### ISSUE TITLE
Mettre le nombre de personne invitées à côté de l'onglet

### ISSUE THREAD

**Issue by emsnytech** [betagouv/tps#1045]
Un petite qw ! mais super...
Manque plus que l'onglet récapitulatif des PJ...

**Comment by mmagn** [comment]
On parle de l'onglet Avis ou Personnes impliquées ? @emsnytech

**Comment by gregoirenovel** [comment]
Pas de précision + pas sur que ça soit bien clair à quoi ce nombre se réfère je pense si on l'affiche (instructeurs ? instructeurs + usager + invités usagers ? usager + invités usagers ?), à mon avis le nombre seul est trop dur à interpréter sans explication. Je propose donc de fermer pour le moment. J'ai aussi du mal à saisir à quelle problématique cela répond.
