### ISSUE TITLE
Il n'y a pas de notifications sur la carto

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#1057]

**Comment by kemenaran** [comment]
Est-ce que maintenant que la carto est un champ ça aide les notifications ?

**Comment by tchak** [comment]
Je ne comprends pas ce que cette issue veut dire

**Comment by mmagn** [comment]
Oui on peut fermer

**Comment by gregoirenovel** [comment]
Ce que ça veut dire c'est : est-ce que si l'usager change un champ carto lorsque le dossier est en construction, l'instructeur qui suit le dossier en est notifié ? Je rouvre tant que c'est pas certain

**Comment by tchak** [comment]
@gregoirenovel c'est un champ comme les autres donc tous les comportements des champs s'appliquent
