### ISSUE TITLE
Explications concernant les emails pas claires sur la page Attestation

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1140]
On peut croire qu'il y a un mail dédié aux attestations (ce qui n'est pas le cas), préciser

**Comment by kemenaran** [comment]
Aujourd'hui le texte dit

> Les attestations, si elles sont activées, sont délivrées par email aux usagers lorsque leurs dossiers sont acceptés, et sont également disponibles au téléchargement sur leur espace personnel.

Ça me semble plutôt clair, non ?

**Comment by gregoirenovel** [comment]
Je trouve que ce n'est toujours pas clair et qu'on peut comprendre que deux emails partent au lieu d'un.

En plus le texte est un peu trompeur sur "sont délivrées" : c'est inexact, un "lien vers la démarche" est délivré.
