### ISSUE TITLE
Dans le cas d'une procédure pour personne physique avec option de renseigner un SIRET à posteriori, il n'y a aucun champ pour renseigner le SIRET sur l'interface usager (ni en brouillon, ni en construction, ni en instruction)

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/tps#1152]

**Comment by fredZen** [comment]
@mmagn @tchak @gregoirenovel @LeSim est-ce qu’on ne devrait pas a minima supprimer l’option dans l’interface administration de création de procédures ? En l’état c’est déceptif !

**Comment by mmagn** [comment]
à communiquer : Work in France

**Comment by mmagn** [comment]
@fredZen je pense à deux options :
- c'est un bug pas compliqué => on fix
- sinon => on cache en attendant d'avoir le vrai champ siret

WDYT ?

**Comment by fredZen** [comment]
@mmagn my thoughts exactly!

**Comment by gregoirenovel** [comment]
En fait y'a WorkInFrance qui en a vraiment besoin pour dans 2 semaines

**Comment by fredZen** [comment]
Pour les procédures avec SIRET optionnel, l’usager peut renseigner son SIRET, en utilisant le bouton entouré sur la capture d’écran ci-dessous. Ce bouton n’est pas accessible pour les brouillons, mais seulement pour les dossiers en construction.

![image](https://user-images.githubusercontent.com/356570/36741379-38089df0-1be5-11e8-854c-6a30dcd8aecb.png)
