### ISSUE TITLE
Il ne faudrait pas proposer la date de passage en instruction sur les templates d’accusé de réception

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#1203]
Filtrer par statut du dossier ?

**Comment by gregoirenovel** [comment]
Un truc similaire à `IS_DOSSIER_TERMINE` ?

**Comment by fredZen** [comment]
Je dirais, oui, même si la multiplication des booléens m’inquiète un peu. J’aurais mieux aimé qu’il y ait un ordre sur `Dossier.state`, et pouvoir spécifier un `min_state`, mais je ne vois pas comment faire (sans changer plus de choses que ça n’en mérite).

**Comment by gregoirenovel** [comment]
`AVAILABLE_FROM_STATE` ?
