### ISSUE TITLE
Rediriger les variantes du nouveau domaine vers le nouveau domaine

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1215]

**Comment by mmagn** [comment]
Le but est d'éviter les fautes d'orthographes, donc un redirect simple devrait suffire

**Comment by mmagn** [comment]
- [x] démarchespubliques.fr
- [x] demarchespubliques.fr
- [x] démarchepublique.fr
- [x] demarchepublique.fr
- [x] démarche-publique.fr
- [x] demarche-publique.fr
- [x] démarches-publiques.fr

**Comment by mmagn** [comment]
@gregoirenovel @tchak @fredZen @LeSim 
je veux bien une review de l'un de vous avant de clore l'issue.

**Comment by gregoirenovel** [comment]
:+1:

**Comment by mmagn** [comment]
Done sur le nouveau NDD
