### ISSUE TITLE
ETQ Instructeur, je veux pouvoir consulter l'attestation telle qu'elle sera vue par l'usager avant de valider le dossier en instruction. 

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/tps#1238]
P.Dubois (Préfecture Pas-de-Calais)

**Comment by kemenaran** [comment]
@emsnytech a écrit :

> Demande formulée par la DGAFP (Plus de 100 000 dossiers)

Le besoin exprimé semble être d'ordre juridique :

> « Il devient possible de visualiser l’attestation qu’après signature, mais la signature équivaut à l’envoi de la dite attestation à l’agent. Cela est une vraie difficulté, puisqu’en principe, l’acte est créateur ou non créateur de droits, est opposable et susceptible de recours contentieux. »

**Comment by kemenaran** [comment]
J'imagine qu'on peut rajouter un lien "Voir l'attestation qui sera envoyée au demandeur" dans la pop-up de confirmation ; ça ouvrirait le PDF généré dans un nouvel onglet du navigateur.

**Comment by mmagn** [comment]
@pengfeidong regarde

**Comment by gregoirenovel** [comment]
Mme A. Perineau (cf. HS 9840)
