### ISSUE TITLE
Le message d'erreur apparait par défaut

### ISSUE THREAD

**Issue by Flightan** [betagouv/tps#1273]
Lorsque l'on souhaite utiliser TPS on arrive sur une page de login qui commence par nous afficher un message d'erreur (car rouge).

<img width="1440" alt="screen shot 2018-01-17 at 10 51 40" src="https://user-images.githubusercontent.com/1475946/35036393-87779ad0-fb74-11e7-873b-53b982c1231e.png">

**Comment by gregoirenovel** [comment]
Dup de #317
