### ISSUE TITLE
Le logo de la démarche n'est pas redimensionné pour respecter l'espace disponible

### ISSUE THREAD

**Issue by Flightan** [betagouv/tps#1274]
<img width="1257" alt="screen shot 2018-01-17 at 10 54 59" src="https://user-images.githubusercontent.com/1475946/35036572-0f25b002-fb75-11e7-8fed-ee72fc78c173.png">

**Comment by mmagn** [comment]
A communiquer : @Flightan

**Comment by mmagn** [comment]
Helpscout : `#1279`

**Comment by maatinito** [comment]
Je viens de tester avec différents logos et tout semble Ok. 
La feuille de style dans new_desiggn/auth.scss précise bien la largeur max dans les deux configurations (petit vs grand ecran)
 ```
.procedure-logos {
    display: flex;
    justify-content: space-around;

    img {
      max-height: 50px;
      max-width: 100%;
      margin: 0 10px;

      @media (min-width: $auth-breakpoint) {
        max-height: 130px;
        max-width: 500px;
      }
    }
  }
```
Donc à moins que quelqu'un ait un logos particulier à me proposer pour tester je propose de clore cette issue.

**Comment by kemenaran** [comment]
Oui, ça a l'air corrigé – et c'est aussi le cas pour le drapeau européen.

<img width="1071" alt="capture d ecran 2018-12-13 a 10 56 22" src="https://user-images.githubusercontent.com/179923/49930857-c3b17700-fec5-11e8-8dd5-bf96cc3d01f7.png">


<img width="1318" alt="capture d ecran 2018-12-13 a 10 55 52" src="https://user-images.githubusercontent.com/179923/49930862-c744fe00-fec5-11e8-9cc1-2aa2e7ca4e27.png">

Je ferme. Merci pour l'investigation !
