### ISSUE TITLE
Le bouton d'inscription pourrait être un peu plus visible

### ISSUE THREAD

**Issue by Flightan** [betagouv/tps#1275]
Lors de nos quelques tests utilisateur, tous ont essayé de créer un compte dans les champs de connexion. Peut-être mettre le lien d'inscription plus en avant ?

<img width="679" alt="screen shot 2018-01-17 at 10 56 41" src="https://user-images.githubusercontent.com/1475946/35036615-2aed79e6-fb75-11e7-93c3-e828ce280544.png">

**Comment by gregoirenovel** [comment]
Dup de #549
