### ISSUE TITLE
Le champs "Lien site internet" devient un lien "En savoir plus"

### ISSUE THREAD

**Issue by Flightan** [betagouv/tps#1276]
Actuellement le champ "Lien site internet" dans la démarche apparait ensuite comme "En savoir plus".
Il me semble que ce sont deux fonctionnalité assez différentes, le lien "En savoir plus" concerne la démarche alors que "Lien site internet" concerne plutôt l'organisme qui gère cette démarche. Ceci est renforcé par le fait que le champ "Lien site internet" se trouve après les champs "Organisme" etc...
<img width="1000" alt="screen shot 2018-01-17 at 10 58 52" src="https://user-images.githubusercontent.com/1475946/35036885-07767778-fb76-11e7-8372-95a48765ead9.png">

<img width="1000" alt="screen shot 2018-01-17 at 11 02 53" src="https://user-images.githubusercontent.com/1475946/35036890-098101b4-fb76-11e7-9bff-a3a141e5c908.png">

**Comment by mmagn** [comment]
Merci, effectivement ce n'est pas clair on va uniformiser ça.

**Comment by mmagn** [comment]
A communiquer : @Flightan

**Comment by chaibax** [comment]
Je pense qu'on peut fermer . Y a plus de lien qui existe. la page a évolué.
