### ISSUE TITLE
Améliorer l'UX de la page "Acceptation des CGU"

### ISSUE THREAD

**Issue by Flightan** [betagouv/tps#1277]
Le bouton "Étape suivante" est en mode `disabled` tant que l'on accepte pas les CGU, le résultat est que l'utilisateur n'a aucun retour sur ce qu'il a mal fait, incompréhension et impression que le site ne marche pas. 
On peut le laisser toujours actif mais ajouter une gestion d'erreur "Vous devez accepter les CGU" / "Le champs nom est obligatoire", etc...

<img width="929" alt="screen shot 2018-01-17 at 11 04 23" src="https://user-images.githubusercontent.com/1475946/35037051-8f0f5088-fb76-11e7-9dfa-c790d438f1ff.png">

**Comment by kemenaran** [comment]
C'est implémenté dans la nouvelle interface utilisateur : le bouton n'est plus désactivé, et on prend un message d'erreur si les CGU ne sont pas acceptées.

<img width="521" alt="capture d ecran 2018-06-25 a 14 52 46" src="https://user-images.githubusercontent.com/179923/41851228-7c493be2-7887-11e8-986c-296c4c2db7fd.png">

**Comment by Flightan** [comment]
Super !
