### ISSUE TITLE
Le label des champs checkbox ne sont pas bien positionnés

### ISSUE THREAD

**Issue by Flightan** [betagouv/tps#1279]
Il est d'usage de placer le label de la checkbox à proximité de la checkbox. Le comportement actuel me semble difficilement utilisable.
<img width="500" alt="screen shot 2018-01-17 at 11 27 47" src="https://user-images.githubusercontent.com/1475946/35038073-da9e5514-fb79-11e7-9057-7e96246071df.png">

**Comment by mmagn** [comment]
C'est le rendu d'un champ d'un formulaire si j'ai bien compris ?

**Comment by Flightan** [comment]
Oui, en ajoutant un champs de type `checkbox`

**Comment by kemenaran** [comment]
Retour de Vince:

> Petit retour d'expérience suite à la publication de https://www.demarches-simplifiees.fr/commencer/api-entreprise
>
> Dans les différences de rendu entre la prévisualisation dans l'admin (dans laquelle nous avons construit le formulaire) et le vrai formulaire front, trois sont problématiques pour nous :
>
> (…)
> * le plus gênant : les checkboxes (qu'idéalement nous aurions aimé à gauche) sont à droite dans l'admin, et, beaucoup plus génant, à la ligne sur le front, ce qui rend notre formulaire pratiquement inutilisable (nous avons une liste de 20 options avec checkboxes, impossible de savoir si la checkbox se rapporte au libellé situé au dessus ou en dessous)

**Comment by kemenaran** [comment]
Je vais voir je peux faire rapidement un label aligné avec la checkbox.
