### ISSUE TITLE
Admin - Passage ancienne interface / nouvelle interface

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1314]
Lorsqu'on accède à la nouvelle interface avec le profil Admin à partir de l'ancienne interface, bug sur la nouvelle interface. 

![nouvelle interface admin chemin](https://user-images.githubusercontent.com/35567048/35154856-0c0cbc90-fd2c-11e7-87e7-a620ac8e8ba6.png)
# #

**Comment by gregoirenovel** [comment]
Le bouton nouvelle interface a été supprimée, ce problème ne se produit plus
