### ISSUE TITLE
Enregistrer vs. Enregistrer et retourner au tableau de bord

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1315]
L’enregistrement de la saisie sur le formulaire provoque un changement de page (redirection vers le tableau de suivi).

Idéalement, il faut distinguer "Enregistrer" (ce qu'on peut faire en cours de saisie pour ne pas perdre son travail) et "Enregistrer et retourner au tableau de bord" (par exemple).

**Comment by gregoirenovel** [comment]
On a aujourd'hui 2 boutons :
- "Enregistrer un brouillon"
- "Enregistrer et voir mes dossiers"

Ce problème a déjà été corrigé. Merci de vérifier que les problèmes sont bien présents avant d'ouvrir des issues.

**Comment by AnthonyBrunelli** [comment]
En effet, j'ai dû attendre entre mes tests et l'organisation d'une réunion où on m'a indiqué l'outil à utiliser, et je ne sais pas ce que vous avez corrigé/mis en place entre temps; je veux bien copier/coller tout ce que j'ai fait et vu dans l'outil, mais je n'ai pas le temps de tout refaire.
