### ISSUE TITLE
ETQ Instructeur, j'aimerais être averti que le texte de la motivation sera visible par les utilisateurs

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1318]
Peut-on indiquer que l'usager aura accès au commentaire (celui que l'accompagnateur peut indiquer en cas d'acceptation ou de refus)?

**Comment by maatinito** [comment]
La première option qui est venue avec @kemenaran  et @LeSim était d'ajouter au dessus ou au dessous un avertissement pour indiquer que l'usager allait recevoir la motivation. 
En y repensant, j'ai pensé que le place holder était aussi une bonne option: 
![image](https://user-images.githubusercontent.com/15379878/49962169-a9bd6780-feb8-11e8-99ff-51c48e2651ca.png)
![image](https://user-images.githubusercontent.com/15379878/49962251-db363300-feb8-11e8-8b77-af1ce7e1d7aa.png)

Avantage du placeholder: il est **lu**. Par exemple, je n'avais jamais remarqué la note qui indique qu'une attestation va être envoyée. Alors qu'au contraire les trois personnes à qui j'ai montré cet écran ont lu le placeholder.
Donc déjà j'aimerai des avis du la position du message: 
1. au dessus 
1. en dessous 
1. en place holder

Reste ensuite la formulation: Celle présentée a l'avantage de mettre l'instructeur dans un mode 'je réponds à l'usager' ce qui l'incite implicitement à de la retenue. C'est une grosse différence avec un message de type 'Cette motivation sera visible par l'usager' qui dépersonalise la motivation. 
On peut préférer l'une ou l'autre pour de bonnes raisons. Les copies d'écran donnent ma préférence. 
A vous de me dire :-)

**Comment by kemenaran** [comment]
Ça me semble un bon usage du placeholder : non pas donner un exemple de ce qui doit aller dans le champ, mais plutôt des précisions sur le contexte dans lequel ça sera utilisé 👍 Et si en plus les gens à qui tu as montré ça le voient vraiment, c'est nickel.

Pour info, il y a une page de [Vocabulaire](https://github.com/betagouv/tps/wiki/Vocabulaire) (et une page de [Typographie](https://github.com/betagouv/tps/wiki/Typographie) aussi) sur le wiki.

Dans le cas présent, le terme technique en interne dans le code serait "Usager" – mais c'est pas très clair : si on se place du point de vue de l'administration (ce qui est le cas ici) "Demandeur" ça me semble très bien.
