### ISSUE TITLE
URL de la démarche

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1323]
Un des critères d'homologation Cerfa concerne l'URL et est actuellement formulé comme suit:

11	L'URL de la démarche en ligne doit être cohérente avec celle du site dont elle dépend. Le nom de domaine appartient à une entité publique.

J'ai compris lors de notre échange que l'URL pour une démarche paramétrée dans TPS était forcément celle de TPS. Me confirmez-vous ce point? (que je puisse voir quoi faire de mon côté si c'est bien le cas)

**Comment by LeSim** [comment]
Oui, je vous confirme ce point. L'ensemble des démarches sont accessibles sous l'URL de TPS.

**Comment by AnthonyBrunelli** [comment]
@LeSim Ok vu, je vais voir s'il y a besoin de reformuler le critère de notre côté.
