### ISSUE TITLE
Charte graphique

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1327]
Un des critères Cerfa concerne la charte graphique:

20	La charte graphique de la démarche en ligne est cohérente avec celle du site qui l'héberge ; elle reprend les éléments de la Charte internet de l'Etat lorsque celle-ci s'applique.

IMPORTANT: la nouvelle charte internet de l'Etat va sortir sous peu; c'est potentiellement un élément important dans le cadre de la refonte de l'interface.

Par ailleurs, j'ai compris lors de notre échange que l'interface de TPS n'était pas paramétrable par rapport à la démarche. Me confirmez-vous ce point? C'est important pour que je voie quoi faire de mon côté.

**Comment by LeSim** [comment]
Oui, je vous confirme que la charte graphique n'est pas paramétrable

**Comment by AnthonyBrunelli** [comment]
@LeSim Ok vu, je vais voir s'il faut ajuster le critère. Etes-vous intéressés par la Charte internet de l'Etat? Ça me semble important. La nouvelle version n'est pas encore publiée, mais j'ai suffisamment d'éléments pour qu'on en discute.

**Comment by LeSim** [comment]
Oui, le sujet nous intéresse mais je ne pense que nous l'implémenterons à court terme.

**Comment by AnthonyBrunelli** [comment]
@LeSim Je peux te joindre par téléphone? J'aimerais te toucher un mot sur le sujet... (je n'ai pas ton num).
