### ISSUE TITLE
Protection des données personnelles

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1329]
Un des critères Cerfa concerne la protection des données personnelles:

23	La démarche en ligne respecte la législation concernant la protection des données personnelles.

Dans le cas de TPS, je ne sais pas qui est légalement responsable des données ni comment la protection des données personnelles est organisées (même si j'ai vu qu'il y avait une déclaration Cnil). Avez-vous des éléments sur ce sujet?

**Comment by LeSim** [comment]
Aujourd'hui, l'infrastructure de TPS est homologuée Référentiel Général de Sécurité.
L'homologation du logiciel TPS est en cours.

Voici ce que j'ai compris pour la partie CNIL:
TPS a fait l'objet d'une déclaration CNIL, et les administrations utilisant TPS sont tenus de respecter les CGU pour être couvert par notre déclaration. Si elle sorte de notre cadre, une déclaration spécifique est nécessaire.

Finalement, les supers administrateurs du site sont informés lors de l'utilisation de champs suspicieux (numéro de sécu ...) dans des procédures et s'assurent alors directement avec les administrations concernées que les démarches CNIL ont bien été effectuées.

**Comment by AnthonyBrunelli** [comment]
@LeSim Ok vu merci. Du coup, j'ai quand même deux questions:
1/ Quel est la différence entre le super administrateur et l'administrateur? Par exemple, moi, je peux créer des formulaires mais je ne suis que administrateur il me semble. Du coup, cette information me concerne non?
2/ Comment est-il informé?

**Comment by LeSim** [comment]
Les supers adminsitrateurs sont grosso modo les membres de l'équipe et en particulier Philippe.
Nous sommes informés par mail lors d'une verification automatique journalière.

Nous contactons alors immédiatement les administrateurs propriétaires des procédures incriminées pour leur demander de régulariser leur situation.
