### ISSUE TITLE
Echange entre administrations

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1330]
Critère Cerfa:

25	Lorsque cela est possible, les données de l’usager ne sont pas redemandées mais obtenues via échange entre administrations (API ...).

TPS donne-t-il la possibilité de remonter d'autres infos que nom-prénom-date de naissance? ex. transport public routier:

![copie ecran quid restitution via franceconnect](https://user-images.githubusercontent.com/35567048/35159965-1ec3297c-fd3c-11e7-97e6-04b35f99257e.png)

**Comment by LeSim** [comment]
Aujourd'hui, des informations publiques sont remontées à partir du numéro siret des entreprises et associations. Ces informations comprennent l'adresse de l'établissement, les derniers exercices financiers, titre et objet ...

Demain, par l'utilisation de France Connect Agent, nous allons mettre en place un méchanisme de récupération de pièces confidentielles.

Je clos cette issue en faveur de France Connect Agent (#1099) et des développements qui vont s'y rattacher.

**Comment by AnthonyBrunelli** [comment]
Ok vu merc.

**Comment by AnthonyBrunelli** [comment]
...je viens de voir l'issue 1099, je n'ai pas l'impression qu'elle traite du cas de l'usager si? 

Si je suis usager (agent ou entreprise), que je me connecte à TPS avec FC, n'y a-t-il pas un lien possible avec certains champs? Adresse & C°...

Par exemple, les champs Adresse, naissance, etc.

**Comment by AnthonyBrunelli** [comment]
J'oubliais: @LeSim

**Comment by LeSim** [comment]
Si l'usager (physique) se connecte avec France Connect, nous pouvons récupérer automatiquement les données suivantes : given_name, family_name, birthdate, gender, birthplace, birthcountry.

Avec France Connect Agent, nous serons en mesure de récupérer plus de données en nous connectant à https://particulier.api.gouv.fr/ et à https://entreprise.api.gouv.fr/website car nous aurons confirmation de l'identité de nos agents.

Ex de données récupérables :
- avis d'imposition
- liasse fiscale
- quotient familiale
- liasse fiscale 
- ...
