### ISSUE TITLE
Nombre de dossiers déposés

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1331]
...parce qu'en plus des critères d'homologation Cerfa des démarches en ligne, on a AUSSI une liste de bonnes pratiques, dont l'une est:

"Le nombre annuel de dossiers déposés par les usagers et la part proportionnelle d’usage des canaux dématérialisés sont accessibles depuis le site de la démarche." (s'entend par démarche, pas pour TPS en général)

TPS permet-il de restituer cette information? (sur la partie démat', bien entendu).

**Comment by emsnytech** [comment]
Cela sera difficile à réaliser... bonne intention à mon avis...

**Comment by LeSim** [comment]
@AnthonyBrunelli TPS ne peut pas savoir la part d'usage dématérialisée. L'administration partenaire qui l'utilise par contre oui. 

Ne pourrait-on pas afficher ce ratio sur le site de l'administration partenaire et pas sur le site TPS ?

**Comment by AnthonyBrunelli** [comment]
@LeSim Nous sommes d'accord. Il faut juste un accès à l'information sur le nombre (et non sur le %) de dossiers transmis par procédure - ce n'est pas à TPS de faire le reste du calcul.

**Comment by LeSim** [comment]
Dans ce cas, le nombre est fourni dans la vue gestionnaire, charge à l'administration de faire le calcul :) .

**Comment by gregoirenovel** [comment]
@AnthonyBrunelli il est également déjà possible d'obtenir ce nombre via notre API
