### ISSUE TITLE
Champ à saisir: nombre de caractères

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1333]
(aspect tout à fait mineur)

Dans les champs texte et zone texte, il n'y a pas de limitation au nombre de caractères? 

(j'ai été surpris qu'il n'y ait pas indiqué le nombre de caractères possible)

**Comment by LeSim** [comment]
Effectivement, il n'y a pas de limite pour les champs de type texte et zone de texte.

**Comment by AnthonyBrunelli** [comment]
@LeSim Ok vu merci. Au passage, j'ai aussi contrôler l'affichage des textes longs dans les champs textes à la lecture, tout ok.
