### ISSUE TITLE
ETQ Expert, lorsque je rends un avis public, l'interface m'indique que mon avis est privé

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1339]
Bug constaté il y 14 jours (des fois qu'il y ait eu des corrections entre temps)

Un accompagnateur sollicite un expert en indiquant que son avis n'est pas confidentiel (ie il est "partagé").
L'expert se connecte: il est indiqué que son avis EST confidentiel et NON partagé.
Un autre expert se connecte: il peut consulter ledit commentaire qui n'est donc pas confidentiel.

[mais quand la conf est demandée, elle semble respectée]

NB: un expert peut solliciter un autre expert... à indiquer

NBbis: tout expert peut participer à l'échange de message... et l'usager qui a remplit le formulaire voit tout. Est-ce souhaitable? Retours utilisateurs?? A minima, l'indiquer!

**Comment by mmagn** [comment]
@pengfeidong regarde
