### ISSUE TITLE
Donner le moyen de déposer une nouvelle demande sur une procédure à laquelle on a déjà répondu

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#134]
Du genre bouton "Déposer un nouveau dossier"

**Comment by emsnytech** [comment]
Cette fonctionnalité va s'avérer très intéressante pour les dossiers de politique de la ville. (Pas de Calais et Nord)

**Comment by fredZen** [comment]
Dupliqué dans #892 – je garde ce dernier car il contient des conversations plus riches
