### ISSUE TITLE
Accompagnateur nouvelle interface changement d'état

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1342]
Le passage de "en instruction" à "en construction" puis de "en construction" à "avis" quelqu'il soit ne sont pas visibles (pas intuitif pour trouver où le faire).

**Comment by AnthonyBrunelli** [comment]
@LeSim Suite à ta question par mail: c'est juste que j'ai mis un peu de temps à trouver que c'était en cliquant sur le bouton en haut à droite que je pouvais effectuer des actions (changement d'état) en tant qu'accompagnateur... Après, une fois qu'on le sait c'est bon.

Je ne sais pas si vous avez d'autres retours utilisateurs sur le sujet - et je ne mettrai pas ma main à couper sur la pertinence de ma remarque.  J'ai plus l'habitude des boutons qui apparaissent en bas du formulaire, en fonction de l'état de celui-ci.

On en rediscute si tu le souhaites.

![changement etat](https://user-images.githubusercontent.com/35567048/35289448-ac5f8e3c-0067-11e8-9b9a-2615045abf54.png)

**Comment by LeSim** [comment]
Je clos cette issue du coup !
