### ISSUE TITLE
Répétition du nom du champ dans la zone de saisie

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1344]
(oui, c'est du mineur)

Y a-t-il une raison particulière pour laquelle le nom du champ est répété dans la zone de saisie?

A priori, ça ne me semble pas indispensable.

**Comment by LeSim** [comment]
Effectivement, ce texte n'apporte pas beaucoup de valeur.
https://github.com/betagouv/tps/issues/1295 propose de le remplacer par des exemples.

Je ferme cette issue en faveur de https://github.com/betagouv/tps/issues/1295
