### ISSUE TITLE
Accompagnateur: pb restitution dossier en construction

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1356]
Cf. copie d'écran ci-après: il manque un dossier dans la liste en construction...

...MAIS comme le dossier qui manque est celui fait par l'accompagnateur lui-même (avec son profil usager) c'est a priori un cas rare - et ça explique peut-être le bug.

![nombre de dossiers](https://user-images.githubusercontent.com/35567048/35270923-ca653332-0030-11e8-96f0-92ea338f1ad6.png)

**Comment by LeSim** [comment]
Il y a 2 dossiers traités : 30736 et 30805.

Il y a 3 dossiers en constructions mais le dossier 30719 est suivi par un gestionnaire (dont l'email commence par `aybi...`)

Il n'est donc plus à suivre ce qui explique la case `à suivre 2`.

**Comment by gregoirenovel** [comment]
Ce sujet est lié à l'issue #907, qui, une fois traité, devrait aussi résoudre l'incompréhension à l'origine de cette issue

**Comment by AnthonyBrunelli** [comment]
Au temps pour moi!
