### ISSUE TITLE
Bump SmartListing version

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#1360]

**Comment by fredZen** [comment]
Le commit comporte deux contournements à enlever quand le problème correspondant aura été corrigé upstream:

https://github.com/betagouv/tps/commit/a4aba563f66533aa98eaf7f3970cc667a84cdf73#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R77 est un contournement de https://github.com/Sology/smart_listing/issues/126 

https://github.com/betagouv/tps/commit/a4aba563f66533aa98eaf7f3970cc667a84cdf73#diff-20ab6677da23c9aebc3acf6d7aa19fc6R32 est un contournement de https://github.com/Sology/smart_listing/issues/134

**Comment by fredZen** [comment]
cas restant potentiellement à traiter (utilisent smart_listing, pas de test qui casse, mais c’est peut-être bien parce-qu’il manque le test)

- ./app/controllers/admin/gestionnaires_controller.rb:    @gestionnaires = smart_listing_create :gestionnaires,
- ./app/controllers/admin/procedures_controller.rb:    @procedures = smart_listing_create :procedures,
- ./app/controllers/admin/procedures_controller.rb:    @procedures = smart_listing_create :procedures,
- ./app/controllers/admin/procedures_controller.rb:    @procedures = smart_listing_create :procedures,
- ./app/controllers/admin/accompagnateurs_controller.rb:    @accompagnateurs_assign = smart_listing_create :accompagnateurs_assign,
- ./app/controllers/admin/accompagnateurs_controller.rb:    @accompagnateurs_not_assign = smart_listing_create :accompagnateurs_not_assign,

**Comment by gregoirenovel** [comment]
Je suis à moitié convaincu par ce que je vais proposer : est-ce qu'on veut pas attendre les erreurs Sentry avant de s'attaquer à ces cas ?

**Comment by gregoirenovel** [comment]
Fixed by #1592
