### ISSUE TITLE
Redesign signup/login

### ISSUE THREAD

**Issue by MarineCrespel** [betagouv/tps#138]
Harmoniser la page de signup/login avec la nouvelle landing page.

**Comment by MarineCrespel** [comment]
https://invis.io/EDAVZVNS7#/230898741_1-Login

**Comment by MarineCrespel** [comment]
Forgot password
https://invis.io/EDAVZVNS7#/231699066_2A-Reinitialisation_Mdp

**Comment by MarineCrespel** [comment]
Signup guest/users (sans le numéro de dossier)
https://invis.io/EDAVZVNS7#/231728175_3-Signup

**Comment by kemenaran** [comment]
C'est fait.
