### ISSUE TITLE
Date en anglais sur l'attestation PDF

### ISSUE THREAD

**Issue by kemar** [betagouv/tps#1389]
La date est en anglais sur l'attestation PDF générée par TPS, c.f. l'image ci-dessous :

<img width="1275" alt="attestation" src="https://user-images.githubusercontent.com/281139/35636174-9ff9e4b8-06b0-11e8-8a5f-164e8ae988d2.png">

**Comment by mmagn** [comment]
Merci pour ce retour. Peux-tu nous dire à quel point c'est bloquant / pressé pour vous ?

Pour info on est ouvert aux contributions extérieures, si tu es intéressé par résoudre ce bug on sera ravi de t'aider. 😃

**Comment by kemar** [comment]
@mmagn merci pour ton retour, malheureusement je ne connais pas le Ruby sinon j'aurais fixé tout de suite. Je pense que ça se joue ici https://github.com/betagouv/tps/blob/c8a090ad800fa71ce2cff3ea21556ab7d49755ae/app/views/admin/attestation_templates/show.pdf.prawn#L18 mais je ne sais pas comment fonctionnent les locales avec les dates en Ruby.

Si tu veux bien fixer pour nous dès que possible ça serait gentil parce que ça ne fait pas très sérieux pour un service étatique français d'afficher une partie de texte en anglais dans une attestation. Ça décrédibilise la solution.

**Comment by mmagn** [comment]
Effectivement tu as bien localisé le problème. L'issue est priorisée, ça devrait être réglé dans les prochains jours.

**Comment by fredZen** [comment]
Très probablement causé par le même défaut que #1392 et #1398 .

Je viens de regarder sur l’historique des attestations générées en prod : 
- parmi toutes les attestations générées jusqu’au 26 janvier inclus, aucune de celles que j’ai regardée ne présente de date en anglais
- parmi le attestations générées depuis le 31 janvier inclus, un grand nombre présente une date en anglais

il n’y a malheureusement pas eu d'attestation générée entre le 26 et le 31

**Comment by fredZen** [comment]
Donc, on dirait qu’on a introduit une régression entre le 26 et le 31 janvier

Comme nous n’avons pas touché au code d'i18n, je soupçonne un bump de gemme

**Comment by fredZen** [comment]
semble résolu par la dernière montée de version
=> dans quelques jours, si toutes les nouvelles attestations générées depuis aujourd’hui ont bien la date en français, et le cas échéant fermer ce bug.

**Comment by fredZen** [comment]
Le bug est revenu... peut-être qu’il ne se produit que sur des serveurs qui tournent depuis en certain temps ? Ce qui expliquerait pourquoi il se produit si rarement en local sur un poste de dev.

**Comment by mmagn** [comment]
On va contacter un marabout pour désenvouter les serveurs...
