### ISSUE TITLE
Le bouton "Créer un compte" est peu visible

### ISSUE THREAD

**Issue by kemar** [betagouv/tps#1390]
En 1280x800 il faut scroller quand on a pas de compte. Serait-il envisageable de modifier l'interface pour égaliser le niveau de visibilité de connexion et de création de compte ?

![capture_d ecran_2018-01-31_a_18_02_21](https://user-images.githubusercontent.com/281139/35636388-3d580168-06b1-11e8-831b-979b7fe60956.png)

**Comment by gregoirenovel** [comment]
Dup de #549

**Comment by kemar** [comment]
@gregoirenovel je me permets d'insister un peu là dessus : on a fait 13 tests utilisateurs hier sur une population d'étudiants et chaque utilisateur s'est systématiquement trompé en utilisant la zone de login en pensant créer un compte. 100% d'erreur pour les utilisateurs qui n'ont pas de compte.

**Comment by gregoirenovel** [comment]
Yes, c'est pas clair, on va corriger ça avec la nouvelle interface usager.
