### ISSUE TITLE
Visibilité du bouton "Créer un compte"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#1391]
Dans de nombreux cas, l'usager doit créer un compte pour saisir un formulaire. Le bouton idoine n'est pas assez visible, et surtout n'apparaît pas à l'écran sans faire défiler la page sur les ordinateurs portables (il est trop bas).

Vu avec l'équipe de WorkinFrance.

**Comment by gregoirenovel** [comment]
Dup de #1390, lui même dup de #549

**Comment by AnthonyBrunelli** [comment]
Ah ok merci.
