### ISSUE TITLE
Message signalant la nécessité de se connecter pour déposer un nouveau dossier à mettre en français

### ISSUE THREAD

**Issue by icollombet** [betagouv/tps#1392]
![capturefrancais](https://user-images.githubusercontent.com/18182552/35674563-4bd2d724-0745-11e8-8eee-0b988ec230a0.PNG)

**Comment by fredZen** [comment]
J’arrive à reproduire le problème de façon intermittente quand je configure mon navigateur pour demander des pages en anglais de préférence.

**Comment by fredZen** [comment]
Mais parfois, même dans ce cas là, ça me sort du Français... étrange

**Comment by fredZen** [comment]
@icollombet si tu arrives à le reproduire de façon systématique, il faut qu’on se voie ! Chez moi, ça l’a fait il y a 5 jours, mais plus moyen de le reproduire.

**Comment by fredZen** [comment]
En fait, je n’arrive plus à le reproduire sur mon poste de dev, mais j’arrive bien à le produire de façon intermittente sur la dev et la prod

**Comment by fredZen** [comment]
Semble résolu par la montée de version + quasi-doublon de #1389 => je ferme
