### ISSUE TITLE
cacher le champ « envoyer à un autre accompagnateur » si je suis le seul accompagnateur sur la procédure

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#1397]
Peut-être supprimer tout le bloc si je suis le seul accompagnateur ?

Ou alors laisser le titre, mais remplacer la select-box + bouton par un texte « vous êtes le seul accompagnateur sur cette procédure » ?

![screenshot from 2018-02-02 16-06-26](https://user-images.githubusercontent.com/356570/35739800-201055a0-0833-11e8-99a7-2675d8cac4c2.png)

**Comment by gregoirenovel** [comment]
Le cacher me semble bien

**Comment by fredZen** [comment]
ça a été mon premier choix aussi,

et puis après je me suis dit qu’une option disponible sur certaines procédures et pas sur d’autres, sans explication visible, risque de dérouter les accompagnateurs... « tiens, d’habitude je peux envoyer des dossiers, pourquoi ça ne marche pas là ? peut-être que je ne regarde pas au bon endroit »

du coup, pour respecter le _principe de moindre surprise_, je me demande s’il ne vaut pas mieux laisser une trace de la feature même quand elle est indisponible. Un peu comme la section « Accompagnateurs qui suivent le dossier », d’ailleurs.

**Comment by gregoirenovel** [comment]
Je n'ai pas d'avis tranché, et je suis d'accord avec ton raisonnement :)

**Comment by mmagn** [comment]
On pourrait laisser le titre de la feature et à la place des boutons mettre en italique : _vous êtes le seul accompagnateur assigné sur cette procédure_ (ou un autre wording)
