### ISSUE TITLE
Afficher les nombres en français dans la page /stats

### ISSUE THREAD

**Issue by icollombet** [betagouv/tps#1398]
En français, les nombre ne prennent pas de virgule entre les milliers et les centaines mais un espace insécable : 11,000 => 11 000
![affichagestatsfrancais](https://user-images.githubusercontent.com/18182552/35797046-bd86cbac-0a5e-11e8-8dac-c0c5e30e80fd.PNG)

**Comment by gregoirenovel** [comment]
Lié à #1392 ?

**Comment by fredZen** [comment]
Oui, c’est certainement la même cause sous-jacente. Quand on rafraîchit la page, ça produit, aléatoirement, tantôt la version française, tantôt la version anglaise (vu sur la prod et la dev).

**Comment by fredZen** [comment]
Semble résolu par la montée de version + quasi-doublon de #1389 => je ferme
