### ISSUE TITLE
Je voudrais que le bouton pour inviter un collaborateur soit en Français

### ISSUE THREAD

**Issue by emsnytech** [betagouv/tps#1416]

**Comment by emsnytech** [comment]
![capture d ecran 2018-02-08 a 22 14 23](https://user-images.githubusercontent.com/27733126/35998703-c06a8590-0d1d-11e8-8241-f3535a6a06b2.png)

**Comment by fredZen** [comment]
@emsnytech pour info, quand nous écrivons _ETQ_, c’est les initiales « En Tant Que ». Ça nous sert à indiquer si une fonctionnalité concerne les instructeurs, les usager ou les administrateurs : « ETQ usager », «ETQ admin » etc.

Du coup je me suis permis de le supprimer le « ETQ » vide du titre de ce ticket.

**Comment by gregoirenovel** [comment]
C'est pas un bug du aux problèmes de locale ? Et du coup on peut fermer ?

**Comment by fredZen** [comment]
@gregoirenovel je pense oui, je suis en train de vérifier par acquit de conscience avant de fermer

**Comment by fredZen** [comment]
Je confirme, c’est la même cause sous-jacente que #1389 , ce sera corrigé à la prochaine mise en prod

**Comment by emsnytech** [comment]
Ok 👌 

Envoyé de mon iPhone
