### ISSUE TITLE
ETQ Administrateur: je veux parametrer une date de silence valant acceptation / rejet

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#1420]
se calcule à partir de la date de passage en instruction du dossier + une durée fixe par procédure.

**Comment by LeSim** [comment]
Université de Nantes

**Comment by gregoirenovel** [comment]
Engagement pour le 1/7

**Comment by mmagn** [comment]
Vu avec le juridique, trop complexe pour traiter ce sujet de façon automatique maintenant.
La solution sera mise en place avec les templates d'emails proposés par le juridique.

**Comment by fredZen** [comment]
J’ai l’impression que tout ce qui devait être communiqué sur ce ticket l’a été. J’enlèverai prochainement le label `à communiquer`.

**Comment by gregoirenovel** [comment]
On peut enlever tout de suite, comme on n'a rien fait on n'a rien à communiquer je pense :)
