### ISSUE TITLE
Faire des listes déroulantes liées (conditionnel)

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#1421]
Université de Nantes

**Comment by gregoirenovel** [comment]
Lié à #834

**Comment by gregoirenovel** [comment]
Engagement pour le 1/7

**Comment by guillaume-cellier** [comment]
Est-ce que la fonctionnalité est maintenant accessible (j'avais vu qu'elle le serait à partir du 01/07) ?
Merci.

**Comment by LeSim** [comment]
Oui, je viens de l'activer pour votre profile admin. 
Elle est un peu rustique pour l'instant, faites attention à bien respecter le format suivant
```
--A--
a1
a2
--B--
b1
b2
```
Avec A et B les choix de la première liste, a1, a2 ... les choix de la seconde

**Comment by guillaume-cellier** [comment]
Je n'avais pas compris que toutes les informations des listes déroulantes devaient être présentes dans un seul champ. J'avais créé une première liste avec les possibilités A ou B puis créé deux nouvelles listes (l'une nommée A, l'autre B). Maintenant que j'ai compris ça fonctionne.

Par contre pour être franc, cela répond pas vraiment aux problématiques qu'on rencontre : la plupart du temps se sont des champs de saisie qui devraient être conditionnels.
Par exemple : 
Êtes-vous propriétaire ou locataire ? 
Si l'utilisateur est propriétaire, alors une liste de champs à renseigner s'affiche. S'il est locataire, la liste sera différente et surement beaucoup plus courte.

Pour l'instant, nous avons géré ces cas en créant des sections propres aux locataires, aux propriétaires mais le formulaire devient rapidement très long lorsqu'il y a plus de 2 possibilités et l'utilisateur n'a pas la possibilité de sauter des sections comme il pourrait le faire à la lecture d'un formulaire papier.

Vous avez peut-être engagé une réflexion sur cette problématique, je pense qu'une possibilité serait d'envisager de rendre les sections conditionnelles pour s'affranchir d'une gestion complexe des conditions sur chaque champ du formulaire.

**Comment by kemenaran** [comment]
@fredZen tu crois qu'on peut fermer cette issue ?

**Comment by guillaume-cellier** [comment]
Bonjour,

Disons que la fonctionnalité permettant de lier 2 listes déroulantes existe maintenant.
Par contre, ma problématique initiale concernait plutôt des champs de saisie conditionnels.

Par exemple :
Êtes-vous propriétaire ou locataire ?
Si l'utilisateur est propriétaire, alors une liste de champs de saisie s'affiche. S'il est locataire, la liste sera différente et surement beaucoup plus courte.

Pour l'instant, nous avons géré ces cas en créant des sections propres aux locataires, aux propriétaires mais le formulaire devient rapidement très long lorsqu'il y a plus de 2 possibilités et l'utilisateur n'a pas la possibilité de sauter des sections comme il pourrait le faire à la lecture d'un formulaire papier.

Vous avez peut-être engagé une réflexion sur cette problématique, je pense qu'une possibilité serait de rendre les sections conditionnelles pour s'affranchir d'une gestion complexe des conditions sur chaque champ du formulaire.

**Comment by fredZen** [comment]
@guillaume-cellier la fonctionnalité que vous évoquez (un conditionnel généralisé, qui pourrait en effet s’envisager sur une base de pages conditionnelles) est suivie en #834.

Cette fiche-ci ne concerne que le conditionnel limité aux menus à double entrée, et je met permets donc de la fermer.
