### ISSUE TITLE
Corriger les explications sur le suivi des dossiers dans la documentation

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#1435]
Il y a une erreur dans la doc, quand on dit que “Une fois le dossier suivi, l’accompagnateur a accès à un ensemble de fonctionnalités facilitant le traitement du dossier ...“, ces fonctionnalités sont disponibles sur tous les dossiers.

**Comment by gregoirenovel** [comment]
Améliorer "facilitant" pour quelque chose de plus correct ?

**Comment by CamilleGarrigue** [comment]
Modifications effectuées sur la doc.
