### ISSUE TITLE
Tooltip en anglais quand je n’accepte pas les CGU

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#1495]
![image](https://user-images.githubusercontent.com/356570/36741054-67d3a8d2-1be4-11e8-934a-a3cb06fb1927.png)

**Comment by LeSim** [comment]
Sous quel navigateur ?

j'ai le bon texte sous ff ... et je me dis que ca dépend de la local de ton navigateur

**Comment by fredZen** [comment]
Mon navigateur est en locale Française. Par contre le gros de mon OS est en locale EN => ça dépend peut-être de la locale serveur. Je ferme du coup ?
