### ISSUE TITLE
Accusés de réception pas envoyés dans la nouvelle interface usager

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#1510]
Cc @mmagn @LeSim 

Dans l’ancienne interface usager, c’est le contrôleur qui envoyait le mail d’accusé de réception (on est d’accord que ce n’est pas son rôle) : dans `Users::DescriptionController::update`, aux alentours de la ligne 55

```ruby
      if dossier.brouillon?
        dossier.en_construction!
        # TODO move to model
        NotificationMailer.send_notification(dossier, procedure.initiated_mail_template).deliver_now!
      end
```

`NewUser::DossierController::update` ne reprend pas l’envoi de mail, ce que, en soi, je trouve plutôt très bien. Mais du coup, il faut bien le faire quelque part.

Si ça vous va, je vous propose de faire l’envoi du mail depuis `Dossier::send_dossier_received`, et je me porte volontaire pour le coder. (Et si vous voulez le faire autrement ça me va aussi)

**Comment by mmagn** [comment]
👍  ça me parait pas mal ce que tu proposes.

**Comment by fredZen** [comment]
à notifier : helpscout `#1528`

**Comment by gregoirenovel** [comment]
À communiquer : `#1604`

**Comment by gregoirenovel** [comment]
Faire une moulinette qui traite les cas où les emails ne sont pas partis
