### ISSUE TITLE
installation tps

### ISSUE THREAD

**Issue by kaktus40** [betagouv/tps#1532]
Bonjour,
je souhaiterais installer TPS dans un réseau isolé d'internet. Quels sont les prérequis et le guide d'installation pour une mise en production?

**Comment by gregoirenovel** [comment]
Bonjour,

Malheureusement TPS n'a pas été conçue pour exister avec plusieurs instances :
- le logiciel n'a pas été architecturé pour être déployé dans un autre contexte que le notre
- le nom et design de notre site ne doivent se retrouver que sur un seul site pour éviter toute confusion pour les usagers
- l'application dépend de plusieurs composants réservés à l'administration auxquels l'accès n'est pas immédiat : FranceConnect, API Entreprise
- l'application dépend de plusieurs composants techniques : compte MailJet, compte CleverCloud, compte OVH Object Storage, application GitHub
