### ISSUE TITLE
Supprimer le formatting des champs de type "textarea"

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1543]
Dans la nouvelle UI usager, on n'a plus de formatting, donc les valeurs remplies avec l'ancienne interface s'affichent mal, car on ne les a pas migrées.

Faire un script de migration

À communiquer : `#1574`

**Comment by gregoirenovel** [comment]
Hint : a05217b364fda3716aa877aa213a7c84a50bc165

**Comment by fredZen** [comment]
devrait régler #1287 dans la foulée
