### ISSUE TITLE
Envoyer un lien vers l'attestation au lieu d'une PJ

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1563]
C'est moins bien niveau UX, mais :
- ça nous fait moins de code (pas de gestion des PJs)
- c'est mieux d'un point de vue sécurité, on n'enverra alors rien de trop sensible par email

**Comment by fredZen** [comment]
Supprimer la PJ c’est la partie facile :-) (fait sur [frederic/fix_1563-remove_attestation_pj](https://github.com/betagouv/tps/tree/frederic/fix_1563-remove_attestation_pj))

Pour insérer le lien vers l’attestation, on fait quoi ? Je vois trois cas à gérer :

1. les procédures **sans attestation** ;
2. les procédures **avec attestation**, avec template de **mail d’acceptation standard** ;
3. les procédures **avec attestation**, avec template de **mail d’acceptation personnalisé**

Je voudrais satisfaire les contraintes suivantes :

- pour les procédures sans attestation
  - rien ne doit changer par rapport au comportement actuel, il faut que le mail continue à ne pas parler d’attestation (contrainte 1.1) ;
- pour les procédures avec attestation, avec template standard
  - on voudrait que le mail envoyé comporte une petite phrase du genre « Vous pouvez télécharger votre attestation cette adresse : » (wording perfectible) suivie d’un lien vers https://demarches-simplifiees.fr/dossiers/12345/attestation (contrainte 2.1) ;
- pour les procédures avec attestation, avec template personnalisé
  - ne pas imposer à l’administrateur la phrase descriptive avant le lien (contrainte 3.1) ;
  - permettre à l’administrateur de placer le lien où il veut dans le mail (contrainte 3.2) ;
- Aider l’administrateur à bien configurer sa procédure s’il touche à la fois aux attestations et au template d’acceptation
  - si la procédure a une attestation, mais que le template de mail personnalisé ne comporte pas la balise, ou à l’inverse, si le template de mail comporte la balise de lien mais qu’il n’y a pas d’attestation sur la procédure, avertir l’administrateur du problème qu’il vient de créer (contrainte 4.1)

Solution proposée

- on crée une nouvelle balise `--lien attestation--` ;
- on crée deux templates de mail d’acceptation par défaut, l’un pour les procédures avec attestation (et qui comporte la nouvelle balise), l’autres pour celles sans ;
- `Mails::ClosedMail.default_for_procedure` choisit le bon template en fonction du type de procédure ;
- Dans l’interface d’admin, on notifie l’administrateur si le template de mail personnalisé n’est pas cohérent avec la présence d’attesation
  - quand il vient de changer l’attestation ;
  - quand il vient de changer le template de mail d’accepation ;
  - sur la page « informations » (comme garde-fou pour un administrateur qui n’aurait pas immédiatement réagi à une des notifications précédentes)

Ça fait pas mal de taf mine de rien.
Des idées pour simplifier ? Des contraintes qu’on pourrait faire sauter, au moins dans un temps 1 ?
