### ISSUE TITLE
Retirer la limite à 50px de hauteur sur les boutons

### ISSUE THREAD

**Issue by nicolasbocquet** [betagouv/tps#1566]
Pour déposer des demandes en toute simplicité, nous aurions besoin que les règles css

`.role-panel-button-primary {...}` et `.role-panel-button-secondary {...}` ne possèdent pas de `height: 50px;`

![dxojaiqx0aal5uc jpg large](https://user-images.githubusercontent.com/3034108/37058254-37f5aae2-218a-11e8-9099-48bc823b1e8f.jpg)

**Comment by mmagn** [comment]
Merci pour le retour. Pouvez-vous nous indiquer comment reproduire ce comportement ? De façon à pouvoir s'assurer que le correctif sera efficace.

**Comment by nicolasbocquet** [comment]
Navigateur utilisé : Firefox
Dans le menu de Firefox, activer : Affichage > Zoom > Zoom Texte Seulement

https://www.w3.org/Translations/WCAG20-fr/#visual-audio-contrast-scale

**Comment by mmagn** [comment]
Merci, la pull request est prête https://github.com/betagouv/tps/pull/1569, ça devrait être déployé dans la journée d'aujourd'hui ou de demain.
