### ISSUE TITLE
Faire sauter font-awesome

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1584]
Ça devrait faire sauter l'appel à une API Google pour la gestion des typos

**Comment by tchak** [comment]
Je ne suis pas sur de l'usage de `font-awesome` sur le site actuellement mais c'est quand même pratique pour les icônes, et il n'y a aucune raison que ça utilise l'API Google pour la gestion des typos. Donc peut-être just ne pas utiliser l'API Google webfonts pour charger `font-awesome` ?

**Comment by gregoirenovel** [comment]
T'as raison c'est moi qui ai mal analysé le problème, c'est le widget Mailjet qui fout la merde
