### ISSUE TITLE
problème de sécurité pour les liens avec target=_blank

### ISSUE THREAD

**Issue by dzc34** [betagouv/tps#1591]
> "Mathias Bynens l’a illustré de manière très explicite : l’utilisation d’un attribut target="_blank" sur un lien hypertexte permet à la page web ouverte de déclencher un changement de page dans la fenêtre d’origine."  https://blog.dareboost.com/fr/2017/03/target-blank-rel-noopener-securite-performance/

> target="_blank" is an exposable vulnerability when used on your links without the addition of the following rel="noopener noreferrer" attribute. 
https://twitter.com/RobertCooper_RC/status/971803428518285312

Démo : 
- https://mathiasbynens.github.io/rel-noopener/  (démo la plus explicite)
- https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/

solution :  ajouter l'attribut `rel="noopener noreferrer"`
`<a href="" target="_blank" rel="noopener noreferrer"></a>`

et en complément : https://caniuse.com/#feat=rel-noopener

**Comment by fredZen** [comment]
Voir aussi #1590
