### ISSUE TITLE
ETQ usager, je souhaite pouvoir entrer mon numéro RNA pour identifier la structure (à la place du SIRET)

### ISSUE THREAD

**Issue by emsnytech** [betagouv/tps#1598]
AUjourd'hui, le champs SIRET n'accepte que les SIRET.
Il serait souhaitée par les administrateur de proposer aussi le numéro RNA.

Deux approche, Créer deux champs
ou
Faire en sorte que le champs SIRET accepte aussi les numéro RNA, avec possibilité de le reconnaitre pour taper alors la base RNA en premier.
A signaler que l'API entreprise prend à priori en compte aussi bien le num SIRET que le RNA en entrée.

**Comment by gregoirenovel** [comment]
Dupliqué de #139
