### ISSUE TITLE
Faire le point sur l'intégration Pipedrive dans HelpScout

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1603]

**Comment by chaibax** [comment]
L'Intégration est fonctionnel, ca marche. Je l'utilise régulièrement.

**Comment by gregoirenovel** [comment]
OK, on ferme alors :)

**Comment by gregoirenovel** [comment]
(si c'est utile on garde, pas besoin de rétrograder l'abonnement)
