### ISSUE TITLE
Les sauts à la ligne ne sont pas conservés dans les champs de type "zone de texte"

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1614]
> Pour l'instant j'ai fait de la mise en forme sommaire à l'aide d'espaces, tirets et retours à la ligne mais dès qu'on valide le dossier, les retours à la ligne ne sont pas pris en compte et la lecture des zones de texte devient presque illisible.

Cf. HS `#1574`

À communiquer : `#1574`

**Comment by emsnytech** [comment]
Je confirme, ce point est particulièrement gênant quand il faut lire à l'écran les dossiers longs....

**Comment by fredZen** [comment]
communiqué à l’instant
