### ISSUE TITLE
ETQ Usager je veux voir la liste de mes dossiers

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#1623]
https://projects.invisionapp.com/d/main#/console/11285888/240792463/preview

**Comment by kemenaran** [comment]
Une implémentation presque complète existe déjà dans `/dossiers`.

Étapes nécessaires pour une mise en prod de cette page :

- [ ] Rediriger chaque item de la liste vers la page `/dossier/:id` correspondante
- [ ] Permettre de trier les colonnes par ordre croissant ou décroissant
- [ ] Rajouter les encarts expliquant la signification de chaque statut
- [ ] Vérifier le fonctionnement avec des dossiers "Invités"
- [ ] Tester la vue
- [ ] Supprimer l'ancien code
