### ISSUE TITLE
Création automatique de compte admin (demander l'accès)

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#167]
1. Ajouter pour des utiilisateurs précis (ivan, philippe) un lien vers l'interface superadmin dans le selecteur de compte
2. Dans l'interface superadmin, ne laisser qu'un champ pour entrer l'email d'un futur administrateur
3. Soumettre le formulaire envoie un lien à l'adresse mail indiqué, lien qui va vers une page de création de mot de passe pour l'administrateur concerné

**Comment by LeSim** [comment]
closed by #1095
