### ISSUE TITLE
Envoyer les mails de refus directement depuis manager

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1670]
- [ ] Depend de #1601 

Avoir un bouton pour refuser une demande, qui envoie alors un email de refus

**Comment by LeSim** [comment]
Nouvelle spec :
- ETQ super admin: je peux créer un compte admin en l'affectant directement a un pipeline adequat
- ETQ super admin: je peux supprimer une demande d'admin ce qui a pour conséquence de `perdre` le deal + note sur pipedrive
