### ISSUE TITLE
Co-construction impossible pour un utilisateur multi-profil

### ISSUE THREAD

**Issue by kemar** [betagouv/tps#1677]
Un utilisateur qui a le double profil `usager` et `agent` et qui est invité à co-construire un dossier ne peut pas l'éditer.

##### Comportement attendu

L'utilisateur avec double profil `usager` et `agent` peut co-construire le dossier en mode `usager`.

##### Résultat actuel

L'utilisateur avec double profil `usager` et `agent`, lorsqu'il est en mode `usager` et qu'il clique sur le bouton "ÉDITER" afin de co-construire, est automatiquement basculé en mode `agent` et ne peut pas co-construire le dossier.

##### Étapes pour répliquer

1. Déposer un dossier
1. Inviter un co-constructeur multi-profil (`usager` et `agent`) à co-construire le dossier
1. Se déconnecter
1. Suivre le lien envoyé par e-mail au co-constructeur
1. Se connecter en tant que co-constructeur et s'assurer d'être en statut `usager`
1. Trouver le bouton "ÉDITER" (cf. screenshot ci-dessous)
1. Cliquer sur "ÉDITER"

![captureds](https://user-images.githubusercontent.com/281139/37661645-96a0ca38-2c55-11e8-9816-7335792eed6e.png)

**Comment by fredZen** [comment]
Dans une variante intéressante du bug, avec mon jeu de données le bouton « Éditer » n’apparaît même pas pour l’usager/instructeur invité

**Comment by fredZen** [comment]
Note au passage : la co-construction est cassée même pour les invités qui ne sont pas instructeurs :-(

**Comment by kemar** [comment]
Ah zut, il faudrait mettre des tests unitaires là dessus !

**Comment by fredZen** [comment]
A minima automatisés, et idéalement unitaires, oui.

**Comment by kemar** [comment]
Thanx @fredZen :)
