### ISSUE TITLE
Balise contenant une apostrophe typographique non évaluée dans l'attestation

### ISSUE THREAD

**Issue by kemar** [betagouv/tps#1681]
Une balise contenant une apostrophe typographique (`’` vs `'`) n'est pas évalué dans l'attestation.

Par exemple : `--Nombre d’heures--` ne sera jamais évalué correctement dans l'attestation.

##### Comportement attendu

La balise `--Nombre d’heures--` est remplacée par la valeur du champ correspondant dans l'attestation PDF.

##### Résultat actuel

`--Nombre d’heures--` apparaît tel quel en toutes lettres dans l'attestation PDF.

##### Étapes pour répliquer

1. Choisir une procédure
1. Créer un champ dont le *Libellé* contient une apostrophe typographique, par ex. `Nombre d’heures`
2. Utiliser la balise `--Nombre d’heures--` dans l'attestation
3. Déposer un dossier
4. Instruire et valider le dossier
5. Ouvrir le PDF généré pour constater

**Comment by fredZen** [comment]
Je ne reproduis pas, sur mon cas de test la balise avec apostrophe typograghique `’` est bien substituée. @kemar peux tu me donner le numéro d’une procédure qui exhibe le problème ?

**Comment by kemar** [comment]
@fredZen nope j'ai delete la procédure concernée après avoir cherché pendant 20 minutes pourquoi la balise n'était pas évaluée.

Si tu ne reproduis pas, tu peux peut-être tenter avec un champ contenant une apostrophe typograghique et une balise contenant une apostrophe simple ?

**Comment by fredZen** [comment]
oui, si tu as une apostrophe bête et méchante `'` d’un côté et une apostrophe belle et gentille `’` de l’autre, elles ne vont pas matcher.

**Comment by kemar** [comment]
Pour moi c'est un problème, il devrait y avoir un `slug` ou quelque chose comme un identifiant unique pour le champ en background plutôt que de comparer texto le libellé du champ.

Ce problème d'apostrophe, beaucoup de monde peut le rencontrer suite à un copier coller depuis Word par exemple.

Et ça va être la même chose avec des caractères unicode qui se ressemblent etc.

**Comment by gregoirenovel** [comment]
Ça commence à ressembler à #1288 tout ça

**Comment by kemar** [comment]
@gregoirenovel exact ça rejoint ça https://github.com/betagouv/tps/issues/1288#issuecomment-371426994

IMO votre système de balises actuel pose des problèmes.

Je ferme dans la foulée en duplicate de #1288

**Comment by fredZen** [comment]
@kemar ton opinion est partagée dans l’équipe. Autre cas qui est mal géré : quand deux champs ont le même libellé

**Comment by kemar** [comment]
@fredZen yes, je vous signale juste ce problème parce que je l'ai subi, et si j'en crois les commentaires du #1288 votre support aussi l'a déjà subi.

Mon avis et que ce problème se représentera dans le futur avec des retours chariots, des accents ou n'importe quel caractère [*unicode confusable*](http://unicode.org/cldr/utility/confusables.jsp) (voir la liste [ici](http://www.unicode.org/Public/security/latest/confusables.txt)). Un utilisateur non technique ne comprendra pas ce qui se passe et le temps sera perdu par votre support.

Techniquement vous pouvez utiliser un slug ou un ID unique, et continuer à faire un fallback sur le texte pour assurer la rétro-compatibilité.

Mais vous faite comme vous voulez après :)

**Comment by fredZen** [comment]
J’ai l’impression qu’on est d’accord :-)
