### ISSUE TITLE
La description d'un procédure déborde de sa colonne

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1692]
Cf. https://www.demarches-simplifiees.fr/commencer/projetsenvironnement

<img width="807" alt="screen shot 2018-03-21 at 11 31 20" src="https://user-images.githubusercontent.com/1333173/37705164-66a792f2-2cfb-11e8-939d-f53c50d8289a.png">

Peut être reglé par #1691 ?

À communiquer : CGDD

**Comment by fredZen** [comment]
Causé par la présence d‘espaces insécables dans la description => c’est à l’administrateur de nettoyer sa description
