### ISSUE TITLE
Afficher un contact technique sur toutes les pages de l'interface Usager

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1698]
Footer, bouton ?

Particulièrement problématique quand on rempli un brouillon, on n'a pas de messagerie, aucun moyen de contacter qui que ce soit

_Lié à #1699 (Rajouter un moyen dans la nouvelle UI usager de contacter l'administration émettrice de la démarche)_

**Comment by gregoirenovel** [comment]
On a des problèmes techniques : attestations mal générées, upload de PJ qui ne marche pas, etc.

J'aime bien le comportement suivant, sur toutes les pages où un usager est connecté :
- lien "Contacter l'administration" : lien vers l'email du Service, ou vers la messagerie quand on est sur la page d'un dossier qui n'est pas en brouillon
- Contact technique : lien vers notre email

**Comment by kemenaran** [comment]
Maintenant on a en bas des formulaires : 

- un pavé de texte avec le contact de l'administration
- un lien "Contact technique" avec l'email de DS

Est-ce qu'on considère que c'est bon pour considérer cette issue comme résolu ? (quitte à ouvrir des issues plus spécifiques plus tard).

**Comment by kemenaran** [comment]
J'ai l'impression que maintenant le footer est présent partout – et que sinon il faut ouvrir des issues au cas par cas.

On ferme ?

**Comment by gregoirenovel** [comment]
Il n'est pas dans la page "Merci", je propose de laisser donc cette issue ouverte tant que c'est pas regle pour cette page.
