### ISSUE TITLE
Changer la taille autorisée pour la somme des pièces jointes (>50Mo)

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#173]
- [ ] Passer sur Rails 5.1.4
- [ ] Passer sur Rails 5.2.0.beta2
- [ ] Corriger https://github.com/jeffreyguenther/activestorage-openstack/issues/2 si besoin
- [ ] Créer un champ pièce jointe #84 qui utilise activestorage
- [ ] Faire une issue pour la migration des anciennes PJs

**Comment by gregoirenovel** [comment]
Engagement : CGDD

**Comment by mmagn** [comment]
Dépend de la #84

**Comment by mmagn** [comment]
Fait avec #84
