### ISSUE TITLE
Avis dans les deux onglets bien qu'il ait été rendu

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1738]
Cf. dossier 41497. On a demandé son avis dessus à @HelaG, qui l'a rendu. Mais le dossier apparait désormais à la fois dans "Avis donnés" et "Avis à donner"

**Comment by mmagn** [comment]
Pas constaté aujourd'hui, les 3 avis étaient avec réponses.
Vu le code il parait étrange qu'un avis se retrouve dans les deux listes en même temps :
```ruby
scope :with_answer, -> { where.not(answer: nil) }
scope :without_answer, -> { where(answer: nil) }
```

Il n'y avait pas plusieurs avis ?

**Comment by gregoirenovel** [comment]
Si c'est probablement ça, je viens de regarder avec elle. Je propose :
1. de fermer cette issue
2. soit de faire une issue pour interdire la demande de plusieurs avis à une meme personne, soit d'en faire une qui affiche en warning en cas de 2de demande à une meme personne. J'ai du mal à trouver un bon use case pour une demande de plusieurs avis (hors utilisation comme messagerie interne)

**Comment by mmagn** [comment]
2, je pense que c'est compliqué d'interdire, ça va rendre la feature vraiment frustante, l'accompagnateur invitant n'aura plus le droit à l'erreur. Peut-être qu'on peut déjà permettre de supprimer/editer un avis pas encore renseigné (issue 1). Et dans un second temps quand on aura du temps améliorer l'ui côté avis accompagnateur qui doit répondre (issue 2).

**Comment by gregoirenovel** [comment]
> Peut-être qu'on peut déjà permettre de supprimer/editer un avis pas encore renseigné (issue 1)

Je trouve ça pas mal mais pas prioritaire (car faut gérer correctement le lien du mail pas encore cliqué, etc.).

OK pour les 2 issues, donc

**Comment by mmagn** [comment]
👍  on est déjà bien occupés

**Comment by gregoirenovel** [comment]
Cf. #1786 et #1787
