### ISSUE TITLE
donner accès directement aux CGU dans démarches simplifiées

### ISSUE THREAD

**Issue by emsnytech** [betagouv/tps#1739]
AUjourd'hui, les CGU sont accessible sur gitbook... pas très facile pour ceux qui ne peuvent y accéder, et l'usager ne comprend pas pourquoi il quitte le site du service.
Apparait en plus un sujet sur le certificat utilisé...

**Comment by gregoirenovel** [comment]
> pas très facile pour ceux qui ne peuvent y accéder
Quid

> l'usager ne comprend pas pourquoi il quitte le site du service
t'as eu combien de retours à ce sujet ?

> Apparait en plus un sujet sur le certificat utilisé
- Pour le moment [il est OK mais pas parfait](https://www.ssllabs.com/ssltest/analyze.html?d=demarches-simplifiees.gitbook.io)
- [J'ai demandé à leur équipe de s'améliorer](https://gitbook.canny.io/feature-requests/p/have-a-better-ssl-certificate)

La raison pour laquelle les CGU sont externalisées est pour pouvoir les éditer facilement.

**Comment by gregoirenovel** [comment]
@emsnytech up

**Comment by gregoirenovel** [comment]
@emsnytech le certificat est désormais [solide](https://www.ssllabs.com/ssltest/analyze.html?d=demarches%2dsimplifiees.gitbook.io&latest), je ferme cette issue.
