### ISSUE TITLE
Rajouter des notifications dans la partie usager

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1757]

**Comment by kemenaran** [comment]
On devrait pouvoir calculer quels dossiers ont eu une activité depuis la dernière interaction utilisateur – mais plutôt que de faire des calculs de date compliqués et fragiles, il vaudrait sans doute mieux créer un modèle `Notification`, qu'on pourrait manipuler plus explicitement.

**Comment by gregoirenovel** [comment]
Cette issue est trop large, je la coupe en 3 : #2205, #2206, #2207
