### ISSUE TITLE
Convertir les liens des descriptions en liens lorsqu'on les affiche à l'usager

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1801]
Préambule : j'espère qu'on ne va pas finir par recoder un moteur de Markdown-like ou se retaper à la main l'éditeur WYSIWYG qu'on avait avant

Aujourd'hui on a 10 % des procédures dont la description contient un lien vers une adresse web ou une adresse email. Ces liens sont aujourd'hui affichés en texte brut, on ne peut pas cliquer dessus (`simple_format` ne le fait pas pour nous).

Lorsqu'on affiche la description à l'usager, convertir ces liens en liens HTML.
---
À faire aussi dans l'ancienne UI coté identification

**Comment by mmagn** [comment]
On peut surement reprendre le code de `ChampDecorator.description_with_links` dans un helper ?

**Comment by gregoirenovel** [comment]
`#2957` (concerne l'identification SIREN)

**Comment by gregoirenovel** [comment]
`#2957`

**Comment by gregoirenovel** [comment]
Engagement : `#2957` pour le 10 juin

**Comment by fredZen** [comment]
@gregoirenovel est-ce qu’il reste quelque chose à communiquer ? Je veux bien envoyer un mail à Mme Zucker si tu penses que c’est utile, mais comme le problème est corrigé depuis longtemps, et que l’échéance du 10 juin est elle aussi passée depuis longtemps, je ne suis pas convaincu de l’intérêt.
