### ISSUE TITLE
ETQ Usager je veux consulter un dossier dans la nouvelle interface

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#1818]
Implémenter les différents panneaux de la page d'un dossier : Identité, formulaire, messagerie, décision.

https://app.zeplin.io/project/58d91c6f824616263cb8b508/dashboard?tag=Usager

## Étapes

- [x] Implémenter le nouveau système d'invitation (#1737)
- [x] Faire des wireframes
- [x] Ajouter un feature-flag propre
- [x] Implémenter l'onglet "Résumé"
- [x] Implémenter l'onglet "Formulaire"
- [x] Implémenter l'onglet "Messagerie"
- [x] Implémenter les cas de succès et d'échec (#2593)
- [x] Implémenter l'accès pour les invités
- [x] Implémenter la carto
- [x] Implémenter l'identification SIRET
- [x] Activer la fonctionnalité pour tous
- [ ] Supprimer l'ancien code

**Comment by kemenaran** [comment]
Après discussion aujourd'hui, résumé de la situation.

## Objectifs

L'utilisateur doit pouvoir :

- Voir l'avancement du dossier
- Inviter quelqu'un d'autre à co-construire le dossier
- Voir les messages reçus
- Poser une question ou répondre à un message
- Télécharger une attestation

## Conception

On part sur **trois onglets** : Résumé, Formulaire et Messagerie.

### Résumé

Pour les dossiers en cours :

- État du dossier (avec un chemin de fer indiquant la progression de la démarche)
- Dernier message reçu
- Boutons "Modifier le formulaire" et "Voir les messages"

Pour les dossiers acceptés ou refusés :

- État du dossier
- Motivation
- Attestation le cas échéant

### Formulaire

- Champs de l'identité (prénom, nom)
- Champs du formulaire

### Messagerie

- Liste des messages
- Composer un nouveau message

**Comment by kemenaran** [comment]
## Mockups

### Onglet "Formulaire" – En construction

<img width="1049" alt="capture d ecran 2018-07-10 a 17 00 39" src="https://user-images.githubusercontent.com/179923/42518876-1de24020-8463-11e8-8b4d-e911a90e7dc7.png">

https://wireframe.cc/tXCL6M

### Onglet "Résumé" – En construction

<img width="1051" alt="capture d ecran 2018-07-10 a 17 01 47" src="https://user-images.githubusercontent.com/179923/42518902-2bfb62a4-8463-11e8-97a1-002f3358ec3b.png">

https://wireframe.cc/FTswew

### Onglet "Résumé" – Accepté

<img width="1050" alt="capture d ecran 2018-07-10 a 17 02 11" src="https://user-images.githubusercontent.com/179923/42518927-34c4c9fc-8463-11e8-86e6-73d7aee44134.png">

https://wireframe.cc/eDgrCD

### Onglet "Résumé" – Rejeté

<img width="1051" alt="capture d ecran 2018-07-10 a 17 02 24" src="https://user-images.githubusercontent.com/179923/42518986-4ebeb78c-8463-11e8-84cb-1c32579fabf1.png">

https://wireframe.cc/bUklHI

**Comment by kemenaran** [comment]
Mise à jour des mockups après discussion avec @gregoirenovel :

### Onglet "Formulaire" – En construction

<img width="1055" alt="capture d ecran 2018-07-11 a 18 02 23" src="https://user-images.githubusercontent.com/179923/42584956-abcd6ac8-8534-11e8-8ef4-88e5e4ba9891.png">

https://wireframe.cc/tXCL6M

### Onglet "Résumé" – En construction

<img width="1048" alt="capture d ecran 2018-07-11 a 18 01 50" src="https://user-images.githubusercontent.com/179923/42584975-b53707f4-8534-11e8-9469-b76be92741d2.png">

https://wireframe.cc/FTswew

### Onglet "Résumé" – Accepté

<img width="1046" alt="capture d ecran 2018-07-11 a 18 01 11" src="https://user-images.githubusercontent.com/179923/42584985-bcb86432-8534-11e8-8ba2-fc7795345255.png">

https://wireframe.cc/eDgrCD

### Onglet "Résumé" – Rejeté

<img width="1050" alt="capture d ecran 2018-07-11 a 18 01 19" src="https://user-images.githubusercontent.com/179923/42584995-c143a6ec-8534-11e8-93e9-3571f7d987be.png">

https://wireframe.cc/bUklHI

**Comment by kemenaran** [comment]
Pour la compatibilité RGAA, je propose d'en faire un chantier général plus tard. Dans l'immédiat j'aimerais bien boucler le tunnel "dégager l'ancienne UI Usager", qui nous permettra d'avancer plus vite ensuite.

**Comment by gregoirenovel** [comment]
On peut pas en faire un "chantier général plus tard" car on s'est engagé à livrer la compat RGAA dans la partie usager avec la nouvelle partie usager (dans la foulée en tout cas)

**Comment by kemenaran** [comment]
Vu sur Slack : on essaie de boucler la refonte de l'UI Usager (pour pouvoir virer le code), et d'enchaîner avec une passe sur le RGAA juste derrière.
