### ISSUE TITLE
Remplacement dans le fil de discussion les adresses emails par des placeholders ("Votre accompagnateur")

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#185]

**Comment by fredZen** [comment]
A Ministère de l'Environnement

**Comment by gregoirenovel** [comment]
À communiquer : H.L du Bureau Education Routière du Rhone

**Comment by kemenaran** [comment]
Proposition de correctif par Tchak dans #2307

**Comment by kemenaran** [comment]
Maintenant :

- on masque une partie de l'email,
- on n'affiche plus les accompagnateurs affectés à l'Usager,

ce qui devrait répondre au besoin.

On ferme ?

**Comment by LeSim** [comment]
ok pour moi.

**Comment by fredZen** [comment]
Communiqué au BER du Rhône dans `HS #5019`. Je n’arrive pas à trouver à qui pensait Benjamin quand il parlait de _ministère de l’environnement_. Comme ça remonte à plus d’un an, je propose de supprimer le libellé `à communiquer`.
