### ISSUE TITLE
ETQ Utilisateur de l'API, j'aimerai que les ids des types de champs soient stables par clonage

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#1860]
c.a.d. si je clone une procédure, je veux que le type de champ qui possède le libellé 'votre nom' garde son id.

**Comment by tchak** [comment]
Évoqué par plain de monde aujourd'hui lors du brainstorming de l'api.

**Comment by tchak** [comment]
Ça serait bien de communiquer le fait que c'est résolu à toutes les personnes présentes vendredi à l'atelier API cc @emsnytech @chaibax
