### ISSUE TITLE
Dans la messagerie, ne pas afficher le texte "Merci de ne pas répondre à cet email. Postez directement vos questions dans votre dossier sur la plateforme"

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/tps#1863]
En effet, on se trouve sur la plateforme, on a ce message "Merci de ne pas répondre à cet email..." et parfois en dessous " Répondre ici"... C'est vrai que le texte "Merci de ne pas répondre à cet email..." fait partie du mail envoyé, mais une fois sur la plateforme, il est inutile et même perturbant.
@A.B (Inforoutes)

**Comment by kemenaran** [comment]
@LeSim il me semble qu'on a corrigé ça en passant aux templates d'emails il y a un mois, non ?

Mais il en reste peut-être encore…

**Comment by LeSim** [comment]
@kemenaran , copie d'écran d'un usager :

![capture-site-de-marches-simplifie](https://user-images.githubusercontent.com/907405/48068483-39de0200-e1d3-11e8-84dd-9d813f1253cd.png)

**Comment by kemenaran** [comment]
Ok, j'ai compris. On n'a plus de trace de ça dans le code, maintenant que ce texte est dans le layout (plutôt que dans l'email lui-même).

MAIS les anciens templates d'emails en prod contiennent encore ces textes.

```
> Mails::ReceivedMail.all.where("body LIKE '%Merci de ne pas répondre%'").count
=> 2992
```

Et même :

```
> Mails::ReceivedMail.all.where("body LIKE '%Téléprocédures Simplifiées%'").count
=> 181
```

En pratique, ça veut dire qu'on envoie des emails comme ça :

<img width="582" alt="capture d ecran 2018-11-06 a 15 06 51" src="https://user-images.githubusercontent.com/179923/48069374-a0641f80-e1d5-11e8-964a-87c8f64d9aa3.png">

La première ligne "Merci de ne pas répondre" vient du template, la deuxième du layout.

<hr>

J'imagine qu'il faudrait qu'on fasse une moulinette un peu précautionneuse pour enlever ce footer par défaut des templates.
