### ISSUE TITLE
Permettre l'attributation de features gérées via FlipFlop dans Manager

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1872]

**Comment by mmagn** [comment]
Done

**Comment by gregoirenovel** [comment]
Je me permets de réouvrir : y'a pas moyen de faire de l'attribution qu'à certains admins j'ai l'impression

**Comment by fredZen** [comment]
Je pense que si : si tu vas sur la page d’un administrateur dans le manager, tu as une case à cocher pour chaque feature pour cet administrateur (je te laisse fermer si ça te convient)

**Comment by gregoirenovel** [comment]
My bad, je pensais que tout se gerait dans l'UI FlipFlop. Merci Fred !
