### ISSUE TITLE
ETQ Usager, je veux pouvoir modifier mon siret

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#1874]
`HS #2613`

**Comment by gregoirenovel** [comment]
C'est pas un dup de l'issue Champ Siret ça ?

**Comment by LeSim** [comment]
Je sais pas.

Ce truc est petit. Actuellement, je ne peux pas changer mon champ siret. le changer demande peu de dev je pense.

Par contre, bouger toute la logique pour déplacer la phase d'identification en champs est plus compliqué.

**Comment by gregoirenovel** [comment]
Ouais je vois ce que tu dis, c'est sur que si on en a besoin mainenant, on peut fixer sur le code actuel. Je souligne juste qu'on veut à terme (et plutôt court terme que long terme) faire sauter l'identification et que l'identification SIRET actuelle devienne un champ SIRET de la demande, qui sera donc nativement modifiable ; et donc poser la question "à quel point ça peut attendre ces modifications-là".

Donc laissons si tu penses que c'est pas beaucoup de boulot et que c'est pressé :)

**Comment by LeSim** [comment]
Honnêtement ... je sais pas si cette issue vaut le coup ou pas. C'est juste que @tchak m'a fait prendre conscience que migrer le système d’identification, hé bé, c'est pas gratuit :) .
