### ISSUE TITLE
Chiffres séparateurs pour les milliers

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#188]

**Comment by emsnytech** [comment]
Besoin a nouveau réaffirmé au boost camp

**Comment by kemenaran** [comment]
@gregoirenovel quel est le besoin exactement ?

**Comment by gregoirenovel** [comment]
Je sais plus trop, un peu au pif :
- gérer les espaces / séparateurs de milliers dans l'input usager
- lorsque l'on affiche des nombres, les formatter correctement (espace séparateur de milliers, `,` séparateur décimal)

**Comment by fredZen** [comment]
Désolé, mais on ne va pas garder une issue pour « je ne sais plus trop, un peu au pif ». On rouvrira des issues précises quand on aura trouvé le problème.
