### ISSUE TITLE
Ne plus créer un brouillon de manière automatique mais uniquement lorsque l'usager va sur le lien de la démarche

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/tps#1895]
Dès que l'usager clique sur le lien de la procédure alors un brouillon est automatiquement créé. Mais ce mécanisme n'est pas clair pour l'usager qui parfois clique sur le lien plusieurs fois sans comprendre que ça équivaut à créer un brouillon. Résultat il se retrouve sur son tableau de bord avec plein de dossiers brouillons dont il ne soupçonnait pas l'existence. 
Il serait peut-être plus clair d'enregistrer un brouillon que lorsque l'usager en fait la demande soit quand il clique sur le bouton "enregistrer un brouillon". 

Lié à #1866 

DITP

**Comment by gregoirenovel** [comment]
@CamilleGarrigue tu l'as déjà crée cette issue il me semble : #1866

**Comment by fredZen** [comment]
à communiquer HS `#4070`

**Comment by Benjamin-Doberset** [comment]
a communiquer HS # 4972

**Comment by clemenceleurent** [comment]
Proposition de solution par Pierre : 
"En tant qu'Usager, quand je clique sur un lien /commencer mais que j'ai déjà un brouillon pour cette procédure, un écran me propose de soit :
- Ouvrir le brouillon existant
- Créer un nouveau brouillon pour cette procédure"

**Comment by gregoirenovel** [comment]
C'est en effet ce qu'on veut faire pour la page de garde : montrer les brouillons / dossiers déjà proposés sur la procédure

**Comment by kemenaran** [comment]
Issue déplacée dans #2860

**Comment by gregoirenovel** [comment]
Pour moi c'est un sujet différent, j'aimerais réouvir

**Comment by kemenaran** [comment]
Mmm, j'entends que c'est un autre sujet. Mais j'ai l'impression que c'est un sujet qui disparaitra tout seul avec la page de garde, et que ça n'a pas grand intérêt de garder une issue spécifique ouverte (ça irait mieux comme argumentaire dans l'issue "page de garde").

Mais je te laisse rouvrir si tu le juges bon :)

**Comment by gregoirenovel** [comment]
OK donc fermons aussi #2860 et regroupons ces 2 issues, les objectifs et le plan de mise en oeuvre dans l'issue #2225

**Comment by gregoirenovel** [comment]
(et issue déplacée... les à communiquer ont pas été backportés)

**Comment by gregoirenovel** [comment]
Je rouvre car j'ai un `a-communiquer` qui n'est pertinent qu'ici (email envoyé au brouillon) 10244

**Comment by gregoirenovel** [comment]
@kemenaran j'aimerais qu'on rediscute du split des issues par Slack, là à force de tout mutualiser, on perd en détail et les `a-communiquer` ne sont plus clairs
