### ISSUE TITLE
ETQ Utilisateur, je veux que ma session web expire au bout d'une heure

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#1902]

**Comment by gregoirenovel** [comment]
Qu'est-ce qui nous force à faire ça ?

**Comment by LeSim** [comment]
le point a été remonté par un utilisateur. En regardant, on a vu que le timeout actuel est de 24h. En se regardant dans le blanc des yeux avec @fredZen @mmagn , on s'est dit qu'une heure c'était pas mal. Ca permet de verrouiller la session si la personne ne revient pas après la pause dej.

Cela te sied-il ?

**Comment by gregoirenovel** [comment]
Non, car je trouve que ça flingue l'UX. Je ne vois pas de bonne raison de de déconnecter l'usager.
