### ISSUE TITLE
ETQ Usager, je peux demander la suppression d'un dossier

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#1931]
à réfléchir si on garde un dossier avec des données vides qu'on ne lie plus à l'utilisateur pour ne pas perdre l'accompagnateur.

**Comment by emsnytech** [comment]
Comme vu hier avec le RSSI, on peut garder des informations sur le dossier, a voir quelles info (nom de la procédure, date de dépôt, date de décision, nature de la décision.
On peut proposer après supression du dossier de donner un laps de temps à l’usager pour qu’il puisse télécharger le dossier en PFD et en donnée ( accessible pendant 30 jours par exemple) Cela implose de l’autre côté au service de sauvegarder le dossier....

**Comment by LeSim** [comment]
Suite à la réunion de ce matin, bouton coté usager à partir de l'état `en construction`
