### ISSUE TITLE
Rajouter dans Manager un bouton qui permet de repasser un dossier terminé en construction

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2014]
Bien faire gaffe à l'attestation (la supprimer s'il y en a une)

**Comment by fredZen** [comment]
Toujours utile ? ( #2183 permet le repassage en instruction, ensuite l’accompagnateur peut repasser en construction s’il veut)

**Comment by kemenaran** [comment]
Je pense qu'on peut fermer. À rouvrir au besoin.
