### ISSUE TITLE
ETQ super admin je veux voir les dossiers soft-deleted

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2031]

**Comment by kemenaran** [comment]
On peut maintenant voir les dossiers soft-deleted si on les cherche par id (mais ils n'apparaissent pas dans la liste).

@fredZen tu penses qu'il nous faudrait mieux que ça ?

**Comment by fredZen** [comment]
Je pense que tu as eu raison de fermer. C’était sorti d’une discussion à l’époque, ça paraissait une bonne idée, mais franchement on s’en passe très bien pour l’instant. On pourra toujours re-créer l’issue quand on n’aura rien de plus prioritaire à faire ;-)
