### ISSUE TITLE
ETQ super admin je veux rétablir un dossier soft-deleted

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2032]

**Comment by fredZen** [comment]
Voir aussi #2031

**Comment by kemenaran** [comment]
Est-ce que c'est une demande qu'on a beaucoup ? Pour l'instant il faut toujours faire ça en console – mais j'ai l'impression que ce n'est pas un truc qu'on fait fréquemment, et sans doute pas très prioritaire.

**Comment by fredZen** [comment]
Non, ça paraissait une bonne idée quand on a mis en place le soft delete, mais franchement on s’en passe très bien pour l’instant. On pourra toujours re-créer (ou rouvrir) l’issue si on décide de s’y attaquer un jour.
