### ISSUE TITLE
Changer la configuration du tracking pixel de Mailjet pour qu'il utilise un domain en demarches-simplifiees.fr

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#2056]
Je viens de recevoir un mail pour retrouver mon brouillon sur DS.
Le mail est catégorisé comme spam par fastmail.

Si je regarde le code source de l'email, je vois un tracking pixel de mailjet en `emails.tps.apientreprise.fr` .

Je suppose que cette adresse, différente de celle de l'expéditeur (contact@demarches-simplifiees.fr) contribue à la classification en spam du mail.

**Comment by LeSim** [comment]
En regardant les headers avec @fredZen on a découvert ceci :

```
X-Spam-known-sender: no
X-Spam-score: 5.0
X-Spam-hits: BAYES_20 -0.001, HEADER_FROM_DIFFERENT_DOMAINS 0.25,
  HTML_IMAGE_ONLY_12 2.059, HTML_MESSAGE 0.001, HTTPS_HTTP_MISMATCH 1.989,
  MIME_HTML_ONLY 0.723, RCVD_IN_DNSWL_NONE -0.0001, SPF_HELO_PASS -0.001,
  SPF_PASS -0.001, LANGUAGES fr, BAYES_USED global, SA_VERSION 3.4.0
```

et si on regarde de plus pres les liens on voit

```
<a target="_blank" href="http://emails.tps.apientreprise.fr/lnk/AMoAAAs=...">https://www.demarches-simplifiees.fr/users/dossiers?liste=brouillon</a>
```

On voit que le lien annoncé est en https alors que le href est en http et pas sur le mm domaine. Ticket mailjet ouvert.

**Comment by LeSim** [comment]
je suis d'accord pour la fermer. On rouvrira au besoin.

**Comment by chaibax** [comment]
On peut, sur Mailjet, tracker les ouvertures d'email et pas les clicks sur les liens. Après plusieurs tests de délivrabilité, ça n'impacte en rien notre score. 

Je propose donc de reactiver le tracking d'ouverture uniquement.

**Comment by fredZen** [comment]
@chaibax ça me va de réactiver le tracking d’ouverture.
