### ISSUE TITLE
ETQ Administrateur, La saisie d'une durée de conservation supérieure à 36 mois provoque une erreur

### ISSUE THREAD

**Issue by guillaume-cellier** [betagouv/tps#2089]
L'erreur n'est pas correctement "capturée", voici l'affichage actuel : 

> Durée de conservation des dossiers sur demarches-simplifiees.fr translation missing: fr.activerecord.errors.models.procedure.attributes.duree_conservation_dossiers_dans_ds.less_than_or_equal_to 

Un message pourrait indiquer que la durée de conservation maximale d'un dossier est de 36 mois.

**Comment by fredZen** [comment]
Merci ! J’ai manifestement loupé des traductions

**Comment by guillaume-cellier** [comment]
Merci c'est en ligne !

Juste un coquille sur l'orthographe :
_"Durée de conservation des dossiers sur demarches-simplifiees.fr doit être inférieur ou égal à 36"_

Durée de conservation des dossiers sur demarches-simplifiees.fr doit être inférieure ou égale à 36

**Comment by gregoirenovel** [comment]
@guillaume-cellier Merci pour cette remarque, nous allons suivre ce problème dans l'issue #2201
