### ISSUE TITLE
ETQ accompagnateur, je veux savoir qui m'a nommé pour instruire telle procédure

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/tps#2100]
Un accompagnateur avait été nommé sur des procédures qui ne le concernaient pas. 
Est-il possible de dire aux accompagnateurs qui les a nommé, pour qu'il puissent échanger en cas de problème ? par exemple dans le mail de notification

**Comment by emsnytech** [comment]
Bonne idée !

**Comment by gregoirenovel** [comment]
Dup #1696
