### ISSUE TITLE
Mail pour nouveau mot de passe

### ISSUE THREAD

**Issue by AnthonyBrunelli** [betagouv/tps#2105]
Le mail envoyé lorsque l'on effectue la procédure "mot de passe oublié" est en anglais. Il faudrait qu'il soit en français...

![image](https://user-images.githubusercontent.com/35567048/41420095-fda40be6-6ff3-11e8-86ea-9635ccb72409.png)

**Comment by mmagn** [comment]
Hello merci pour le retour, l'issue était déjà référencée ici #2068 et la correction est sur le point d'être livrée. ;)

**Comment by fredZen** [comment]
Sur le point d’être livré c’est vite dit, ça fait une semaine que j’ai le correctif pour le problème proprement dit et que des membres de l’équipe trouvent des points additionnels à traiter impérativement avant qu’on puisse oser passer les mails en français #bikeshedding.
