### ISSUE TITLE
Coquille

### ISSUE THREAD

**Issue by teolemon** [betagouv/tps#2113]
Direction générale de l'aviation civile
​Traitement informartisé des demandes d'agrément d’assistance en escale​

https://doc.demarches-simplifiees.fr/listes-des-demarches

**Comment by fredZen** [comment]
Merci de nous avoir signalé la coquille. Pour être sûr de ne rien rater : je vois un r en trop dans informa*r*tisé → informatisé, est-ce qu’il y a autre chose ?

**Comment by teolemon** [comment]
Sur cette ligne c'est tout. Après, j'ai pas tout lu :)

**Comment by fredZen** [comment]
Merci pour le retour, j’ai corrigé la coquille :-)
