### ISSUE TITLE
Distinguer le footer de DS du footer de la procédure

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2125]
Augmenter la distinction visuelle

Éventuellement transformer le footer de la procédure en un encart affiché au début du dossier

**Comment by emsnytech** [comment]
En effet, il faut expliciter les deux nature de footer.
Celui qui concerne le service traitant, celui du service opérant le téléservice ( nous). Par ailleurs, quand on va sur contact du footer, on a directement un mail... il faudrait expliciter que les mail par le biais de cette boite technique ne concerne que les pb technique liés à l’utilisation de la plateforme et que pour toutes saisine du service, on envoi sur le lien du contact du service....

**Comment by kemenaran** [comment]
On a maintenant un menu d'aide avec le contact administratif.

Le contact mail est clairement indiqué comme un contact uniquement technique.
