### ISSUE TITLE
Pas de `bin/rake` en prod

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2128]
README.md dit de lancer les tâches administratives via `bin/rake` plutôt que `bundle exec rake`. Or, si cet exécutable existe bien sur un environnement local, ce n’est pas le cas en prod. Mettre à jour la config ansible ?

**Comment by kemenaran** [comment]
J'ai investigué. Ce qui se passe, c'est qu'au deploy le dossier `bin` est défini comme "partagé" : ça veut dire qu'au lieu d'être dans "/var/www/tps/current`, il est symlinké depuis `/var/www/tps/shared`.

Donc au moment où on lance `bin/rake` depuis `/var/www/tps/current`, il essaie de lire un Gemfile dans `/var/www/tps/shared` – et il ne le trouve pas, évidemment, puisqu'il est dans `current`.

Je ne sais pas trop quelle est la bonne solution :

- Ne pas partager le dossier `./bin` ? (J'avoue avoir des doutes sur l'utilité de ce partage)
- Ré-écrire `bin/spring` pour qu'il prenne en compte le bon Gemfile, même dans des dossiers chelous ?
- Passer `BUNDLE_GEMFILE=/var/www/tps/current` en variable d'env aux commandes ?

J'imagine que la première solution serait la meilleure, mais je ne maitrise pas toutes les implications.

**Comment by mmagn** [comment]
Oui après recherche je viens de voir que les binstub sont versionnés dans le repo ansible.
Je n'ai aucune idée pourquoi c'est fait comme cela.
On devrait s'en débarrasser au changement d'infra.

**Comment by fredZen** [comment]
N’a plus lieu d’être avec la nouvelle infra, merci @LeSim :heart:
