### ISSUE TITLE
ETQ usager, je veux enregistrer un brouillon incomplet comportant des pièces jointes

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2165]
# Reproduction

- Créer un dossier sur une procédure comportant des champs obligatoires et des champs pièces justificatives
- Laisser au moins un champ obligatoire vierge
- Ajouter au moins une pièce jointe
- Enregistrer le brouillon

# Comportement attendu

- Les champs que j’ai remplis et mes pièces jointes sont enregistrés dans mon brouillon

# Comportement observé

- Une erreur de validation s’affiche car des champs obligatoires ne sont pas remplis
- Aucune donnée n’est mise à jour dans le brouillon

**Comment by gregoirenovel** [comment]
Fixed by #2182

**Comment by gregoirenovel** [comment]
@fredZen personne à qui communiquer la résolution ? (il me semblait que ça venait de HelpScout, mais je peux me tromper)

**Comment by fredZen** [comment]
@gregoirenovel c'est bon, c'est communiqué
