### ISSUE TITLE
ETQ Instructeur, je peux régler la fréquence des mails de récap

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2172]
Cas d’usage à repréciser avec le Sicoval ?

Voir aussi #345 et #1977

**Comment by fredZen** [comment]
Cas d’usage (à creuser je trouve) : « accompagnateurs qui ne traitent pas beaucoup de dossiers, et qui ne se connectent pas tous les jours »

**Comment by fredZen** [comment]
Après discussion avec @gregoirenovel : ce cas est probablement un doublon soit de #1449 soit de #1977 . À reporter dans la bonne issue une fois que c‘est tiré au clair.

**Comment by Benjamin-Doberset** [comment]
Cadrage : la personnalisation serait choisie par l'instructeur pour chacune de ses procédures. Par défaut, fréquence hebdomadaire. 

Au départ deux choix : je reçois un mail à chaque dossier déposé / je reçois un mail toutes les semaines. 

On pourrait aussi réflechir à donner la possibilité de personnalisé les notifications : je reçois un mail par jour récapitulant tous les dossiers déposés / je reçois un mail hebdomadaire avec tous les dossiers déposés (le même qu'avec les nouveaux dossiers).

**Comment by LeSim** [comment]
`hs #11057`

**Comment by chaibax** [comment]
hs # 1309

**Comment by fredZen** [comment]
Voir aussi #1977 (quasi-doublon)

**Comment by mmagn** [comment]
Nous avons commencé un fix pour cette issue qui permet à l'instructeur de choisir s'il souhaite recevoir un email à chaque dossier déposé.

Selon moi cela pose les problèmes suivants :

- une fois le dossier déposé, il n'y aura plus aucune notification alors que le dossier peut continuer à évoluer (messages, modifications, etc.). On risque de nous demander rapidement de développer la suite de la fonctionnalité : la notification lors de la modification de dossier, on devra alors faire attention de ne pas envoyer d'email à chaque fois que l'usager clique sur "enregistrer" ou ajoute un message.

- pas de protection contre une activation dans un contexte pas pertinent (exemple : l'instruction a plusieurs dizaines / centaines de dossiers par jour), on risque de baisser la réputation de nos ips de serveurs de mails.

- ça rajoute une feature, une nouvelle notion a expliquer / documenter, alors qu'on a déjà des emails qui partent toutes les semaines et dont le but était à la base d'avertir les instructeurs qui n'allaient pas souvent sur DS qu'ils avaient des dossiers.

**Comment by mmagn** [comment]
Après avoir lu les conversations HS réparties sur les tickets  qui traitent du sujet (#345, #1977, #1449, #1977 et celui ci), les utilisateurs s'expriment de plusieurs façon :
- je veux changer la fréquence des mails
- je veux savoir quand un nouveau dossier arrive

mais aussi
- je veux savoir quand un nouveau dossier arrive **donc** envoyez moi le mail récap tous les jours

Avec @CamilleGarrigue et @Benjamin-Doberset on fait donc l'hypothèse que la majeure partie des problèmes seront résolus si on permet le changement de la fréquence des emails récapitulatifs (hebdo ou journalier).

**Comment by LeSim** [comment]
@mmagn , ok.

Est ce que vous avez prévu le cas suivant :
- une démarches avec peu de dossier (1 par mois)
- un instructeur qui du coup ne se connecte plus a ds régulièrement mais qui veut être averti quand un nouveau dossier arrive
- une fréquence journalière des mails récapitulatif ... mais comme il ne se passe rien la plupart du temps, l'instructeur ne la lit plus non plus.

**Comment by fredZen** [comment]
@LeSim est-ce que tu es en train de distinguer deux usages du mail de récap ?

1. Rappeler de temps en temps à l’instructeurice qu’ille a des dossiers qui dorment
2. Prévenir l’instructeurice qu’il y a du nouveau sur ses dossiers

Et de suggérer que ça aurait du sens qu’une instructeurice puisse avoir deux fréquences de récap sur la même démarche, correspondant aux deux usages ?

**Comment by chaibax** [comment]
Le problème initiale qu'on ma remonté très souvent est pour moi : 

- en tant qu'instructeur, je ne souhaite pas me connecter tout les jours sur le backoffice pour vérifier s'il y a un nouveau dossier

- en tant qu'admin je souhaite que mes instructeurs soient réactif quand un nouveau dossier arrive (pas au bout d'une semaine), mais je ne pas qu'il se connecte pour rien sur le backoffice DS.

**Comment by mmagn** [comment]
@LeSim tu penses que les mails récapitulatifs ne devraient pas être envoyés s'il n'y a aucune activité ?

**Comment by LeSim** [comment]
@mmagn oui, je me demande si on peut arriver à un mix malin genre :
- [ ] envoyer le mail récapitulatif toute les semaines
  - [ ] envoyer le mail récapitulatif dès qu'il y a des nouveautés sur mes procédures
- [ ] envoyer le mail tous les jours

**Comment by LeSim** [comment]
Finalement, après discussion, on a décidé de garder 2 mails distincts :
- le résumé de la semaine
- un mail, envoyé au maximum une fois par jour, qui indique aux instructeurs de l'arrivée de nouveaux dossiers ou des notifications sur les dossiers en cours

**Comment by chaibax** [comment]
@LeSim : ce mail peut-il être envoyé à midi ? 

Ca permettrait une meilleurs réactivité des instructeurs

**Comment by mmagn** [comment]
@chaibax on était parti sur 14h, mais on peut changer à midi si vous pensez que c'est mieux

**Comment by chaibax** [comment]
@mmagn : 14h, c'est peut le faire  aussi. Idéalement, ca serait l'heure "médiane" a laquelle les demandes sont déposés sur DS (tout compte confondu). Si la majorité est déposé entre 9h et 15h, ca sera midi par exemple. Si c'est entre 10h et 18h, 14h ca serait mieux etc. (et, helas, t tant pis pour l'outre mer )
