### ISSUE TITLE
Séparer visuellement les paragraphes dans la description d’une procédure

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2174]
Exemple démontrant le problème :

![capture du 2018-06-29 11-54-50](https://user-images.githubusercontent.com/356570/42086407-43137aa4-7b93-11e8-8d17-d25329ebf243.png)

Le texte correspondant pour la description de la procédure est 

```
Ceci est un premier paragraphe. Il est suffisamment long pour qu’il occupe plus d’une seule ligne.

Ceci est un second paragraphe. La distinction visuelle par rapport au paragraphe précédent ne se fait que par le retour à la ligne.
Ceci n’est pas un nouveau paragraphe mais seulement une nouvelle ligne.
```

**Comment by kemenaran** [comment]
Oui, le reset-css est un peu trop costaud, et supprime les marges par défaut entre les paragraphes. Faudrait en rajouter.
