### ISSUE TITLE
ETQ accompagnateur, je veux pouvoir faire des recherches

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2179]
Actuellement, la recherche accompagnateur part en timeout.

HS #`4293`

**Comment by fredZen** [comment]
J’avoue que je n’arrive pas à imaginer de scénario où la vue `searches` pourrait avoir des performances décentes. On essaie de la maintenir à bout de bras ou bien on passe à Elastic Search ?

**Comment by fredZen** [comment]
à titre indicatif, sur ma machine de dev, l’exécution de la commande suivante en console rails sur un dump de prod a mis près de 8 minutes :

`Search.new(gestionnaire: mon_compte_gestionnaire, query: 'frederic').results`

**Comment by fredZen** [comment]
Et le temps d’exécution est passé (quasi) exclusivement dans la requête SQL `SELECT  DISTINCT(searches.dossier_id), COALESCE(ts_rank(to_tsvector('french', searches.term::text), to_tsquery('french', 'frederic:*')), 0) AS rank FROM "searches" INNER JOIN "dossiers" ON "dossiers"."id" = "searches"."dossier_id" AND "dossiers"."hidden_at" IS NULL WHERE "searches"."dossier_id" IN (SELECT "dossiers"."id" FROM "dossiers" INNER JOIN "procedures" ON "dossiers"."procedure_id" = "procedures"."id" INNER JOIN "assign_tos" ON "procedures"."id" = "assign_tos"."procedure_id" WHERE "dossiers"."hidden_at" IS NULL AND "procedures"."hidden_at" IS NULL AND "assign_tos"."gestionnaire_id" = 2489 AND "dossiers"."state" != 'brouillon' AND "dossiers"."archived" = false AND "dossiers"."state" != 'brouillon') AND (to_tsvector('french', searches.term::text) @@ to_tsquery('french', 'frederic:*')) ORDER BY rank DESC LIMIT 11;`

**Comment by fredZen** [comment]
Une piste de solution serait de poser des index GIN ou GIST. Mais pour pouvoir faire ça il faudrait soit matérialiser la vue (avec les retards de mise à jour que cela entraîne) pour pouvoir poser un index dessus, soit  poser des index sur les tables sous-jacentes, mais dans ce cas il faut se débarrasser de la concaténation pour que la vue ait une chance de bénéficier des index. On pourrait tenter de construire la vue par UNION ALL (donc présenter la data pour chaque dossier sur plusieurs lignes plutôt que de grouper les data de chaque dossier sur une seule ligne)

**Comment by gregoirenovel** [comment]
> J’avoue que je n’arrive pas à imaginer de scénario où la vue searches pourrait avoir des performances décentes. On essaie de la maintenir à bout de bras ou bien on passe à Elastic Search ?

Je suis assez aligné avec cette position. Je propose de ne faire que de la recherche rudimentaire sur les numéros de dossiers (avec éventuellement en plus prénom et nom du demandeur + nom entreprise   + email demandeur ; mais pas plus), et si on veut faire quelque chose de plus complexe, de passer à une "vraie" solution de recherche.

**Comment by fredZen** [comment]
Dans mes idées d’amélioration, je me suis concentré sur la vitesse de la recherche texte, mais une autre piste à étudier très sérieusement serait de voir pourquoi la requête générée par la recherche ne parvient pas à utiliser le filtrage sur l’id du gestionnaire pour réduire drastiquement le nombre de dossiers à étudier, au point où les performances de la recherche texte seraient hors sujet.

Pistes à creuser :

- il manque un index ? (par exemple sur l’id gestionnaire ou l’id dossier)
- clauses à réordonner dans la requête

**Comment by DanielBMY** [comment]
*"Je propose de ne faire que de la recherche rudimentaire sur les numéros de dossiers (avec ~~éventuellement~~ en plus prénom et nom du demandeur + nom entreprise + email demandeur ; mais pas plus), et si on veut faire quelque chose de plus complexe, de passer à une "vraie" solution de recherche."*
Pour workinfrance, les agents ont besoin d'avoir la possibilité d'effectuer des recherches par nom / prénom du salarié (ces derniers étant limités en volume horaire par leur titre de séjour, il na faudrait pas que l'administration puisse délivrer par erreur des attestations les autorisant à exploser les quotas par manque de visibilité leur "historique de demandes déposées" ) ...

**Comment by gregoirenovel** [comment]
À communiquer : `#4511`, `#4561`

**Comment by kemenaran** [comment]
À communiquer : `HS #4680`

**Comment by kemenaran** [comment]
Dans les idées d'amélioration pour essayer de faire du quickfix :

- Pour reprendre l'idée de @fredZen, voir "pourquoi la requête générée par la recherche ne parvient pas à utiliser le filtrage sur l’id du gestionnaire pour réduire drastiquement le nombre de dossiers à étudier"
- Dénormaliser les données : créer un champ "concatenated_champs", avec le contenu de la valeur de tous les champs. Ça permettrait de faire une recherche full-text sur une seule colonne, plutôt que sur plein, et p-ê d'améliorer les performances.

**Comment by fredZen** [comment]
Je suis parti sur une solution dénormalisée. Sous réserve que ça soit concluant niveau perfs, ça va nécessiter plusieurs interventions en prod : 

1. MEP une version qui alimente le champ dénormalisé
2. Faire tourner un script de reprise pour alimenter le champ dénormalisé pour l’existant
3. MEP une version qui fait les recherches via le champ dénormalisé plutôt que via la vue
4. Supprimer la vue

**Comment by fredZen** [comment]
Une fois la table dénormalisée, la requête se simplifie un peu, mais surtout son temps d’exécution passe de 8 minutes à quelques millisecondes.

```sql
SELECT dossiers.id, COALESCE(
                      ts_rank(to_tsvector('french', search_terms || private_search_terms),
                              to_tsquery('french', 'frederic:*')),
                      0) AS rank

FROM dossiers
       INNER JOIN procedures ON dossiers.procedure_id = procedures.id
       INNER JOIN assign_tos ON procedures.id = assign_tos.procedure_id
WHERE dossiers.hidden_at IS NULL
  AND procedures.hidden_at IS NULL
  AND assign_tos.gestionnaire_id = 2489
  AND dossiers.state != 'brouillon'
  AND dossiers.archived = false
  AND (to_tsvector('french', search_terms || private_search_terms) @@ to_tsquery('french', 'frederic:*'))
ORDER BY rank DESC
LIMIT 11;
```

**Comment by fredZen** [comment]
Communiqué sur `HS #4293, #4511, #4561, #5192, #4680`
