### ISSUE TITLE
ETQ Utilisateur je veux pouvoir supprimer un brouillon

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2211]
C'est une régression : depuis la mise en production de la nouvelle liste des dossiers début juillet, les usagers ne peuvent plus supprimer leur brouillon (alors qu'ils pouvaient avant).

- Rajouter un bouton dans la vue brouillon ?
- Rajouter un bouton dans la liste des dossiers ?

**Comment by gregoirenovel** [comment]
À communiquer : `#4224`

**Comment by LeSim** [comment]
A communiquer  # 4249

**Comment by mmagn** [comment]
A communiquer # 4653

**Comment by kemenaran** [comment]
Je vois deux problèmes au bouton "Supprimer" dans la liste :

- C'est seulement au hover, donc ça ne fonctionne pas sur mobile ;
- Si on a quatre brouillons sur la même procédure, rien dans la liste ne permet de savoir qu'on est bien en train de supprimer les 3 brouillons qu'on ne veut pas (et de garder celui qu'on veut).

Et un bouton "Supprimer le brouillon" en bas du formulaire, vous en pensez quoi ?

<img width="969" alt="capture d ecran 2018-07-19 a 17 51 12" src="https://user-images.githubusercontent.com/179923/42954243-87d5ed36-8b7c-11e8-9437-d9352983eb30.png">

**Comment by gregoirenovel** [comment]
Je trouve ça très bien :)

**Comment by kemenaran** [comment]
A communiquer à tempsfort@nordnet.fr
