### ISSUE TITLE
Recherche très lente

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2219]
en saisissant le mot « Cned » (ou d'autres mots) dans la zone de recherche, j'obtiens « 504 Gateway Time-out ». Je suis obligée de saisir le numéro de dossier pour obtenir le dossier.

À communiquer : `#4511`

**Comment by LeSim** [comment]
A communiquer `#4561`

**Comment by fredZen** [comment]
dup de #2179 ?

**Comment by gregoirenovel** [comment]
Yes, je backporte les "à communiquer"
