### ISSUE TITLE
Les sauts de ligne dans la description des champs ne sont pas pris en compte

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/tps#2228]
Demande d'Eric T. de Nantes (VAE)

Dans la partie champs, quand je choisis le type "explication", je ne peux pas écrire un long texte structuré avec des renvois à la ligne dans la partie "libellé", la case est toute petite. 

Pourrait-on : 
- aggrandir la taille de la case "libellé"
- permettre des renvois à la ligne

![image](https://user-images.githubusercontent.com/39761053/42455051-7b32de24-8391-11e8-88cf-aa96c4389acc.png)

**Comment by kemenaran** [comment]
Est-ce qu'un texte long avec des sauts de ligne, ce n'est pas plutôt le rôle de la Description (plutôt que du Libellé) ?

Quel est son cas d'usage ?

**Comment by clemenceleurent** [comment]
En effet, problème de com° avec l'admin, on avait mal saisi son besoin. Je ferme l'issue

**Comment by gregoirenovel** [comment]
@clemenceleurent est-ce que ce champ est incompréhensible ? Est-ce que ça serait plus simple si on ne pouvait pas avoir de "libellé" pour les "explications" ?

**Comment by clemenceleurent** [comment]
Ah oui peut-être.
Si l'administrateur a pas de titre particulier à mettre pour son explication, il peut être perdu. 

En fait c'est confusant globalement d'avoir cet outil pour faire des explications, au milieu des autres champs où l'usager rempli quelquechose.

**Comment by gregoirenovel** [comment]
OK, je te propose de faire une autre issue pour expliciter ce problème.

**Comment by clemenceleurent** [comment]
Alors après échange avec l'administrateur, on avait vraiment pas bien identifié le pb (désolée pour tous ces allers retours :/). 
Il a créé un champ "explication". Il a bien écrit son texte dans la partie "description", il a bien mis des sauts de ligne. Mais problème : dans la prévisualisation et dans le formulaire quand on le publie, les sauts de ligne disparaissent. 

Cf # 4543

**Comment by kemenaran** [comment]
Ok, je peux regarder ça

**Comment by kemenaran** [comment]
De ce que je vois les sauts de ligne sont bien pris en compte.

**Dans l'interface d'administration**

<img width="829" alt="capture d ecran 2018-07-09 a 18 10 35" src="https://user-images.githubusercontent.com/179923/42462396-744e798a-83a3-11e8-9e5b-b650a3a3ec16.png">

**Aperçu dans le formulaire.**

<img width="599" alt="capture d ecran 2018-07-09 a 18 10 21" src="https://user-images.githubusercontent.com/179923/42462403-7b0b3f6a-83a3-11e8-9d3c-d15510987191.png">

Le seul souci c'est qu'on ne sépare pas les paragraphes – mais les retours à la ligne, eux, fonctionnent correctement.
