### ISSUE TITLE
Améliorer le header pour les brouillons

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2232]
On ne sait pas que c'est un brouillon, cf.

![screenshot_2018-07-09 demarches-simplifiees fr 1](https://user-images.githubusercontent.com/179923/42455703-43c165bc-8393-11e8-9dd2-86ef5b74b3c5.png)

Propositions (mockups dégueues) :

![screenshot_2018-07-09 demarches-simplifiees fr](https://user-images.githubusercontent.com/1333173/42458984-3e33835c-839b-11e8-94fb-8737e7f2b043.png)
![screenshot_2018-07-09 demarches-simplifiees fr 1](https://user-images.githubusercontent.com/1333173/42458989-3fe5bd0a-839b-11e8-8924-3daa7847cc08.png)

**Comment by kemenaran** [comment]
Pourquoi c'est important qu'on sache que c'est un brouillon, par rapport à un autre état ?

**Comment by gregoirenovel** [comment]
Par uniformité avec ce que seront les autres états je pense

**Comment by kemenaran** [comment]
J'ai l'impression qu'on s'est dit dans https://github.com/betagouv/tps/pull/2229#issuecomment-403743863 que :

- pour l'instant on ne va pas tenter d'uniformiser les headers
- à l'étape du remplissage initial d'un brouillon le n° de dossier n'est sans doute pas important au point d'être plus mis en avant que le nom de la procédure
- la mention du brouillon peut se faire plus par le bouton que par la pastille de statut

Est-ce qu'on ferme ?

**Comment by gregoirenovel** [comment]
Yes, surtout étant donné que #1818 reprend aussi une partie des propositions formulées ici.
