### ISSUE TITLE
Bug sur les champs conditionnels

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/tps#2236]
On a peut-être un petit bug sur les champs conditionnels, ça se produit quand on veut faire deux champs conditionnels à la suite.

j'ai fait un test avec une procédure : https://www.demarches-simplifiees.fr/commencer/test-champs-conditionnels-double-j
Pour le premier champ, on ne peut rien sélectionner dans la 2e case

![image](https://user-images.githubusercontent.com/39761053/42497077-531992b0-8428-11e8-9302-80707bb035f9.png)

Le pb nous a été soulevé par Eric T. de Nantes

**Comment by gregoirenovel** [comment]
Dup de #2247
