### ISSUE TITLE
ETQ administrateur je veux pouvoir organiser les PJ demandées aux usagers en sections

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/tps#2256]
@J-N.P (Pref Rhône)
Exemple : 41 PJ dans un cerfa de demande d'urbanisme. Se serait plus lisible avec des sections.

**Comment by gregoirenovel** [comment]
Il faut lui activer le champ pièce jointes et lui dire de l'utiliser avec les champs de type "titre".
