### ISSUE TITLE
ETQ usager, quand je dois me créer un compte, je n'arrive plus à retrouver mon formulaire

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/tps#2293]
Cas apparu à 3 reprises en 24h (cf notamment : # 4956 et # 4916)

L'usager clique sur le lien indiqué par l'administration. Il doit se créer un compte, et après il atterit sur le tableau de bord usager. Et la il ne retrouve plus son formulaire initial. Donc il nous appelle

**Comment by kemenaran** [comment]
Pourtant il me semblait que quand on se créait un compte, on arrivant quand même sur le bon formulaire ? C'est cassé ? Ou ça n'a jamais fonctionné ?

**Comment by gregoirenovel** [comment]
Il est possible que le lien donné par d'administration soit le lien de sign_in et pas le lien commencer, d'où le problème. Ça sera reglé avec la nouvelle UI usager (bouton "commencer une nouvelle procédure") et avec un changement du lien de la part de l'administration.

Il faut donc vérifier le lien communiqué par l'administration et leur demander de le changer si besoin

**Comment by clemenceleurent** [comment]
Non non dans les 3 cas en questions j'avais fait la vérification en
demandant aux usagers les mails envoyés par l'administration, le pb ne
vient pas du lien

Le lun. 30 juil. 2018 09:38, gregoirenovel <notifications@github.com> a
écrit :

**Comment by LucienMLD** [comment]
Testé en locale et aucun problème relevé, on est bien redirigé vers la procédure quand on se créer un compte et que l'on clic sur le lien dans le mail. 
Les liens donnés par les administrations était correctes mais personne n'a eu le problème depuis.
A surveiller si le problème revient
