### ISSUE TITLE
ETQ usager je soumets mon dossier mais il s'enregistre en brouillon

### ISSUE THREAD

**Issue by red1bush** [betagouv/tps#2300]
Un usager veut soumettre son dossier, mais à la place son brouillon est enregistré. Pas de possibilité de soumettre le dossier.

N.B. : l'usager utilise Safari.

**Comment by kemenaran** [comment]
Safari 😂 😶 😭

**Comment by kemenaran** [comment]
Je regarde

**Comment by kemenaran** [comment]
@mmagn je viens de tester rapidement, ça a l'air de fonctionner sous Safari. Mais c'est possible qu'on ait un bug à cet endroit là.

Tu aurais son ID d'utilisateur et l'ID de la procédure ?

**Comment by kemenaran** [comment]
J'ai testé avec la procédure en question (n° 4927), et ça a l'air de fonctionner. La prochaine étape ça serait sans doute de regarder les logs dans Kibana (quand Kibana sera up) pour reconstituer son parcours, et voir si avec exactement la même séquence d'actions on peut reproduire le problème.

**Comment by fredZen** [comment]
Très certainement lié à HS `# 5053` et HS `# 5061`. Ça sent le problème turbolinks (problème intermittent qui apparaît / disparaît en changeant de browser ou en passant en navigation privée).

**Comment by kemenaran** [comment]
`#HS #5053` et `HS #5061` disent que "Je ne vois que le bouton 'Supprimer'", pas les autres. C'est donc très vraisemblablement non pas ce problème d'enregistrement du brouillon, mais plutôt #2311.

**Comment by gregoirenovel** [comment]
À communiquer : `#5257` et `#5255`

**Comment by Benjamin-Doberset** [comment]
Dossier 109595 (j'ai le numéro de tel en complément). La personne a complété son brouillon ce matin, a cliqué sur soumettre, le bouton s'est transformé en envoie mais il est resté bloqué dessus. Un nouveau brouillon s'est par la suite créé mais il est vide. Aucun dossier n'a été soumis

**Comment by Benjamin-Doberset** [comment]
à communiquer HS# 5260

**Comment by kemenaran** [comment]
À investiguer : c'est peut-être bien un problème lié à Internet Explorer :

- On teste moins IE
- Y'avait un screenshot qui montrait du IE
- Une personne a corrigé le problème en passant de IE à Firefox (`HS #5302`)

**Comment by kemenaran** [comment]
@LeSim dit :

> J'ai eu un utilisateur qui a eu le pb ce matin et qui est sur firefox ...

Donc ce n'est pas seulement IE le problème.

Il se peut que Babel ne génère pas du Javascript pour les vieux navigateurs. Pour l'instant on lui demande `"browsers": ">1%"`, mais ce n'est sans doute [pas assez](http://browserl.ist/?q=%3E1%25) : ça n'inclut pas les vieux Firefox et les vieux Safari, par exemple. Je vais faire une PR pour ça.

**Comment by kemenaran** [comment]
J'ai testé sous FF 52 / Windows 7. Même avec l'ancienne config de Babel (pas de polyfill, pas de support explicite des vieux Firefox), et en testant avec des pièces jointes, je n'ai pas réussi à reproduire le problème.

On a donc bien corrigé certains navigateurs (IE, Safari), mais pour d'autres le mystère reste entier.

**Comment by kemenaran** [comment]
Encore une piste : il se peut que les problèmes restants soient liés à Uglify (vu que j'ai fait mes tests sur un environnement de développement, où Uglify est désactivé).

Je vais refaire une passe de tests avec Uglify activé, pour voir si y'aurait d'autres paramètres à ajuster.

**Comment by kemenaran** [comment]
Résultat : même avec Uglify activé, pas réussi à reproduire d'erreur sous Firefox 52.

**Comment by fredZen** [comment]
Déjà communiqué sur `#5257` le 7 août, je viens de communiquer sur `#5255`, `#5260` était un autre problème (#2341), qui a déjà été résolu et communiqué dans `HS #5311`
