### ISSUE TITLE
ETQ accompagnateur, quand j'écris un message aux usagers, mon adresse mail apparait

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/tps#2302]
Problème soulevé par H.L du Bureau Education Routière du Rhone

Les accompagnateurs utilisent beaucoup la messagerie, mais ils se sont rendus compte que leur adresse mail apparaissaient dans les réponses usagers, ce qui est assez embetant.

**Comment by kemenaran** [comment]
C'est un peu bizarre. En regardant rapidement dans le code, je me demande d'où ça peut venir. Tu as des précisions là dessus ? Un exemple de réponse usager ?

**Comment by kemenaran** [comment]
C'est un peu bizarre. En regardant rapidement dans le code, je me demande d'où ça peut venir. Tu as des précisions là dessus ? Un exemple de réponse usager ?

**Comment by clemenceleurent** [comment]
Je demande au BER s'ils peuvent nous envoyer des captures d'écran :)

**Comment by red1bush** [comment]
Voici un mail du BER 93 également qui décrit la situation avec un exemple de no de dossier: 
https://secure.helpscout.net/conversation/628352659/5027?folderId=1948973

**Comment by fredZen** [comment]
Quand les accompagnateurs répondent sur la messagerie, l‘usager peut voir leur mail. A priori ça doit venir de là.

Exemple avec une procédure de test

![capture d ecran de 2018-07-26 11-21-26](https://user-images.githubusercontent.com/356570/43254210-2e24cf0a-90c7-11e8-9396-818e102cf121.png)

**Comment by gregoirenovel** [comment]
Dup #185
