### ISSUE TITLE
ETQ usager, je suis perdu dans ma liste de dossiers

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/tps#2308]
Problème soulevé par une entreprise répondant à de nombreux appels à projet sur DS : 

"Afin de faciliter la lecture de la liste des projets d'une même structure, il serait utile que à minima l'acronyme (s'il existe ?), et le titre du projet et le nom du chef de projet apparaissent sur cet interface.
En effet une liste de numéro n'est pas très parlante pour nous, il il faut à chaque fois ouvrir les fichiers pour savoir de quel projet il s'agit." cf HS 5038 

Ils ont en effet une vingtaine de dossiers apparaissant sur leur tableau de bord, avec à chaque fois seulement le nom de la procédure et le n° de dossier. ça ne leur permet pas de distinguer leur differents appels à projet.

**Comment by gregoirenovel** [comment]
Dup #2191
