### ISSUE TITLE
Rajouter un linter pour editorconfig

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2310]

**Comment by kemenaran** [comment]
@gregoirenovel Pourquoi ?

**Comment by gregoirenovel** [comment]
Parce que pour le moment seuls les devs équippés du bon plugin sur leur éditeur de texte enforcent les règles définies dans le .editorconfig du repo.

Maintenant qu’on a une dépendance à node on peut rajouter un linter à la CI, la majorité des linters d’editorconfig étant en JS.

**Comment by gregoirenovel** [comment]
Dup de #1747
