### ISSUE TITLE
Certains usagers ne voient plus le bouton "Soumettre le dossier"

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2311]
Depuis la mise en prod du bouton "Supprimer un brouillon", certains utilisateurs disent qu'ils ne voient plus que ce bouton là – et que le bouton "Supprimer un dossier" est absent.

`HS #5053`
`HS #5061`

D'après une des captures d'écran, c'est peut-être Internet Explorer le problème.

![image001](https://user-images.githubusercontent.com/179923/43387791-ac79685c-93e7-11e8-8ed3-ca57ac2976fb.png)

**Comment by red1bush** [comment]
En ayant conçu un formulaire et mis en prod pour le webinaire, j'ai eu le mm probleme (voir screenshot). A savoir: ni bouton soumettre, ni enregistrer le brouillon ni meme le champ service en footer.
 J'ai demandé à Benjamin d'essayer et ca a fonctionné de son coté.
En allant en Navigation privée j'ai tout qui fonctionnait, et en retournant en navigation normale après cela tout était rentré dans l'ordre dans mon formulaire.

![image 1](https://user-images.githubusercontent.com/32521418/43391982-928fe578-93f2-11e8-9615-b2220b5a36b5.png)
![image](https://user-images.githubusercontent.com/32521418/43391986-9710a5e2-93f2-11e8-8a10-64d64eb7876e.png)
