### ISSUE TITLE
Rediriger le trafic HTTP sur du HTTPS

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/tps#2320]
Quand je tape demarches-simplifiees.fr dans ma barre d'adresse, je tombe sur erreur 503

Pareil que pour les mails qui transforme demarches-simplifiees en http.demarches-simplifiees.fr `HS #5162`
Signalé aussi par B.Dobrani en mail perso

**Comment by Benjamin-Doberset** [comment]
J'ai le même problème quand je tape directement dans ma barre d'adresse

**Comment by gregoirenovel** [comment]
Le problème c'est le HTTP qui redirige pas vers HTTPS. Je reproduis BTW.

Cf. aussi `#5194`.

**Comment by gregoirenovel** [comment]
À communiquer : `HS #5162`

**Comment by fredZen** [comment]
Il doit y avoir une config à corriger du côté du load balancer, car quand je modifie mon `/etc/hosts` pour faire pointer `demarches-simplifiees.fr` directement sur une de nos machines de prod (sans passer par le LB), la redirection se fait comme il se doit.

**Comment by fredZen** [comment]
J’ai mis en place un deuxième front-end sur le loadbalancer chez OVH.

Le front-end existant ne gérait que le https. Le nouveau front-end gère le http.

La redirection proprement dite est gérée par notre nginx.

**Comment by fredZen** [comment]
Communiqué sur `HS #5162` le 2 août par bibi, je n’ai pas trouvé de Dobrani à contacter ni dans le helpdesk ni dans le CRM. @Benjamin-Doberset je te laisse lui communiquer si ça a encore du sens, dans tous les cas je ne tarderai pas à supprimer le label `à communiquer`
