### ISSUE TITLE
Problèmes au déploiement

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2330]
On doit executer les commandes suivantes après un deploy pour que les bons assets soient servis :
```
sudo service tps{_dev} stop
sudo service tps{_dev} start
```

**Comment by kemenaran** [comment]
Apparemment les assets sont au bon endroit. Ça semble être un problème de serveur qui redémarre mal.

Le redémarrage d'unicorn après une mise à jour est défini dans `/etc/init.d/tps{_dev}`. La commande `upgrade` envoie un signal à Unicorn, en lui demandant de recharger le code pour chaque worker, l'un après l'autre.

Mais quand on exécute `/etc/init.d/tps{_dev} upgrade`, les logs d'Unicorn indiquent une erreur :

> INFO -- : executing ["/var/www/tps_dev/current/bin/unicorn", "-c", "/var/www/tps_dev/current/config/unicorn.rb", "-E", "staging", "-D", {14=>#<Kgio::UNIXServer:/tmp/unicorn.tps_dev.sock>, 15=>#<Unicorn::TCPSrv:fd 15, AF_INET, 127.0.0.1, 8806>}] (in /var/www/tps_dev/releases/965)
>
> /var/www/tps_dev/shared/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:457:in `exec': No such file or directory - /var/www/tps_dev/current/bin/unicorn (Errno::ENOENT)

En clair, Unicorn ne redémarre pas, parce qu'il essaie de trouver un binstub pour unicorn dans `./bin`, et que ça échoue.

De fait, le binstub `bin/unicorn` n'est pas présent.

## Pourquoi ça fonctionnait avant

Avant, le dossier `./bin` était partagé entre toutes les instances. Et de fait, dans `/var/www/tps{_dev}/shared/bin`, on trouve bien un binstub pour Unicorn.

## Comment corriger

J'ai généré à la main les bons binstubs (pour Unicorn), et ça permet au serveur de redémarrer correctement.

**Comment by tchak** [comment]
Ce que je ne comprends pas c’est d’où viens ce bin stub dans ansible… Il y a bien une histoire de bin stub unicorn dans le role rails_app mais je n’ai pas trouvé où tps hérite de rails_app…

**Comment by tchak** [comment]
Mais :+1: pour cette PR

**Comment by kemenaran** [comment]
Je ne sais pas comment se fait l'héritage de `rails_app` dans Ansible, mais manifestement c'est ça qui génère les binstubs partagés, en tout cas.

Cela dit je me demande si plutôt que de générer les binstubs, on ne devrait pas revenir aux binstubs partagés. Ça a l'air de fonctionner bien, ce que j'ai fait – mais je ne suis pas sûr de maîtriser toutes les implications. À voir.

**Comment by tchak** [comment]
Je viens de comprendre. Il n'y a pas d'héritage. Les bin stub sont générer par le `rails_app` rôle de manière indépendante de `tps`. Ce qui veux dir qu'on utilisait l'artefact d'un autre rôle 🤦‍♂️
