### ISSUE TITLE
Créer et utiliser des sous-comptes Mailjet

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2337]
Cf. `HS #5213`

Afin de distinguer les campagnes des mails transactionnels et améliorer notre déliverabilité

**Comment by kemenaran** [comment]
Fait.

**Comment by kemenaran** [comment]
Mais on a rollback : trop de bounce sur le sous-compte, et donc nos emails ont été bloqués.

**Comment by kemenaran** [comment]
Discussion plus générale dans #2982 .
