### ISSUE TITLE
Kit UI

### ISSUE THREAD

**Issue by MarineCrespel** [betagouv/tps#238]
Mettre à disposition aux développeurs un kit UI avec : 
- utilisation du logo
- font utilisée
- couleurs
- niveau de titres
- boutons
- formulaires
- composants

**Comment by MarineCrespel** [comment]
[Kit Ui.pdf](https://github.com/sgmap/tps/files/973771/Kit.Ui.pdf)

**Comment by kemenaran** [comment]
C'est fait : https://demarches-simplifiees.fr/patron
