### ISSUE TITLE
ETQ Usager sur la landing page je ne veux pas créer de compte Administrateur par erreur

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2382]
Pas mal d'usager arrivent sur la page d'accueil demarches-simplifiees (sans lien direct vers une démarche). Normalement la marche à suivre est de créer un compte Usager – mais un bon nombre d'entre eux cliquent au mauvais endroit, et envoient à la place une demande de création de compte Administrateur.

On pense que c'est parce que le vocabulaire et la présentation de la page d'accueil n'est pas assez clair.

Pistes : séparer la page d'accueil en deux :

- la page principale pour les usagers ;
- une page secondaire orientée vers les administrations.

(Remonté par @clemenceleurent)

**Comment by clemenceleurent** [comment]
On peut aussi éviter la confusion en faisant une charte graphique differente pour les 2 pages, pour que la difference soit bien claire visuellement. Peut être du vert comme couleur principale pour la page demarches-simplifiees.fr/administrateur ?
