### ISSUE TITLE
ETQ usager, je veux connaître le délai moyen d’instruction de mon dossier

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/tps#2395]
Nous recevons beaucoup de tickets d'usagers demandant des informations sur le délai d'instruction de leur procédure. (ex : `HS #5500`)

Solution proposée : 
- ajouter un champs dans l'onglet "description" dans l'interface administrateur indiquant le délai moyen d'instruction ( à titre indicatif ?)
- afficher systématiquement cette information à la fin de la description des procédures pour les usagers et/ou dans le "merci" qui s'affiche une fois le dossier soumis

**Comment by clemenceleurent** [comment]
On pourrait presque afficher le temps réel d'instruction, puisque nous avons ces données... Les administrations ne seront peut être pas d'accord par contre

**Comment by gregoirenovel** [comment]
On peut le faire (affichage systématique) : 
- sur la future page de garde qu'on va mettre en place avec le nouveau design usager
- sur la page "résumé" d'un dossier

Pour les administrations, on attend qu'elles se plaignent et on verra ensuite :)

**Comment by kemenaran** [comment]
C'est fait.

On a quelques soucis avec le calcul automatique :

- Quand des dossiers sont traités par lot, ça marche moyen
- Quand des vieux dossiers sont classés sans suite pour nettoyer la file, ça augmente le temps de traitement artificiellement
- Certaines administrations voudraient pouvoir masquer ou rectifier le temps estimé manuellement

Mais le gros de l'issue est implémenté.
