### ISSUE TITLE
Mailjet: 250 mails bloqué en 15 jours depuis le 1 aout. pourquoi ?

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#2396]
https://app.mailjet.com/support/public-ticket/e03c12e8281e60e4af23f1500aac4613

Mailjet semble dire que c'est principalement du à des mails invalides.

Il conviendrait de 
- cleaner la mailing liste  `Invitation - Webinaires de présentation demarches-simplifiees.fr`
- voir si lorsqu'on envoi un mail, on ne peut pas attraper les erreurs mailjet et les traiter plutot que du fire and forget (flagguer l'utilisateur ?  nous envoyer des mails ? recommencer uniquement si server busy ?)

**Comment by chaibax** [comment]
Il existe pas mal de solution de cleaning d'email, que ce soit a partir d'un fichier , ou mieux, via une API pour empêcher d'enregistrer a un moment chez nous un email invalide. 

Perso, j'utilise http://www.listwisehq.com/ pour des gros fichier, et niveau api :  https://www.mailgun.com/email-validation
Il parait que https://www.briteverify.com/ est pas mal aussi (et connecté a Mailgun ). 

Je peux m'occuper de cleaner "Invitation - Webinaires de présentation demarches-simplifiees.fr"  du coup

**Comment by kemenaran** [comment]
(Sans doute lié à #2337)

**Comment by BriceDelh** [comment]
A titre d'information, je viens d'être confronté à un blocage de mes mails par l'API de mailjet (V3) alors que cette dernière me retournait bien un code signifiant que l'envoi était bien passé. 

La cause de ce blocage par les algorithmes de Mailjet était que j'avais utilisé des URL comme ancre ou même simplement affiché des URL (dans une balise p), ce qui allait à l'encontre de leur système de réécriture de liens pour le tracking. 

Je ne sais pas si cette réponse pourra aider mais elle m'aurait fait économiser un peu de temps aujourd'hui :)

**Comment by kemenaran** [comment]
@BriceDelh bon à savoir :) De fait on a désactivé le tracking des liens sortants sur notre compte Mailjet, ce qui aide sans doute à ne pas rencontrer ce problème.

**Comment by fredZen** [comment]
Oui, c’est effectivement pour ça qu’on avait désactivé le tracking des liens avec Sim (les URLs affichées différentes des URLs effectives plombaient notre score dans SpamAssassin)

**Comment by kemenaran** [comment]
J'ai l'impression qu'on sait maintenant pourquoi, et qu'on peut fermer cette issue. Ça vous va ?

**Comment by fredZen** [comment]
Aucun chevalier vaillant ne s’étant porté au secours de l’issue, je ferme. Ceux qui voudraient rouvrir savent comment faire :-)
