### ISSUE TITLE
504 Gateway Time-out sur /stats

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#2398]
(Parfois cela fonctionne correctement)

Il faut surement faire un peu de ménage dans les stats qui sont affichées, certaines sont trop gourmandes en calcul et ne sont pas forcément utiles.

**Comment by fredZen** [comment]
Je ferme car j’ai l’impression que le problème est résolu. N’hésite pas à rouvrir si je me suis trompé.

**Comment by mmagn** [comment]
Oui on avait fait le ménage, et les serveurs sont plus puissants. 
Mais il y a encore des progrès à faire.
