### ISSUE TITLE
Router les réponses aux mails automatiques vers la messagerie

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/tps#2418]
Cas d'usage : en tant qu'usager, quand je reçois un mail automatique sur l'avancée de mon dossier, je réponds directement si j'ai une question, je ne passe pas par la messagerie. Le mail atteri donc chez DS, au lieu d'arriver au service instructeur. 

Pour résoudre ce problème, nous avons déjà créé un lien direct vers la messagerie, dans le footer au bas du mail automatique. 

Pour aller plus loin nous pourrions créer une redirection automatique vers la messagerie, lorsque les usagers cliquent sur "reply".

**Comment by tchak** [comment]
duplicate of #1783
