### ISSUE TITLE
ETQ Usager je souhaite pouvoir supprimer mes dossiers en brouillon/construction à partir de mon tableau de suivi des dossiers

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/tps#2423]
Actuel : ETQ usager je dois rentrer dans mon dossier, remplir la premiere page (siret ou nom/prénom) puis accéder au formulaire, descendre en bas de page pour pouvoir trouver le bouton "supprimer mon dossier".

Proposition : ETQ usager je vois dans mon tableau de suivi tout mes dossiers rangés en ligne. A la fin de chaque ligne, à coté de l'état de mon dossier, je trouve une petite poubelle qui me permet de supprimer directement mon dossier.

**Comment by Benjamin-Doberset** [comment]
HS# 5588

**Comment by kemenaran** [comment]
Ça me semble pas mal – même si ça complexifie un peu la liste.

On pourrait n'afficher l'icône "Supprimer" que au survol, mais ça ne fonctionne pas pour les utilisateurs mobiles / tablettes.

Des idées ?

**Comment by red1bush** [comment]
Appliquer ce la aussi aux dossiers dont les procédures sont archivées

**Comment by kemenaran** [comment]
Ça permettrait de résoudre aussi #2687 et #2436.
