### ISSUE TITLE
ETQ usager, je veux pouvoir supprimer un brouillon a peine rempli

### ISSUE THREAD

**Issue by clemenceleurent** [betagouv/tps#2436]
Problème souligné par S.B. de France Agrimer : "il est possible de supprimer un brouillon mais il faut avoir « dépassé » le stade saisie et validation du n° SIRET pour le faire car sinon ce n'est pas accessible"
cf https://secure.helpscout.net/conversation/645353524/5740?folderId=2080409  

Idée : ajouter une petite poubelle dans la liste des dossiers, pour chaque ligne

**Comment by gregoirenovel** [comment]
Ça sautera automatiquement quand on aura fait de l'identification des champs

**Comment by LeSim** [comment]
`HS #6337`

**Comment by LeSim** [comment]
`HS #7997`

**Comment by red1bush** [comment]
Ajouter la possibilité de supprimer les brouillons de dossiers archivés

**Comment by mmagn** [comment]
Solution retenue par l'équipe : dans un premier temps on ajoute un bouton "supprimer" sur les pages d'identification SIRET et Individu. On verra si c'est suffisant.

**Comment by emsnytech** [comment]
pourquoi pas sur le tableau de bord ?
Si j’ai un dossier en construction, je n’accède pas (plus ) à cette page.
Or on doit pouvoir supprimer un dossier en construction.

Donc, à moins que je n’ai pas compris, je ne suis pas ok ....

On ne se précipite donc pas sur ce dev....


Envoyé de mon iPhone

**Comment by mmagn** [comment]
Comme vu ensemble mardi dernier on propose le bouton depuis la liste des dossiers.

**Comment by mmagn** [comment]
Réglé avec la https://github.com/betagouv/tps/issues/2423
