### ISSUE TITLE
ETQ instructeur je veux pouvoir trier les instructeurs à qui je veux envoyer un dossier

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2540]

**Comment by gregoirenovel** [comment]
`HS 6023`

**Comment by kemenaran** [comment]
Pour l'instant un dossier est forcément envoyé à tous les instructeurs ?

**Comment by gregoirenovel** [comment]
Non, pour l'instant tu ne peux envoyer qu'un dossier à un instructeur à la fois, l'idée c'est de pouvoir en envoyer un à plusieurs instructeurs d'un coup, et d'au passage pouvoir facilement sélectionner les instructeurs dans la liste des instructeurs.
