### ISSUE TITLE
Certains templates utilisent encore la balise `--libelle-procedure--`

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2544]
Le renommage "Procedure" -> "Démarche" (#2521) a renommé la balise `--libelle-procedure--` en `--libelle-demarche--`. Ça a cassé les templates d'emails existants.

Il faudrait faire passer une moulinette sur les templates d'emails existants.

**Comment by kemenaran** [comment]
`HS #6369`

**Comment by gregoirenovel** [comment]
Ça peut aussi toucher les templates d'emails
