### ISSUE TITLE
Tri/filtrage : NewGestionnaire::ProceduresController est trop intime avec Procedure

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2584]
Les méthodes `filtered_ids` et `sorted_ids` du `NewGestionnaire::ProceduresController` ne sont pas où elles devraient être. Pour le démontrer, j’avance les arguments suivants :

- elles sont fortement couplées à `Procedure#fields` : quand on rajoute un nouveau field, on se retrouve automatiquement aussi à éditer ces deux méthodes là
- elles contiennent du SQL qui a une connaissance intime de la structure en base d‘un dossier
- le fait que ce soient des méthodes privées dans un contrôleur les rend pénibles à tester

Dans une moindre mesure, `Dossier#get_value` est touchée par le même problème.

J’ai deux propositions alternatives pour améliorer la situation

# Proposition 1 : créer un service (nom à déterminer)

Ce service serait responsable de la présentation tabulaire des dossiers. On y migrerait les méthodes

- `NewGestionnaire::ProceduresController#filtered_ids`
- `NewGestionnaire::ProceduresController#sorted_ids`
- `Procedure#fields`
- `Dossier#get_value`

# Proposition 2 : migrer `filtered_ids` et `sorted_ids` dans `Procedure`

Ça ne règle pas le problème de `Dossier#get_value`, mais ça évite de créer un service et ça réduit aussi bien la douleur pour `filtered_ids` et `sorted_ids`.

**Comment by kemenaran** [comment]
Merci pour la présentation super-claire.

En général j'aime bien les Services. Ça m'embête toujours un peu de trop coupler les Modèles avec la couche de présentation – et aussi le risque de fat-model est assez réel.

Du coup je dirais plutôt Service. Cela dit est-ce que conceptuellement ce dont on aurait besoin là c'est pas d'un ViewModel ? (même si c'est implémenté comme un service ou whatever ?)

**Comment by fredZen** [comment]
Je dois avouer que je ne connais pas bien MVVM mais oui, conceptuellement ça semble matcher

**Comment by LeSim** [comment]
Merci Fred pour le taff. Je partage tes conclusions.

Petite question innocente, y'a t'il un autre endroit dans l'interface ou l'on désirerait filtrer un tableau de dossier ?

**Comment by kemenaran** [comment]
@fredZen Oui, le tri des dossiers côté Usager c'est une demande qui revient régulièrement (#2191). Pas dit qu'on le fasse tout de suite, mais si c'est facile de le faire un jour ça serait top.

**Comment by kemenaran** [comment]
On pourrait envisager une `DossiersTableDataSource`, qui prendrait une liste de dossier, des options de tri, et se chargerait d'exposer plein d'accesseurs pratiques pour construire la vue, tiens. (Mais peut-être que ça se rapproche de `smart_listing`)
