### ISSUE TITLE
ETQ Usager, je veux comprendre la marche à suivre pour valider mon adresse email

### ISSUE THREAD

**Issue by chaibax** [betagouv/tps#2586]
Hello,

Suite à ce ticket : https://secure.helpscout.net/conversation/663618806/6539?folderId=1653804 / , il apparait que l'inscription n'est pas claire.

En effet, quand on se créer un compte dans DS pour remplir une démarche, on arrive sur une page avec trop d'info inutile (la home de DS ) et pas suffisamment d'info utile.
Il y a juste un bandeau basique, qui n'explique pas ce qu'il y a faire ensuite. 

<img width="1256" alt="capture d ecran 2018-09-17 10 10 56" src="https://user-images.githubusercontent.com/3593868/45613474-cd624480-ba66-11e8-90b4-51faf7b738f4.png">

Il faudrait créer une page dédiée, suite à la création du compte , sans fioriture, expliquant qu'on va recevoir un email qui permettra de confirmer son compte, mais surtout de remplir [NOM DE LA DEMARCHE] . 

Idem pour l'email de confirmation : on devrait  ajouter à la suite de : 

"Pour activer votre compte sur demarches-simplifiees.fr, veuillez cliquer sur le lien suivant : https://www.demarches-simplifiees.fr/users/confirmation?confirmation_token=sPvCBJ2GNrH9WQcio6xA" 

Vous pourrez juste après commencer la remplir la démarche [NOM DE LA DEMARCHE]

**Comment by kemenaran** [comment]
Bonne idée, la page dédiée 👍

**Comment by chaibax** [comment]
Exemple de page dédié sympa : 
<img width="1259" alt="capture d ecran 2018-09-19 14 15 05" src="https://user-images.githubusercontent.com/3593868/45752645-756a4000-bc16-11e8-9031-0129342efaba.png">

**Comment by kemenaran** [comment]
Une bonne resource à ce sujet : [Gov.uk Design System: Confirm an email address](https://design-system.service.gov.uk/patterns/confirm-an-email-address/).

**Comment by kemenaran** [comment]
Pour référence et pour amélioration future, la page de confirmation de N26, que je trouve assez bien faite.

## Desktop

<img width="943" alt="capture d ecran 2018-11-16 a 10 22 30" src="https://user-images.githubusercontent.com/179923/48662991-1c8a1d00-ea8a-11e8-9b2b-502a8b7fc7b8.png">

## Mobile

![n26-mobile](https://user-images.githubusercontent.com/179923/48662993-20b63a80-ea8a-11e8-9479-3e47ee6d6d5f.gif)
