### ISSUE TITLE
Afficher le taux de contact sur la page /stats

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2587]
Le taux de contact, c'est le rapport entre le nombre de tickets traités par le service client et le nombre d'utilisateurs.

Je pense que ça serait une métrique très utile à avoir :

- Le taux de contact est un bon indicateur de la **satisfaction des utilisateurs**. (Quand tout va bien, pas besoin de contacter le support.)
- C'est aussi un bon indicateur de la **qualité du produit**.
- C'est un indicateur qui ne nécessite pas de faire travailler les clients (par exemple en faisant remplir un formulaire de satisfaction, etc.)
- Quand le nombre de tickets augmente, ça nous permet de savoir si c'est à cause de la croissance ou d'autre chose.
- Ça nous permet de voir si on arrive à améliorer suffisamment le produit pour réduire le taux de contact.
- Ça permet d'évaluer l'évolution du nombre de tickets dans le futur, et notre capacité à les traiter.

### Risques

Comme toute métrique, il y a deux questions ?

**Est-ce qu'on mesure la bonne chose ?**

Je pense que oui. Au final, ce qu'on veut réellement, c'est la satisfaction des usagers. Le nombre de fois où un Usager a besoin de nous contacter est sans doute un bon indicateur de ça. Je ne vois pas comment on pourrait avoir un taux de contact qui augmente, mais un produit qui est en fait meilleur.

**Est-ce qu'on ne risque pas d'optimiser le chiffre, plutôt que ce qu'on mesure ?** Autrement dit, est-ce qu'on ne risque pas de vouloir faire baisser le taux de contact artificiellement ?

Le risque évident, c'est qu'on rende l'adresse de contact plus difficile à trouver, pour réduire le taux de contact artificiellement. Mais j'ai qu'une fois que ce risque est identifié, ça va : on n'est pas dans du tout dans cette dynamique de dissimulation. Et une fois qu'on se l'est dit, on se met tous d'accord pour se dire qu'on ne masquera pas l'adresse de contact volontairement, et basta.

Par ailleurs il y a de bien meilleures pistes pour réduire le taux de contact : amélioration du produit, redirection des réponses par email sur la messagerie, etc. Toutes ces pistes améliorent réellement l'expérience des usagers.

### Implémentation

On doit mesurer deux choses :

- **Le nombre de tickets**. On va interroger HelpScout pour ça (j'imagine qu'il y a une API). Est-ce qu'on compte tous les tickets, ou seulement les tickets Usagers ? Je dirais que "Tous les tickets" c'est une bonne approximation.
- **La croissance du site**. On peut compter le nombre de dossiers déposés, ou le nombre d'usagers. Les deux me semblent pertinents.

**Comment by gregoirenovel** [comment]
Pour l'implem, on peut aussi rajouter un compteur sur notre formulaire de contact

**Comment by kemenaran** [comment]
C'est fait, et c'est en ligne : http://demarches-simplifiees.fr/stats
