### ISSUE TITLE
Accès à l'UI web des delayed jobs impossible en prod

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2625]

**Comment by fredZen** [comment]
Tu peux préciser ?

J’arrive à accéder à la page des delayed jobs dans le manager de prod, je suppose que tu parles d’autre chose.

**Comment by gregoirenovel** [comment]
Yes L quand je clique sur le lien depuis le maanger de prod, je tombe sur une page blanche avec simplement écrit `Forbidden`

**Comment by tchak** [comment]
Je ne reproduis pas non plus

**Comment by gregoirenovel** [comment]
Marche toujours pas chez moi. Je me suis sign out puis sign in, toujours pareil.

**Comment by gregoirenovel** [comment]
Bon ça marche sous Safari mais pas FF, on va dire que c'est OK, si ça se reproduit j'investiguerai plus
