### ISSUE TITLE
ETQ Usager je veux remplir les infos de carto dans la nouvelle UI

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2681]
## Notes d'implémentation

La carto dans l'ancienne UI utilise une ancienne version de Leaflet.js. On appelle des fonctions dépréciées depuis. (cf. #2683)

La nouvelle UI utilise une version plus récente de Leaflet ; ça sera bien de migrer notre code vers cette version au passage.

**Comment by kemenaran** [comment]
@tchak a déjà commencé à refactorer la partie JS là dessus (dans une branche). À voir avec lui.

**Comment by tchak** [comment]
https://github.com/betagouv/tps/pull/2732

**Comment by kemenaran** [comment]
J'ai cru comprendre qu'on était en train d'implémenter la carto comme un champ de formulaire.

Est-ce qu'on a prévu de dégager cette page à court terme (genre dans le prochain mois), ou est-ce qu'elle va vivre encore un peu le temps de la transition et de la migration des procédures existantes ?

**Comment by gregoirenovel** [comment]
À mon avis cette page va encore vivre le temps qu'on migre toutes les anciennes carto sur le nouveau champ.

La migration n'est probablement pas déconnante, je pense que c'est jouable de travailler dans l'immédiat sur la tache de migration plutot que sur le portage de cette page, histoire de la jouer dès le champ en place et un peu testé. (et comme ça on évite de se trainer du legacy comme on a un peu trop tendance à le faire).

@mmagn t'en penses quoi ?

**Comment by gregoirenovel** [comment]
La migration ça veut dire, selon moi :
- rajouter un type de champ carto au début de tous les formulaires qui ont cette option d'activée (et donc décaler l'ordre des autres TDC de 1)
- bien le configurer comme l'ancienne carto vis à vis des PC et des QP
- rajouter le champ correspondant au TDC dans tous les dossiers des démarches concernées
- préparer la PR qui :
  * fait sauter l'ancienne gestion de la carto dans l'UI administrateur
  * nettoie les nouvelles vues de dossier pour enlever la vue de l'ancienne carto

**Comment by tchak** [comment]
Celons-moi, il faut se concentrer sur la migration. Je suis d'accord avec la liste de @gregoirenovel 

> regarder les impact sur l'API et l'export de dossiers

ça va être le plus compliquer

**Comment by tchak** [comment]
Création du champ carte #2831

**Comment by tchak** [comment]
Justement. On va devoir faire de la bidouille sur la bidouille. Car la bidouille consiste à faire un champ par `geo_area`, alors que maintenant c'est un champ `has_many` `geo_area`.

**Comment by gregoirenovel** [comment]
Au pire on contact les admins concernés et on casse l'API

**Comment by gregoirenovel** [comment]
On ferme, donc ?

**Comment by kemenaran** [comment]
Quand la PR sera mergée ? :)

**Comment by kemenaran** [comment]
Corrigé par #2930.
