### ISSUE TITLE
ETQ Usager je veux supprimer un dossier en construction

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2687]
Un Usager peut supprimer un dossier en brouillon.

Avant la mise en prod de la nouvelle UI Usager, iel pouvait aussi supprimer un dossier en construction (avant le passage en instruction).

Il faut peut-être porter cette fonctionnalité dans la nouvelle UI.

**Comment by kemenaran** [comment]
Note de @emsnytech :

> assez d'accord avec ta proposition, mais attention tout de même.

> En effet, dès qu'il est en construction, cela pose un pb de le supprimer de manière abrupte (quand le dossier à été envoyé à une administration en papier, tu ne peux pas le supprimer, sauf à demander à l'administration de le supprimer, ou d'aller le rechercher).
>
> Je propose de garder l'interdiction de pouvoir le supprimer quand il est en construction, avant que l'on ai trouvé qque chose de propre. (l'usager vous informe qu'il souhaite supprimer sa demande).
>
> Bref, niveau UX il faut continuer à réfléchir. On va poser la questions aux open lab pour avoir des idées.

**Comment by kemenaran** [comment]
À noter que quand un Usager supprime un dossier en construction, un email de notification est envoyé à l'Instructeur qui suit le dossier (ou à l'Admin si le dossier n'était pas encore suivi).

**Comment by gregoirenovel** [comment]
`HS #7645`

**Comment by mmagn** [comment]
HS 9163

**Comment by gregoirenovel** [comment]
HS 7720

**Comment by kemenaran** [comment]
`HS 10144`

**Comment by kemenaran** [comment]
Corrigé par #3390
