### ISSUE TITLE
ETQ Usager je veux voir le bouton "Créer un compte"

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2692]
Quand on arrive sur la page "Commencer une démarche", on voit surtout le formulaire de connexion.

Le bouton "Créer un compte" est caché : tout en bas, tout petit, sans marge.

Retour utilisateur (`HS 6923`) :

> durant nos tests les utilisateurs n'arrivaient pas à y accéder (lors d'une 1er connexion ), car le bouton « créer votre compte » est situé en bas de la page et donc peu visible.
>
> Serait-il possible de le remonter svp ?

![creer-un-compte](https://user-images.githubusercontent.com/179923/46096213-e8e3f280-c1be-11e8-869d-6e2bae1aee49.gif)

**Comment by kemenaran** [comment]
On pourrait :

- Remonter le bouton et le rendre plus visible ;
- Refaire tout le workflow, en mettant d'abord "Quel est votre email ?", puis "Rentrez votre mot de passe existant" ou "Définissez un mot de passe pour créer un compte".

**Comment by kemenaran** [comment]
Je serai pour une solution-peinture dans un 1er temps – mais je ne vois pas trop comment rendre ce bouton plus visible visuellement…

**Comment by kemenaran** [comment]
(/cc @chaibax)

**Comment by gregoirenovel** [comment]
Ça me semble être un dup de #549 et #551

**Comment by gregoirenovel** [comment]
De toute façon avec la page de garde ça ne sera plus problématique, on proposera les deux options (connexion ou inscription) en bas de page. Je propose de fermer cette issue et de backporter le à communiquer dans l'issue "page de garde", si elle existe

**Comment by kemenaran** [comment]
Si la page de garde arrive rapidement, genre moins d'un mois, je dirais pas trop.

Sinon je pense que ça vaut le coup de faire 1h de CSS pour mettre un `<blink style="font-size: 3em; color: red;">` autour du bouton "Créer un compte".

**Comment by gregoirenovel** [comment]
Temporairement on peut juste le remonter en haut de "Connectez-vous", ça coute pas cher en effet
