### ISSUE TITLE
Le calcul du temps moyen de réponse fait planter la page

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2696]
Plusieurs exceptions remontées dans Sentry.

```
ActionView::Template::Error 
undefined method `-@' for nil:NilClass

TypeError: can't convert nil into an exact number
  app/models/procedure.rb:408:in `block in mean_time'
    .map { |times| times[1] - times[0] }
  app/models/procedure.rb:408:in `map'
    .map { |times| times[1] - times[0] }
  app/models/procedure.rb:408:in `mean_time'
    .map { |times| times[1] - times[0] }
  app/models/procedure.rb:338:in `mean_instruction_time'
    mean_time(:en_instruction_at, :processed_at)
  app/views/new_user/dossiers/show/_status_overview.html.haml:42:in `_app_views_new_user_dossiers_show__status_overview_html_haml__3517954728521896040_7062998465400'
    - if dossier.procedure.mean_instruction_time
...
```

C'est par exemple le cas sur les dossiers 145059 et 159945.

**Comment by kemenaran** [comment]
@LeSim dit qu'il est dessus

**Comment by LeSim** [comment]
Après investigation je vois que nous avons étonnament 900 dossiers qui ont un `processed_at` mais pas de `en_instruction_at`. 

Le dernier date de décembre 2017, du coup, je suppose que le comportement qui générait ce genre de chose a été corrigé.

Finalement, je propose une moulinette rake pour rattraper ces dossiers et mettre `en_instruction_at` à `processed_at` ...

wdyt ?

**Comment by kemenaran** [comment]
@LeSim Carrément. D'une manière générale ça me semble une bonne idée d'harmoniser la bad data.

**Comment by gregoirenovel** [comment]
Ça sent le déclaratoire ça :)
