### ISSUE TITLE
ETQ Usager, je veux voir plus facilement le bouton  "Créer un compte" quand je dois me connecter

### ISSUE THREAD

**Issue by chaibax** [betagouv/tps#2699]
Actuellement, il faut souvent scroller vers le bas pour voir qu'il y a un bouton créer son compte quand un usager arrive sur cette page https://www.demarches-simplifiees.fr/users/sign_in 

Des usagers ne le voient donc pas, et ne savent pas quoi faire. 

Il faudrait réduire le bloc de connexion pour que le bloc d'inscription soit visible plus souvent. 

<img width="1279" alt="capture d ecran 2018-09-27 12 25 56" src="https://user-images.githubusercontent.com/3593868/46140307-0bbee700-c251-11e8-8729-ac6924fa8445.png">

Demande remonté par un admin ayant fait s'inscrire des usagers.

**Comment by gregoirenovel** [comment]
Dup #2692, merci de mettre le `a-communiquer` dans #2692
