### ISSUE TITLE
ETQ Usager, je veux utiliser le champ dossier lié avec un dossier que je n'ai pas moi mm déposé

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#2709]
`hs #6967`

Proposition :
A minima, changer les messages d'informations : 
- des infos sur le dossier, si l'usager à accès
- dire que le dossier existe si ... le dossier existe
- ou sinon dire que le dossier n'existe pas

**Comment by gregoirenovel** [comment]
Dup #2765
