### ISSUE TITLE
ETQ instructeur, impossible de supprimer un filtre au nom trop long

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2719]
<img width="946" alt="screen shot 2018-10-01 at 10 49 33" src="https://user-images.githubusercontent.com/1333173/46278863-c27bd980-c567-11e8-82ea-d38f3ef5d4d7.png">

**Comment by gregoirenovel** [comment]
À communiquer : `#7088`

**Comment by mmagn** [comment]
@pengfeidong s'en occupe
