### ISSUE TITLE
ETQ Usager je n'ai plus besoin de cocher la case à l'identification

### ISSUE THREAD

**Issue by emsnytech** [betagouv/tps#2725]
Vu avec Perica.
Quand on rentre avec un SIRET, suppression de la case à cocher et de la phrase qui va avec.
~Supression des 3 derniers chiffres d’affaires.~
~On en vient à n’afficher que les données publiques.~
A prendre en compte dans la nouvelle UX.

**Comment by kemenaran** [comment]
Ça tombe bien, j'allais justement refaire cette page en version "nouvelle UI".

**Comment by CamilleGarrigue** [comment]
Validé par Perica
Egalement supprimer dans les démarches personnes physiques la case à cocher "J'accepte les CGU"

**Comment by kemenaran** [comment]
>  Egalement supprimer dans les démarches personnes physiques la case à cocher "J'accepte les CGU"

C'est vrai ? Ça m'intéresse de savoir sur quoi il fonde le fait que ce n'est pas une obligation légale :)

**Comment by mmagn** [comment]
Je déporte la partie 3 derniers CA dans cette issue https://github.com/betagouv/tps/issues/2738

**Comment by gregoirenovel** [comment]
Je rouvre car il faut le faire dans la partie "individual" il me semble

**Comment by kemenaran** [comment]
De ce que je vois la partie "Individual" faisait bien partie du commit (https://github.com/betagouv/tps/commit/941c529b2cb21275b9b4ccd34558f0a220d49cc7#diff-49af776f8330658afd501545707d4f96).

**Comment by gregoirenovel** [comment]
En effet, my bad
