### ISSUE TITLE
ETQ Usager je veux que lorsque je clique sur un lien d'une demarche, le lien url qui s'affiche quand je me connecte soit le lien de la procédure

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/tps#2767]
Il faudrait une modification d'affichage du lien url. En effet, lorsqu'on clique sur le lien d'une démarche sans être au préalable connecté, le lien url dans la barre d'adresse est : https://www.demarches-simplifiees.fr/users/sign_in . Il faudrait que ce soit le lien de la procédure, en effet les usagers se trompent et partagent le lien user_sign_in entre eux

**Comment by gregoirenovel** [comment]
Dup de #2225
