### ISSUE TITLE
Dossiers supprimés quand un admin supprime une procédure

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2772]
Quand l’admin soft-delete une démarche (bouton _supprimer la démarche_ ), tous les dossiers de la démarche sont soft-deletés aussi. C’est très problématique pour les démarches en production.

# reprise de données
rétablir les dossiers supprimés (procédures 4860 et 6388)
Attention, il y aura aussi du code à changer car le `default_scope` exclut les `Procedure`s archivées, et donc le`Dossier` va se prendre des beaux `nil` dans la figure si on ne fait rien.

# empêcher le problème de se reproduire
par exemple, 
- désactiver le bouton _supprimer la démarche_, ou 
- arrêter de supprimer les dossiers quand on supprime une démarche

une fois qu’on saura faire la différence entre une procédure en test et une procédure en prod, on différenciera le comportement (c’est OK de supprimer une procédure et des dossiers tant qu’ils ne sont pas en prod)

**Comment by gregoirenovel** [comment]
Si on rétabli ces dossiers, on les rétabli sur quelles procédures, celles qui ont remplacé les supprimées ?

**Comment by fredZen** [comment]
Bonne question... On en parle en live la semaine prochaine ? Il faudra sans doute aussi en parler aux administrateurs et administratrices concernées.

**Comment by gregoirenovel** [comment]
@fredZen t'as les tickets concernés, de mon coté : 
- `HS #7365` (proc 6388)
- `HS #7387` (proc 6388)

**Comment by emsnytech** [comment]
Cela devient très urgent. je crains que nous n'ayons pas d'autre solutions que d'interdire la suppression des dossiers dans un premier temps
Je suis d'avis de rétablir sur la démarche comme t'elle.
Eventuellement, on peut passer tout les dossiers en archivé, pour qu'ils ne polluent pas le tableau de bord des agents traitants. ce qui est important, c'est que l'usager retrouve son dossier.
De toutes les façons, on ne peut pas supprimer tout dossier passer en instruction. L'usager doit avoir accès à son dossier. ce qui veut dire donc que l'on ne peut pas supprimer les démarches qui supportent ces dossiers. Du coup, il faut que nous trouvions une solution pour aller beaucoup plus vite pour distinguer les démarches en production des démarches en test. Malheureusement le chiffre de 30 ou de 20 ne va pas ( j'ai vu hier une démarche de 20 dossiers en production)

**Comment by gregoirenovel** [comment]
C'est en effet bien possible qu'on ait ajouté ce bouton pour supprimer des "démarches de test". Je suis d'accord avec Philippe qu'une fois les démarches de test bien en place, on peut supprimer ce bouton, et éventuellement le réintroduire plus tard mais avec validation de la suppression par quelqu'un de chez nous pour éviter des cas comme celui-ci.

**Comment by gregoirenovel** [comment]
Autres tickets support :
- `7580`
- `7561`

**Comment by kemenaran** [comment]
@fredZen toujours d'actualité ?

**Comment by fredZen** [comment]
non, ok je pense
