### ISSUE TITLE
Affichage de bad data dans le tableau de dossiers instructeur

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2800]
Cf. HS `#7592`

> Je constate un bug sur la plateforme sur l'une des démarches mise en place par le CD92.
> Le champ « nom de l'instructeur » est un champ de saisie libre alimenté par les agents du CD92 au début de l'instruction. Je constate qu'il est alimenté par une valeur depuis plusieurs jours ce qui n'était pas le cas avant (cf. copie écran).

![image001](https://user-images.githubusercontent.com/1333173/46737992-3a9b7b00-cc9d-11e8-9890-575ba78d5bd4.png)

Démarche 8094

Note : pour le dossier 182379, le contenu du champ private "Nom de l'instructeur" est `nil`

À communiquer : `#7592`

**Comment by fredZen** [comment]
Je vais jeter un coup d’œil comme j’ai touché à ce code récemment
