### ISSUE TITLE
Création d'une page statique "webinaire" sur le site public

### ISSUE THREAD

**Issue by chaibax** [betagouv/tps#2801]
Nous souhaitons pouvoir fournir aux administrateur et instructeurs des liens permettant de s'inscrire au webinaire, sans forcement en connaitre la date.

Pour cela, il faudrait créer une page statique et  caché,  dont l'url serait http://demarches-simplifiees.fr/webinaire . Celle-ci comporterait du texte statistique, une image et au moins un lien d'inscription au webinaire.

**Comment by gregoirenovel** [comment]
On peut faire ça sur le site de doc dans un premier temps ? Le lien ca va vers où ?

**Comment by chaibax** [comment]
Le lien va vers une ou des démarches simplifiées . Ca serait une page comme pour les open lab) .  On y présenterait le déroulé du webinaire . Pour l'instant on fourni uniquement le lien vers la démarche. Et ce lien peut changer ...

Oui le lien peut être créer sur la doc, mais je peux m'en occuper et reprendre, je pense, le gabarit  des open lab

**Comment by chaibax** [comment]
Finalement, j'ai crée une page dans la doc :D
