### ISSUE TITLE
ETQ Administrateur quand je clone une démarche avec un lien_notice je veux qu'il ne soit pas copié

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#2813]
Sinon il est impossible pour l'administrateur de supprimer le guide sans l'aide du support

**Comment by kemenaran** [comment]
Est-ce que ce qu'on voudrait faire, ça ne serait pas surtout de permettre de supprimer la notice d'un formulaire ?

**Comment by gregoirenovel** [comment]
D'accord avec @kemenaran, et au moins pour faire la distinction quand c'est un clone depuis la bibliotheque (suppression) ou pas (on garde la notice)

**Comment by mmagn** [comment]
Pour clarifier, on parle ici d'un vieil attribut `lien_notice` qui a été remplacé par un fichier attaché `notice`. Je ne sais pas si vous aviez tous les éléments en tête. 

Oui effectivement on peut rendre supprimable ce vieil attribut mais ça me gêne de rajouter ce code sachant car ça ne va pas totalement dans le sens pour qu'à terme on ai plus de démarche avec de `lien_notice`. 

Comme il n'est plus possible d'ajouter de `lien_notice` sur une nouvelle démarche créée de zéro, pour ne plus avoir de nouvelle démarche utilisant cet attribut, le plus simple semblait de la supprimer d'un clone, mais si vous avez d'autres idée...

**Comment by gregoirenovel** [comment]
En effet, merci beaucoup pour ton explication :)

Est-ce que, mais c'est hors scope et p-e un peu overkill, on peut envisager, pour supprimer cette colonne, de faire un script qui tape sur les liens des démarches qui en ont, convertissent le contenu du lien en pdf, et l'uploadent dans `notice` ?

**Comment by mmagn** [comment]
On a regardé au début pour le faire dans cette issue, mais le premier lien sur lequel j'ai tapé, je suis tombé sur un espace sécurisé :) du coup j'ai laché l'affaire.
Mais il faudrait peut être continuer, c'est le seul moyen de faire ça proprement.
