### ISSUE TITLE
Les taches after_party ne sont pas executées en prod

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2843]
Elles le sont en dev, mais en prod à chaque fois ça ne fait que ` no pending tasks to run`

**Comment by kemenaran** [comment]
D'après @gregoirenovel ça fonctionne quand on se connecte à la prod et qu'on fait un `bin/rake after_party:run` à la main.

Est-ce que le problème ça pourrait être que la commande pendant le deploy se connecte à la mauvaise base – ou utilise l'ancienne base de code (qui n'aurait donc pas encore la tâche) ?

**Comment by gregoirenovel** [comment]
À noter : on a touché à cette partie du script de deploy recemment
