### ISSUE TITLE
ETQ usager je vois un délai moyen de traitement pour une procédure déclarative 

### ISSUE THREAD

**Issue by red1bush** [betagouv/tps#2846]
Le délai de traitement n'est pas représentatif sur une procédure: ex avec la demarche #6547 voir screenshot

![stage3eme](https://user-images.githubusercontent.com/32521418/47021919-bcd3e580-d15c-11e8-88db-0aa7b4221338.gif)

**Comment by gregoirenovel** [comment]
Ce temps est correct. Les déclaratives qui passent automatiquement en instruction sont quand meme sensées etre instuites derrière pour que les dossiers ne restent pas "en instruction".

**Comment by gregoirenovel** [comment]
@red1bush pense au à communiquer la prochaine fois ;)

**Comment by gregoirenovel** [comment]
C'est qu'il y a eu un mauvais accompagnement lors de la mise en place du déclaratif je pense, mais :
- si tu fais du declaratif qui va direct en "accepté", le pb ne se pose pas
- si tu fais du déclaratif qui va en "en instruction", t'es de toute façon obligé d'instruire derrière, et c'est pas du déclaratif mais plus du "je ne veux pas permettre à l'usager de modifier son dossier après dépôt"

**Comment by gregoirenovel** [comment]
Fixed by #2869
