### ISSUE TITLE
Il y a encore des crashes sur le calcul du temps moyen d'instruction

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2854]
Y'a des traces dans Sentry.

@LeSim a fait tourner une moulinette, mais y'a encore de la bad data en prod.

J'ai un commit pour corriger la bad data, je m'en occupe.

**Comment by kemenaran** [comment]
Sentry : http://localhost:9002/apientreprise/tps/issues/3399/

**Comment by kemenaran** [comment]
J'ai l'impression que la moulinette précédente n'était pas passée : je l'ai appliquée en prod, et corrigé 966 dossiers.

Comme un seul dossier invalide suffit à faire planter le code pour tous les dossiers de la démarche, ça devrait corriger un paquet de dossiers.

**Comment by gregoirenovel** [comment]
On parle d e quelle moulinette ? Celle sur laquelle tu as fait un com récemment ? On peut la / le / les référencer ?

**Comment by kemenaran** [comment]
Oui, je parlais de 29e40fa06146e4b238d932c33db592a05ea4a237 (référencée dans #2696)
