### ISSUE TITLE
ETQ Opérateur je veux pouvoir configurer l'url de l'api géo

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/tps#2858]
@mmagn et @LeSim Pour rendre paramétrables les appels aux services, je propose de mettre les URLs dans la fichier `.env` ex: 

Ajouter dans le fichier `.env`: 
`API_GEO_URL="https://geo.api.gouv.fr"`

Supprimer dans le fichier ` tps/config/initializers/urls.rb`:  
`API_GEO_URL="https://geo.api.gouv.fr"`

Modifier dans le fichier ` tps/app/lib/api_geo/api.rb`:  
`url = [ENV["API_GEO_URL"], "regions"].join("/")`
`url = [ENV["API_GEO_URL"], "departements"].join("/")`

**Comment by mmagn** [comment]
Hello,

Ok pour nous, mais je pense qu'on peut rendre cette variable d'env facultative, avec un seul changement.
Dans `tps/config/initializers/urls.rb` :
```ruby
API_GEO_URL = ENV.fetch("API_GEO_URL", "https://geo.api.gouv.fr")
```

**Comment by pengfeidong** [comment]
OK, très bonne idée, mon idée de départ est de réduire les codes.
