### ISSUE TITLE
ETQ Usager je veux retrouver le brouillon de mon dossier facilement

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2860]
Aujourd'hui on a deux manières de récupérer un brouillon :

- Se connecter, cliquer sur "Dossiers", et voir le brouillon dans la liste ;
- Cliquer sur le lien reçu par mail.

Ça ne fonctionne pas : à la place les gens cliquent sur le lien "/commencer" à nouveau. Ça crée un nouveau brouillon au lieu de récupérer l'ancien. Et beaucoup, beaucoup de gens créent 4 ou 5 brouillons sur le même dossier.

### Proposition de solution

En tant qu'Usager, quand je clique sur un lien /commencer mais que j'ai déjà un brouillon pour cette procédure, un écran me propose de soit :

- Ouvrir le brouillon existant
- Créer un nouveau brouillon pour cette procédure

Ça rentre dans le chantier "Faire une page de garde pour les démarches".

**Comment by gregoirenovel** [comment]
Je ne vois pas pourquoi cette issue est distincte de celle de la page de garde (dont il s'agit d'une v0)

**Comment by kemenaran** [comment]
Pour moi cette issue se tient parce que : 

- On peut faire une v0 d'une page de garde qui n'aurait qu'un bouton "Commencer" – et pas de bouton "Retrouver mon brouillon".
- Ici on exprime un problème et un besoin spécifique (qui serait rendu possible par la page de garde, mais on peut imaginer d'autres solutions).

**Comment by fredZen** [comment]
@kemenaran si j’ai bien compris, cette issue porte maintenant le contenu de #1895 . Dans ce cas, il faudra bien penser **à communiquer** aux personnes listées dans #1985.

**Comment by LeSim** [comment]
+1000^1000

**Comment by mmagn** [comment]
engagement Direction des Achats de l’Etat (@CamilleGarrigue)

**Comment by kemenaran** [comment]
À communiquer (contenus précédemment dans #1895) :

`HS #4070`
`HS #4972`

**Comment by LeSim** [comment]
@kemenaran fix by #3293 ?

**Comment by kemenaran** [comment]
Yep ; j'envoie les "à communiquer"
