### ISSUE TITLE
Renommer le dépôt github en demarches-simplifiees

### ISSUE THREAD

**Issue by Flightan** [betagouv/tps#2866]
Le nom TPS n'est vraiment plus utilisé nulle-part à ma connaissance, rendre le nom du dépôt plus explicite améliorerai sa "découvrabilité".

**Comment by kemenaran** [comment]
Oui, tellement !

On est en train de mettre en place une nouvelle infra avec de nouveaux scripts de deploy, donc on va peut-être découper en "un problème à la fois" – mais dès que c'est fait je suis chaud.

**Comment by gregoirenovel** [comment]
Dup #1233. Notez au passage que le nom "demarches-simplifiees" n'existe pas, on parle de "demarches-simplifiees.fr".
