### ISSUE TITLE
ETQ superadmin je souhaite que les listes soient triées par dates (du plus récent au plus anciennes)

### ISSUE THREAD

**Issue by emsnytech** [betagouv/tps#2867]
Une dernière mise à jour a cassé le tri automatique des tableaux à l’ouverture.

**Comment by chaibax** [comment]
C'est embêtant en effet :(

**Comment by mmagn** [comment]
@emsnytech Tu parles des listes de dossier ? Et de quelle date ?

**Comment by chaibax** [comment]
La liste des admin n'est plus classé par id / date d'inscription .

Par défaut, on ca maintenant : 

![capture d ecran 2018-11-06 17 59 04](https://user-images.githubusercontent.com/3593868/48081205-cb5b6d00-e1ef-11e8-9431-a8d751ba0233.png)

C'est peut etre le cas pour d"autre liste du back super admin

**Comment by mmagn** [comment]
Oui je suis dessus je pense que c'est une maj d'une de nos dépendances.
