### ISSUE TITLE
ETQ Usager je veux voir les infos d'une démarche archivée dans la nouvelle UI

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#2878]
<img width="1164" alt="capture d ecran 2018-10-18 a 16 56 47" src="https://user-images.githubusercontent.com/179923/47163767-f6d8ef00-d2f6-11e8-9e70-84d1d6a5def3.png">

**Comment by kemenaran** [comment]
Quand y'en a plus, y'en a encore !

**Comment by gregoirenovel** [comment]
C'est pas la page de garde ?!

**Comment by kemenaran** [comment]
Non, c'est `/commencer/mon-lien-de-la-demarche` qui render `commencer/archived.html.haml`

Y'a pas de page de garde pour l'instant, on redirige toujours vers une autre URL – sauf pour cette page :)

**Comment by kemenaran** [comment]
@tchak dans 641831864ba1087887b017a533d81fa80a7e0091 tu as supprimé la page "Cette démarche a été archivée, il n'est plus possible de déposer un dossier dessus".

Ça me semble pas très clair de remplacer une page explicite par un vague "La démarche n'existe pas, ou elle a été archivée".

Quelle était la raison derrière ce changement ?

**Comment by tchak** [comment]
Nous avons supprimé les path sur les démarches archivées. On n'a plus l'information.

- Il nous a semblé que dire à l'utilisateur "lol, la démarche est archivée tu ne peux plus rien faire" n'était pas sur utile.
- Je comprends ton cas si l'utilisateur a déjà déposé un dossier sur cette procédure - on pourrait déréférencer le path sur le dossier au moment de la création, ce qui nous permettrait d'afficher ces infos pour les utilisateurs avec des dossiers déposés.

**Comment by kemenaran** [comment]
En tout cas la page n'existe plus. Je ferme.
