### ISSUE TITLE
Faciliter le lancement de l'appli après un fresh clone

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#288]
- [x] ajouter les binstubs au dépot (#289)
- [x] enlever france_connect.yml du gitignore et gérer les secrets avec des vars d'env
- [x] enlever fog_credentials.yml du gitignore  et gérer les secrets avec des vars d'env
- [x] enlever token.rb du gitignore  et gérer les secrets avec des vars d'env
- [x] enlever super_admin.rb du gitignore  et gérer les secrets avec des vars d'env
- [x] enlever mailjet.rb du gitignore  et gérer les secrets avec des vars d'env
- [ ] expliquer comment créer un administrateur et un super-administateur dans le README

**Comment by kemenaran** [comment]
J'ai l'impression qu'avec les seeds on est bon sur cette issue, non ?
