### ISSUE TITLE
Ne pas utiliser un cookie pour mémoriser la procédure que l’usager était en train de commencer avant de se connecter

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2920]
# À communiquer

Cas où la procédure est trop persistante`HS #7864`
et  cas où elle n’est pas assez persistante `HS #9187`

# 1. Procédure trop persistante
## Pour reproduire

1. se déconnecter de DS
2. visiter la page « commencer » d‘une procédure, mais ne pas aller plus loin, ne pas se connecter (par exemple https://www.demarches-simplifiees.fr/commencer/declaration-de-survol-drone-scenario-s3-pref06 )
3. aller sur la home (https://www.demarches-simplifiees.fr/)
4. cliquer sur le bouton « connexion » ou « se connecter »  (https://www.demarches-simplifiees.fr/users/sign_in )

## Comportement observé

on arrive sur la page de connexion de la procédure. Un brouillon est généré. Un mail de brouillon est envoyé.

Une instructrice nous remonte qu’elle tombe sur ce cas plusieurs fois par jour, et reçoit plusieurs mails de brouillon par jour.

## Comportement attendu

Quand je clique sur le bouton de « connexion » , j’arrive sur une page de connexion neutre, qui ne crée en particulier pas de brouillon. Comme si j’avais cliqué sur le bouton « fermer » de la la page de connexion de la procédure (https://www.demarches-simplifiees.fr/users/no_procedure)

# 2. Procédure pas assez persistante
## Pour reproduire

1. se déconnecter de ds
2. bloquer les cookies sur son navigateur, supprimer les cookies ds existants
3. aller sur la page « commencer » d‘une procédure (par exemple https://www.demarches-simplifiees.fr/commencer/declaration-de-survol-drone-scenario-s3-pref06 )
4. entrer ses identifiants

## Comportement observé

On arrive sur la liste des démarches

## Comportement attendu

On commence la procédure

**Comment by fredZen** [comment]
En fait ça ne va pas sauter avec la page de garde, le problème de fond est le problème dont tu me parlais il y a quelques jours : le fait que ce soit un cookie qui mémorise la page sur laquelle on allait avant d’être redirigé vers la page de connexion. Comme tu le disais, ça devrait plutôt être fait par un paramètre d’URL.

**Comment by kemenaran** [comment]
Pour le 1. (Démarche trop persistante), techniquement le problème va effectivement sauter avec la page de garde (#2225). Même si l'usager est redirigé sur une page `/commencer` alors que ça fait longtemps, un brouillon ne sera plus créé automatiquement en visitant la page de garde.

Pour le 2. (Démarche pas assez persistante), c'est un bug seulement dans le cas où le navigateur de l'usager bloque les cookies de DS. Mais dans ce cas l'usager pourra à peine se connecter. Est-ce que c'est vraiment un cas d'usage qu'on veut gérer ?

Sinon, sur la proposition technique, j'imagine que le choix d'utiliser des cookies (enfin, plus précisément la session) est pour gérer les cas où on pourrait rompre la chaine de paramètres d'URL (France Connect, lien d'activation dans l'email de confirmation, etc.) On sait si on peut éviter le cookie avec France Connect ?

**Comment by kemenaran** [comment]
(Pour info, un truc que j'envisage de faire, c'est de mettre un bandeau avec le nom et le logo de la démarche enregistrée dans la session (s'il y en a une) sur les pages de sign-in / sign-up.

Pour l'Usager, ça rend plus clair le fait qu'on a bien gardé le contexte de sa démarche ; c'est rassurant.

Et pour nous, ça nous permet de mieux déboguer les cas où la démarche est trop persistante, parce qu'on voit directement sur la page de sign-in / sign-up où est-ce qu'on va être redirigé ensuite.)

**Comment by fredZen** [comment]
> Pour le 1. (Démarche trop persistante), techniquement le problème va effectivement sauter avec la page de garde (#2225). Même si l'usager est redirigé sur une page `/commencer` alors que ça fait longtemps, un brouillon ne sera plus créé automatiquement en visitant la page de garde.

Du coup, ça ne règle qu’un des symptômes (la création de brouillon et l’envoi de mail), mais pas le problème, qui est que j’étais un gestionnaire, simplement en train de me connecter à mon outil de travail et que là ça persiste à me renvoyer vers une démarche que j’ai eu le malheur de visiter un jour.

**Comment by kemenaran** [comment]
Tout à fait 👍  C'était surtout une réflexion pour circonscrire le problème.

Du coup, pour ça, on peut peut-être voir comment purger plus agressivement la démarche visitée dans la session ?

**Comment by fredZen** [comment]
> (Pour info, un truc que j'envisage de faire, c'est de mettre un bandeau avec le nom et le logo de la démarche enregistrée dans la session (s'il y en a une) sur les pages de sign-in / sign-up.

Pour la page de sign in, ça me semble assez clair déjà aujourd’hui :-)

![screenshot from 2018-11-26 11-01-25](https://user-images.githubusercontent.com/356570/49007039-ca708800-f16a-11e8-9ab1-a5dc0b5f383f.png)

Mais effectivement, pour la page de sign up on perd la contexte visuel

![screenshot from 2018-11-26 11-01-45](https://user-images.githubusercontent.com/356570/49007079-dceac180-f16a-11e8-8abb-352c72f53f13.png)

**Comment by fredZen** [comment]
> Mais dans ce cas l'usager pourra à peine se connecter. Est-ce que c'est vraiment un cas d'usage qu'on veut gérer ?

Oui, pas faux... J’ai rencontré plusieurs cas récemment que je n’arrive pas pour l’instant à m’expliquer autrement que par « le browser rejette nos cookies »... Et avec le surcroît d’attention que les cookies ont reçu depuis le RGPD, ça m’a paru crédible que des utilisateurs fassent ça. Mais comme tu le fais remarquer, sans cookies DS ne marche juste pas du tout (je viens d’essayer). Du coup ça falsifie mon hypothèse. Je ne suis pas loin de fermer cette issue.

**Comment by kemenaran** [comment]
Aujourd'hui, avec la page de garde mise en prod :

- la création de brouillon n'est plus automatique (ouf)
- on affiche clairement le contexte de la démarche sur la page de sign-in ou de sign-up

Reste donc le use-case "Et si le navigateur bloque entièrement les cookies ?" Mais dans ce cas j'ai l'impression qu'on a d'autres soucis :)

À mon avis la question de savoir comment on stocke le contexte de la démarche se pose toujours, mais ça devient plus une question technique. Je serais d'avis de fermer cette issue, et d'ouvrir une issue technique au besoin. @fredZen ça t'irait ?

**Comment by fredZen** [comment]
:+1:
