### ISSUE TITLE
L'application plante lorsque les images (logo, signatures) ne sont pas synchro

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#2921]
Exemple :

le logo de la procédure pour une raison inconnu est présent en base mais pas sur ovh, impossible de modifier le logo

Investiguer également sur les bug sentry liées aux images des attestations.

**Comment by fredZen** [comment]
Est-ce qu’on garde cette issue pour bosser sur la robustesse, ou on la ferme maintenant qu’on a traité #2697 ?

**Comment by mmagn** [comment]
Tu entends quoi par bosser sur la robustesse ?
Moi j'aurai fermé l'issue je pense qu'on aura plus de pb.

**Comment by fredZen** [comment]
Je note que l'issue dit « quand ça se désynchronise, alors ça plante ». Techniquement, ça reste toujours vrai je pense (?), sauf qu’a priori ça ne devrait plus se désynchroniser. D'où ma légère réticence à fermer une issue qui en plus n'était pas à moi (si elle était à moi je l'aurais déjà fermée, et je pense que c'est ce que je vais faire. @sim la rouvrira si je me suis gourré)
