### ISSUE TITLE
ETQ Usager je veux avoir une idée plus pertinente du délai de traitement de mon dossier

### ISSUE THREAD

**Issue by chaibax** [betagouv/tps#2970]
Le texte du résumé induit en erreur. L'usager confond notre estimation du délai de traitement et un engagement de la part de l'administration. 

Par ailleurs, le message laisse croire aussi qu'un dossier en construction est immédiatement vérifié (suivi / instruit) par un instructeur. 

<img width="1280" alt="capture d ecran 2018-11-08 10 39 05" src="https://user-images.githubusercontent.com/3593868/48208805-ebb43480-e373-11e8-9434-4238b04bf031.png">

Message de recu :  

> La mise en place du message ci-dessous génère beaucoup d’appels téléphoniques de la part de nos usagers qui s’inquiètent de ne pas voir leur dossier traité en 7 jours.
> 
> J’ai bien compris qu’il s’agissait d’un message générique et non pas d’un engagement de délai de notre part mais les usagers font une toute autre interprétation du message.
> 
> Par ailleurs, concernant la procédure XXX, les instructeurs commencent à vérifier le dossier au moment où ils le passent en instruction.

**Comment by kemenaran** [comment]
Intéressant. Pour le passage en construction, je me demande si leur manière de traiter les dossiers est particulière au sein de DS.

Pour le **temps moyen**, c'est vrai que ça se questionne. Deux pistes :

- Indiquer quelque chose de plus vague : "Habituellement les dossiers de cette démarche sont traités dans les 7 jours."
- Changer le chiffre : mettre le 8ème ou 9ème percentile au lieu du temps moyen. (90% des dossiers sont traités dans les XX jours).

**Comment by fredZen** [comment]
Mettre un percentile me semble de toutes façons une bonne idée, les moyennes sont assez trompeuses.

**Comment by gregoirenovel** [comment]
> les instructeurs commencent à vérifier le dossier au moment où ils le passent en instruction

Ça c'est un problème de leur côté pour moi

**Comment by chaibax** [comment]
Je remplacerais le texte "Le temps moyen de vérification pour cette démarche est de 7 jours"   

"Le délai constaté entre le dépôt d'un dossier et son instruction est de X jours/semaine/jours en moyenne. Ce délai n'est pas un engagement de temps de traitement, mais une statistique fournie à titre indicatif. "

**Comment by gregoirenovel** [comment]
Ça me semble long et complexe. On peut pas juste nuancer ?

> Le temps moyen de vérification pour cette démarche est d'au moins 7 jours

**Comment by kemenaran** [comment]
Je regarde pour faire du percentile.

**Comment by chaibax** [comment]
Il y a un problème de compréhension : l'usager pense que c'est un engagement de délai de traitement. Alors que ca ne l'est tout simplement pas.

**Comment by gregoirenovel** [comment]
Oui j'ai bien compris, mais je ne vois où on peut déceler de l'engagement dans ma suggestion, à part sur une borne minimum ce qui ne me semble pas être pour moi un engagement contraignement, au contraire. Après on peut prendre les pincettes à coup de "Selon nos statistiques".

**Comment by gregoirenovel** [comment]
(dans tous les cas je trouve qu'on s'emballe pas mal pour un problème assez mineur, remonté pour le moment par *1* admin)
