### ISSUE TITLE
Forcer la redirection vers https

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#3039]
On peut aller sur http://demarches-simplifiees.fr sans problème, forcer la redirection vers le https

Pourtant on a bien `config.force_ssl = true` dans `production.rb`

**Comment by mmagn** [comment]
Personnellement je suis automatiquement redirigé en https...
Mais je ne passe pas sur le www.

**Comment by tchak** [comment]
done

**Comment by mmagn** [comment]
Pour info le problème était du au LB, il laissait le client lui parler en http mais parlait en https aux machines derrières.
