### ISSUE TITLE
Le nouveau Sentry n'envoie pas d'emails à Grégoire

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#3042]

**Comment by fredZen** [comment]
Moi j’en reçois régulièrement

**Comment by gregoirenovel** [comment]
C'est probablement parce que j'avais pas de compte... (quel champion je fais)

Je ferme dès que je reçois un email

**Comment by mmagn** [comment]
C'est bon non ? Tu as au moins confirmé ton email
