### ISSUE TITLE
Refuser la saisie d'autre chose qu'un numéro de téléphone dans le champ téléphone

### ISSUE THREAD

**Issue by chaibax** [betagouv/tps#3048]
Actuellement, un usager peut saisir n'importe quoi dans le champ de type "téléphone" d'une démarche.

- Il n'y pas de contrôle, et l'usager peut saisir autre chose qu'un numéro de téléphone.
- Cela induit en erreur nos administrateurs qui pensent qu'il y a un test de format. 

Si on peut renter une adresse email à la place d’un tel, autant viré le champs téléphone du générateur de formulaire (ok c’est plus facile a saisir sur mobile ...) dans cas là .

On pourrait fixer un patern **très large** (pas de lettre, que des chiffres espace, + - # etc) . Là il y a zéro test... 

Ex de regexp pas mal : https://regex101.com/r/GmDIbg/2 . C'est pas ce qui manque. 

Si c’est un champ pour des numéros de téléphone étrangers, l’admin peut toujours mettre un champ texte . Comme pour le champ adresse.  Je pense que si on a un format large, il n'y a pas de raison que ca ne marche pas. 

# à communiquer

`HS 9456`

**Comment by gregoirenovel** [comment]
Y'a un à communiquer ?

> Si c’est un champ pour des numéros de téléphone étrangers, l’admin peut toujours mettre un champ texte

Ça c'est impossible à communiquer dans l'interface simplement, ça complique les affaires, je suis contre. On a un champ téléphone c'est un champ téléphone. Notre champ email c'est pas un champ "email yahoo et gmail seulement, les autres faut faire un champ texte".

> Comme pour le champ adresse

Le champ adresse est libre, on fait juste de la suggestion.

>  Je pense que si on a un format large

OK si tu assures qu'il marche avec tous les formats imaginables, les formats américains usuels sont déjà bien rigolos : https://stackoverflow.com/questions/123559/a-comprehensive-regex-for-phone-number-validation

**Comment by kemenaran** [comment]
> Si c’est un champ pour des numéros de téléphone étrangers, l’admin peut toujours mettre un champ texte.

L'admin ne pensera jamais à ça. Ce sont les usagers qui constateront que ça ne fonctionne pas, et qui seront bien embêtés.

> Je pense que si on a un format large


Le mieux est d'avoir la validation la plus laxiste possible, oui.

Sur les aides de l'Anah j'avais mis "Tout est permis, mais il faut au moins 8 chiffres à un moment ou à un autre". Ça avait le mérite de couvrir les +33, les tirets, les parenthèses, et tout :) Et d'éviter les erreurs les plus courantes.

Ça ne couvre pas certains n° américains à 7 chiffres – mais avec l'indicatif de pays normalement on arrive bien à 8.

**Comment by chaibax** [comment]
> Sur les aides de l'Anah j'avais mis "Tout est permis, mais il faut au moins 8 chiffres à un moment ou à un autre". Ça avait le mérite de couvrir les +33, les tirets, les parenthèses, et tout :) Et d'éviter les erreurs les plus courantes.

Si en plus on acceptait pas les lettres de l'alphabets ni par exemple @ ! ?  . Ca serait pas mal non ?

**Comment by mmagn** [comment]
@pengfeidong regarde

**Comment by Benjamin-Doberset** [comment]
HS : # 10048
a communiquer
