### ISSUE TITLE
ETQ Opérateur je veux pouvoir configurer tous les urls de l'api dans ENV

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/tps#3056]
Bonjour, 
Pour rendre les urls de l'api en dehors de code et le mettre dans les ENV variables, je voudrais modifier le fichier 'url.rb' comme suivant:

`API_ADRESSE_URL = ENV.fetch('API_ADRESSE_URL', "https://api-adresse.data.gouv.fr")`
`API_CARTO_URL = ENV.fetch('API_CARTO_URL', "https://apicarto.sgmap.fr")`
`API_ENTREPRISE_URL = ENV.fetch('API_ENTREPRISE_URL', "https://entreprise.api.gouv.fr/v2")`
`API_GEO_URL = ENV.fetch('API_GEO_URL', "https://geo.api.gouv.fr")`
`API_GEO_SANDBOX_URL = ENV.fetch('API_GEO_SANDBOX_URL', "https://sandbox.geo.api.gouv.fr")`
`HELPSCOUT_API_URL = ENV.fetch('HELPSCOUT_API_URL', "https://api.helpscout.net/v2")`
`PIPEDRIVE_API_URL = ENV.fetch('PIPEDRIVE_API_URL', "https://api.pipedrive.com/v1")`

**Comment by mmagn** [comment]
C'est ok pour moi.

**Comment by kemenaran** [comment]
Ça me semble raisonnable sur le principe : des valeurs par défaut pour les URLs (parce qu'elles ne font que rarement changer, et qu'on a peut-être pas besoin de mettre à jour toutes les variables d'env pour ça) ; mais les rendre overridable quand même.
