### ISSUE TITLE
ETQ Administrateur je veux pouvoir administrer facilement les instructeurs de la démarche

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#3076]
La recherche est fastidieuse sur une démarche avec +200 instructeurs.
HS 9247

**Comment by gregoirenovel** [comment]
Est-ce que c'est pas du wontfix attend le routage ?

**Comment by mmagn** [comment]
C'est sur qu'on ne va pas changer l'UI avant le routage, mais c'était pour garder la volumétrie en tête...
En vrai on peut la fermer...
