### ISSUE TITLE
ETQ Admin si je transfère une démarche le service doit être cloné

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#3192]

**Comment by gregoirenovel** [comment]
On veut pas qu'il soit blank ?

**Comment by mmagn** [comment]
En fait dans le comportement actuel, la nouvelle démarche garde la référence au service du premier.
L'administrateur de la nouvelle démarche n'a pas la possibilité de modifier les informations du service, et si des modifications sont effectuées sur le service depuis la démarche originelle elle sont répercutées sur la démarche transférée.
Cette issue vise à corriger ce comportement, c'est vrai que le titre n'était pas très clair.

Et d'après les données, le cas d'un transfert depuis un membre de l'équipe DS est plutôt minoritaire.

**Comment by gregoirenovel** [comment]
OK, ce que je veux souligner c'est que j'ai peur que ça ne soit pas suffisant (donc ce qui va suivre est probablement pour une autre PR :) ) : quand on clone depuis la bilbiothèque, on va alors avoir un service cloné, au moins on peut le modifier, en effet ; mais ma crainte c'est que certains ne vérifient pas ce service avant publication et publient avec un service autre que le leur. D'où l'idée de ne rien transférer quoi que ce soit qu itouche au service lors du clone d'une démarche.

**Comment by mmagn** [comment]
Non car si tu clones depuis la bibliothèque on met le service à nil (comportement actuel), là je trouve que c'est normal.
