### ISSUE TITLE
Augmenter la taille de la pagination dans l'API

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#320]
Dégager le paramètres `page`

**Comment by gregoirenovel** [comment]
Communiquer à : France Agrimer

**Comment by mmagn** [comment]
On parle de cet endpoint ? https://tps.apientreprise.fr/docs/1.0/dossiers/index.html

**Comment by mmagn** [comment]
Je ne comprends pas en quoi c'est un bug de paginer une API ?

**Comment by gregoirenovel** [comment]
À mon avis il faut proposer les 2 modes, visiblement la pagination embete certains utilisateurs de l'API

**Comment by mmagn** [comment]
Ce qui est sur c'est que c'est chiant que la limite soit à 12, on peut la monter à 100 ou 500, mais c'est compliqué de la virer totalement. Ca protège des réponses de plusieurs Mo si une procédure avait des milliers de dossiers.

**Comment by mmagn** [comment]
Je viens de tester on est large, 100 dossier ~> 10Ko de réponse.

**Comment by fredZen** [comment]
+1 avec « c'est compliqué de la virer totalement », AMA I'm vaut mieux laisser une limite garde-fou, quitte à la mettre à 1000 ou 10 000

**Comment by gregoirenovel** [comment]
👍 pour la mettre à 1000

**Comment by LeSim** [comment]
:+1: juste pour dire que moi aussi, je peux mettre des commentaires tard un lundi ...

**Comment by gregoirenovel** [comment]
Done with #1642
