### ISSUE TITLE
ETQ usager, quand je soumets mon dossier je me demande parfois ce qu'il se passe

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#3227]
Si formulaire avec des champ PJ en milieu de formulaire, que j'ajoute des PJ un peu grosses, que soumets, le bouton se grise, j'ai l'impresion que rien ne se passe (alors qu'en fait ce qu'il se passe c'est l'upload des PJ), et je suis perdu.

**Comment by kemenaran** [comment]
J'avoue, un indicateur de chargement ça serait top.

En quick-win, on pourrait juste afficher "Envoi des pièces jointes en cours…", ou animer le bouton grisé…

**Comment by kemenaran** [comment]
Retour utilisateur : `#10327`

**Comment by kemenaran** [comment]
Y'a une barre de chargement pour les PJ, codée et tout (dans progress.js), mais elle est cassée…
