### ISSUE TITLE
ETQ dev, je ne recoit pas de mail alors qu'il y a bien une nouvelle erreur dans Sentry

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#3231]
Suite à une validation de demande de compte qui plante

<img width="1279" alt="screen shot 2018-12-26 at 12 22 08" src="https://user-images.githubusercontent.com/1333173/50444468-ecdff780-0908-11e9-8e87-f6d04773e367.png">

J'ai bien une erreur Sentry

<img width="1037" alt="screen shot 2018-12-26 at 12 29 49" src="https://user-images.githubusercontent.com/1333173/50444649-f4ec6700-0909-11e9-9f6d-f740703a9f4a.png">

Mais pas d'email correspondant

**Comment by kemenaran** [comment]
@gregoirenovel Tu ne disais pas que c'était suite à une erreur de paramétrage de ton côté ?

**Comment by gregoirenovel** [comment]
Hmm il me semble avoir la conf par défaut, j'ai eu un autre problème du à ma config il y a quelques semaines mais il est résolu et était différent de celui-ci il me semble
