### ISSUE TITLE
Convertir tous les emails en HAML

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#324]

**Comment by kemenaran** [comment]
Aujourd'hui il ne reste qu'un email en TXT plutôt qu'en HAML. J'ai l'impression qu'on s'en occupera le jour où on voudra le modifier.

On ferme ?

**Comment by gregoirenovel** [comment]
> J'ai l'impression qu'on s'en occupera le jour où on voudra le modifier.

Pas sur, car ça sera p-e hors-scope. Je propose donc de laisser ouvert.
