### ISSUE TITLE
ETQ usager, je souhaite que les statistique de satisfaction soient à jour

### ISSUE THREAD

**Issue by emsnytech** [betagouv/tps#3242]
Les statistiques de satisfaction ne sont plus à jour depuis le 15 décembre.
Le pb, c'est qu'elles sont figées sur des statistiques qui ne sont pas très bonnes.

**Comment by fredZen** [comment]
Aujourd’hui, les stats semblent avoir bougé par rapport à ce que tu voyais il y a deux jours (nous avons maintenant un point de données pour le 22 décembre), mais je pense aussi que nous avons des problèmes avec les statistiques de satisfaction.

![capture d ecran de 2018-12-31 19-42-29](https://user-images.githubusercontent.com/356570/50565935-51012200-0d34-11e9-9b66-df9a13425181.png)

Pour mémoire, avec notre première version des statistiques de satisfaction, le dernier point de données (le plus à droite) n’était pas statbles, car il était calculé sur la semaine en cours, et s‘enrichissait donc au cours des réponses données par les utilisateurs. Cela a été considéré comme un problème par certains membres de l‘équipe, qui ont donc fait le choix de ne plus afficher les données pour la semaine en cours.

Je fais l’hypothèse (à vérifier) que le point libellé « 22 décembre » agrège en fait les données du 22 au 29 décembre (inclus ou exclus ? Je ne sais pas), et a été publié le 29 décembre au soir (puisque tu ne le voyais pas vers 15h).

Cependant : 
1. un petit texte explicatif ne serait pas de trop pour aider le lecteur à comprendre ce qu’il voit sur le graphe
2. l’objectif de stabilité des données ne me semble pas avoir été atteint (de mémoire, le chiffre de satisfaction pour le 15 décembre était moins bon qu’il ne l’est sur l’affichage actuel)

**Comment by fredZen** [comment]
Nouveau point de données : dans la screenshot ci-dessous, le point du 24 décembre ne semble pas cohérent avec ce qu’on avait en dernier point sur le screenshot précédent (point sans libellé à droite du 17 décembre)

<img width="537" alt="capture d ecran 2019-01-09 a 11 29 03" src="https://user-images.githubusercontent.com/356570/50894107-af986100-1402-11e9-9ec2-c1b96df21d0a.png">
