### ISSUE TITLE
[RFC] ETQ usager, la notion de "en construction" n'est pas claire

### ISSUE THREAD

**Issue by chaibax** [betagouv/tps#3246]
On ne comprend pas bien que le dossier est bien envoyé (à moins de lire ses emails) et pourtant encore modifiable. C'est dommage, car c'est une vraie valeur ajoutée de DS par rapport à d'autre solution de permettre de modifier un dossier soumis à l'administration tant que celui-ci n'est pas instruit. 

Je propose : 'Envoyé et encore modifiable' avec un texte d'aide explicite

**Comment by chaibax** [comment]
Je me demande si "En instruction" est suffisamment clair. Par ailleurs, un dossier soumis/envoyé est plutôt "en attente d'instruction". 

Ne faudrait-il pas **le rassurer un maximum** sur la bonne soumission de son dossier ?

**Comment by emsnytech** [comment]
à voir avec #3245

ATTENTION terme déjà largement compris par beaucoup d'usager... prudence aux changements de manière unilatérale de notre côté. On a eu qques pb la dernière fois que l'on a fait cela.

**Comment by chaibax** [comment]
Merci de ton retour @emsnytech. On est ici pour en discuter justement. On ne fera pas de changement unilatérale. 

Cependant, même dans ton issue #3245 tu parles de dossier déposé et pas en construction...

**Comment by emsnytech** [comment]
depuis le début, nous avons en effet  créé un statu de dossier qui n'existe pas en droit, "en construction", mais pas forcément réceptionné... C'est le numérique qui permet en effet cette interactivité, qui n'existant pas avec le papier. D'où les questions légitimes que nous nous posons...

**Comment by chaibax** [comment]
C'est pour ca que je pense que ce n'est pas claire a comprendre pour l'usager.
