### ISSUE TITLE
Régler le problème de chargement de css au changement de pages entre les différents designs

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#328]
Pour reproduire :
- Aller sur la home
- Cliquer sur une page avec l'ancien design, ex : Statistiques
- Cliquer sur la Marianne pour revenir sur la home
 => Le design est cassé sur la home

**Comment by kemenaran** [comment]
Ça a l'air corrigé, plus jamais vu le problème depuis longtemps.
