### ISSUE TITLE
Sur l'interface admin, modifier la nomenclature du type d'organisme de la section service

### ISSUE THREAD

**Issue by CamilleGarrigue** [betagouv/tps#3315]
Tout remplacer par : 
- Administration centrale
- Service déconcentré de l'Etat
- Opérateur d'Etat
- Collectivité territoriale
- Etablissement d'enseignement
- Association
- Autre

**Comment by kemenaran** [comment]
@CamilleGarrigue @Benjamin-Doberset est-ce que vous pouvez nous donner les migrations des anciennes valeurs vers les nouvelles ?

**Comment by CamilleGarrigue** [comment]
Voici la correspondance en partant de l'ancienne nomenclature : 
- administration centrale --> Administration centrale
- association --> Association
- commune --> Collectivité territoriale
- département --> Collectivités territoriale
- établissement d'enseignement --> Etablissements d'enseignement
- préfecture --> Service déconcentré de l'Etat
- région --> Collectivité territoriale
- autre --> Autre

En conformité avec la nomenclature attendue (présentée dans le commentaire au dessus) il faut aussi ajouter "Opérateur d'Etat".
