### ISSUE TITLE
Suppression d’un dossier : incohérence entre le contôleur et la vue

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#3354]
La vue ne montre le bouton de suppression que pour les brouillons

https://github.com/betagouv/tps/blob/9728721a1253a0c80aec626e8917bd716b147cc9/app/views/new_user/dossiers/index.html.haml#L54

mais le contrôleur autorise la suppression tant que l’instruction n’a pas commencé (donc aussi pour les dossiers en construction)

https://github.com/betagouv/tps/blob/9728721a1253a0c80aec626e8917bd716b147cc9/app/controllers/new_user/dossiers_controller.rb#L191

**Comment by kemenaran** [comment]
De fait j'ai l'impression que ça se tient de pouvoir supprimer un dossier en construction (tant qu'un instructeur ne l'a pas touché, donc).

Ça vous va si on modifie la vue pour autoriser la suppression de dossiers en construction ?

**Comment by fredZen** [comment]
@kemenaran moi ça me va bien, et ça semble cohérent avec ce qu’on nous demande en support

**Comment by fredZen** [comment]
à communiquer `#11507`

**Comment by kemenaran** [comment]
C'était essentiellement l'issue décrite dans #2687
