### ISSUE TITLE
ETQ Usager je veux obtenir une réponse à mon problème dans le formulaire de contact

### ISSUE THREAD

**Issue by chaibax** [betagouv/tps#3365]
L'idée est de fournir l'information recherché avant la soumission du formulaire de contact, en particulier pour :  

  - J'ai un problème lors du remplissage de mon dossier
  - Je ne trouve pas la démarche que je veux faire
  - J'ai une question sur l'instruction de mon dossier

**Comment by kemenaran** [comment]
Grave, tellement ! 🙌 

Comme implémentation, j'imaginais un petit encadré de texte juste entre le menu déroulant de choix du sujet et le formulaire de contact.

On peut voir en quelques mots si ce n'est pas un problème courant – et rediriger vers la FAQ avec un lien.

Quelque chose du genre 

```
"Je ne trouve pas la démarche que je veux faire"

(i) Avez-vous consulté la [liste complète des démarches disponibles] ?
Sinon, vous pouvez demander à l'administration un [lien direct]
(FAQ "qu'est-ce qu'un lien direct") vers la bonne démarche.
```

**Comment by chaibax** [comment]
@philemon95 propose **en plus** de cacher le champs messages du formulaire (avec le bouton envoyé) quand ont peut donner de suite la réponse : 

* J'ai un problème lors du remplissage de mon dossier
* Je ne trouve pas la démarche que je veux faire
* J'ai une question sur l'instruction de mon dossier

**Comment by kemenaran** [comment]
_For the record_, je ne suis vraiment pas chaud à l'idée d'empêcher des usagers de nous contacter :

- C'est hostile à l'usager (au lieu de résoudre son problème) ;
- L'usager va juste sélectionner une autre catégorie de problèmes pour pouvoir avoir accès au formulaire de contact ; et ça fera des messages mal catégorisés.

J'ai l'impression qu'on a déjà pas mal de pistes pour faire en sorte que l'usager trouve mieux ses réponses lui-même (bouton "Aide" vers la FAQ, aide contextuelle dans cette issue). On peut déjà voir comment ces pistes fonctionnent, non ?
