### ISSUE TITLE
ETQ Super-admin je veux savoir quel est le dossier qui pose problème 

### ISSUE THREAD

**Issue by philemon95** [betagouv/tps#3369]
impossible sur HS pour l'instant d'avoir un tag du numéro de dossier même quand renseigné (autofill ou par l'usager)

**Comment by kemenaran** [comment]
Mmm, je crois que quelque chose m'échappe… Le besoin ça serait de pouvoir cliquer sur un numéro de dossier mentionné dans HelpScout, et de tomber directement sur le bon dossier dans le Manager ?

**Comment by philemon95** [comment]
Actuellement dans le formulaire de contact, l'usager peut saisir son dossier, ou il me semble qu'il peut également être autofillé. Il me semble que cette donnée n'apparaît pas ensuite sur HS.

**Comment by tchak** [comment]
Elle apparait en haut de l'échange normalement

**Comment by chaibax** [comment]
C'est une erreur dans le controleur, j'ai corrigé
