### ISSUE TITLE
[RFC] ETQ USAGER je ne veux plus avoir le bouton "commencer une nouvelle démarche"

### ISSUE THREAD

**Issue by philemon95** [betagouv/tps#3371]
Le bouton "commencer une nouvelle démarche" génère du support facilement évitable
1. L'usager ne trouve pas sa démarche
2. L'usager a rempli la mauvaise démarche en cliquant sur la première qu'il a trouvée.

Je pense que supprimer ce bouton n'enlèverait pas d'avantages à l'usager mais limiterait ses désagréments et diminuerait le support

**Comment by kemenaran** [comment]
Mmm, intéressant.

L'idée c'était de commencer à faire un système qui permette aux usagers de trouver eux-même leur démarche. Mais peut-être que le moteur de recherche v0 n'est pas encore assez bon pour être une amélioration nette par rapport à "pas de moteur de recherche".

- Tu as des exemples de conversations au support de gens perdus par ce bouton ?
- Tu crois qu'on pourrait facilement améliorer la page de recherche de démarche (plutôt que de désactiver le bouton), ou ça te semble compliqué ?

Si ça te semble problématique, moi ça me va bien de le masquer pour l'instant (en attendant qu'on améliore le moteur de recherche).

**Comment by philemon95** [comment]
ce problème génère notamment du support sur les démarches "départementalisées", par exemple si tu recherches la démarche pour ton numéro NEPH, tu vas cliquer sur la première démarche qui vient, sans faire attention au département, ce qui crée du travail en plus pour les instructeurs (qui ne comprennent pas bien d'où vient le problème et pourquoi les gens tombent sur leurs démarches) et de notre côté avec des gens qui ne comprennent pas pourquoi leur dossier est refusé.
Pour l'instant, la solution la plus satisfaisante est celle mise en place pour les[ permis de conduire](https://doc.demarches-simplifiees.fr/listes-des-demarches/demarches-relatives-au-permis-de-conduire) et pour la [DETR](https://doc.demarches-simplifiees.fr/listes-des-demarches/demarches-relatives-a-la-detr) avec la liste exhaustive des  démarches existantes, mais c'est difficilement scalable. En outre, le moteur de recherche n'est pas forcément l'outil idoine, pour revenir à l'exemple des démarchs départementalisées, car l'enjeu, une fois que j'ai tapé "NEPH", n'est pas de trouver les démarches NEPH mais de savoir laquelle est la bonne.

**Comment by philemon95** [comment]
pour illustrer problème, le HS # 12041 qu'on vient de recvoir, source de perte de temps pour les usagers (qui attendent de se voir refuser leur dossier, parfois après plusieurs semaines) avant d'entamer la démarche pour laquelle ils sont éligibles.

**Comment by chaibax** [comment]
Je suis d'accord pour masquer en attendant de trouver une meilleur solution

**Comment by chaibax** [comment]
J'ai fait un PR pour cacher le bouton
