### ISSUE TITLE
ETQ Administrateur je veux qu'un usager puisse saisir uniquement un point sur la carte

### ISSUE THREAD

**Issue by philemon95** [betagouv/tps#3393]
Actuellement, seule une zone est possible (cadastrale, politique de la ville etc...)
Ici, l'idée serait de rajouter pour l'administrateur l'option "point unique" pour connaître la localisation d'équipements (défibrillateurs, bornes incendies ou que sais-je)

`HS #12007`

**Comment by emsnytech** [comment]
A rajouter au vaste programme amélioration cartographique... il faut un dev la dessus pendant six mois ... On va finir par en trouver un ! car on peut aller très loin..;

**Comment by kemenaran** [comment]
Par ailleurs, un développement intéressant serait d'extraire l'outil d'édition cartographique de DS.

On aurait un outil externe qui serait améliorable indépendamment de DS, et qui remonterait les informations entrées sur les dossiers. Ça permettrait de développer l'interface d'édition carto sans dévier de la mission fondamentale de DS :)

**Comment by kemenaran** [comment]
Doublon de #3393. J'ai migré la notification client, et je ferme cette issue
