### ISSUE TITLE
ETQ Usager, je veux pouvoir supprimer une pièce jointe de mon brouillon

### ISSUE THREAD

**Issue by philemon95** [betagouv/tps#3398]
Actuellement, la seule possibilité est de remplacer la pièce jointe par une autre pièce jointe, impossible de "vider" un champ PJ.
cf pour illustration HS #12040

**Comment by kemenaran** [comment]
Normalement c'est le cas uniquement sur les anciennes pièces jointes, qui vont être rapidement migrées vers les nouvelles.

Mais en attendant c'est un souci, oui.
