### ISSUE TITLE
Décompiler une application

### ISSUE THREAD

**Issue by baxther** [betagouv/tps#3399]
Bonjour à tous!
jai developper un projet avec ionic mais je n'ai jamais pris la peine de le sauvegarder!! Du coup jai tout perdu lorsqu'on m'a volé ma machine. Il me reste seulement l'apk que j'avais envoyé par mail à un pote! Je voudrais savoir si je peux retrouver le code source de mon application. Je tiens encore à le préciser le projet à été developper avec ionic

**Comment by fredZen** [comment]
Bonjour

toutes mes condoléances. Je ne sais pas si vous avez travaillé des jours, des semaines ou des mois sur votre projet, mais je peux imaginer le sentiment de perte.

Ce n’est pas vraiment le bon endroit pour en parler ici (notre rôle est de développer un outil web pour l’État français), nous ne sommes pas forcément les plus compétents pour répondre non plus (notre stack technologique est Ruby / Rails, pas JavaScript / Ionic), mais j’ai quand-même envie de répondre de mon mieux par solidarité entre développeurs.

Les fichiers apk sont des fichiers zip un peu particuliers, mais des fichiers zip malgré tout. Si tu renommes ton fichier pour lui donner une extension .zip, tu vas pouvoir l’ouvrir, et il y a des chances que tu trouves des choses intéressantes dedans (par exemple des images, des fichiers xml).

Cela dit, je ne voudrais pas te donner trop d’espoir pour le code source en lui même : tu ne trouveras très certainement pas tes fichiers JavaScript (ou TypeScript) originaux dans l’apk, mais du JavaScript minifié.

Ma recommandation serait de réécrire le code en partant d’une page blanche. C’est effrayant comme perspective, mais pour l’avoir déjà fait, j’ai découvert que le logiciel s’écrit beaucoup plus vite la deuxième fois que la première.

Une bonne partie du temps qu’on croit passer à écrire du logiciel, on est en fait surtout en train d’apprendre. Apprendre des nouveaux points techniques, apprendre comment notre logiciel va être utilisé, apprendre comment formaliser telle notion de nos utilisateurs dans une construction technique élégante.

Quand on écrit le même logiciel, on peut profiter de ce capital d’apprentissage accumulé. Non seulement le logiciel s’écrit plus vite, mais le résultat est souvent plus élégant que la première fois.

Je te souhaite bon courage dans ton entreprise, et t’adresse tous mes vœux de réussite.
