### ISSUE TITLE
ETQ Usager, je peux voir la surface des parcelles cadastrales sélectionnées

### ISSUE THREAD

**Issue by Keirua** [betagouv/tps#3403]
Les parcelles cadastrales ont plein de métadonnées associées, dont une surface qui n'est pas affichée à l'utilisateur.
On se dit qu'il est intéressant d'afficher cet information à l'utilisateur, par exemple ainsi:
![parcelles-cadastrales](https://user-images.githubusercontent.com/1223316/52481443-d509bd80-2bae-11e9-86e3-5ed0d8f74d73.png)

C'est utile pour [notre projet](https://beta.gouv.fr/startups/permis-de-construire-facile.html), mais on se dit que ça peut servir pour tout le monde.

Il faudrait:
 - vérifier que l'API source possède bien l'info
 - modifier le retour de l'API POST /champs/{id}/carte pour qu'elle déclenche l'affichage

Si cette fonctionnalité vous intéresse, je peux m'en occuper.

**Comment by emsnytech** [comment]
ET une deuxième PR !!!!

**Comment by kemenaran** [comment]
Ça me semble intéressant à récupérer et à afficher comme métadonnées, oui 👍 

Si ça vous dit de le faire, on est preneur (à la fois pour le code, et pour itérer sur la simplicité de l'installation du projet en local et du processus de contribution).
