### ISSUE TITLE
ETQ Usager ou Instructeur, je peux connaitre la date de dépot du dossier

### ISSUE THREAD

**Issue by Keirua** [betagouv/tps#3404]
Dans tout un tas de démarches (dont le permis de construire), la date de dépot conditionne un certain nombre de choses. Cela semble pertinent d'afficher cette information à l'utilisateur.

Actuellement, le seul moyen que j'ai trouvé d'avoir cette info, c'est dans la messagerie, via la date du mail:

![image](https://user-images.githubusercontent.com/1223316/52483340-f6b97380-2bb3-11e9-85ba-af93db23c4f1.png)

On peut faire mieux que ça ;) Par exemple en l'affichan à côté du numéro de dossier

![date-de-depot](https://user-images.githubusercontent.com/1223316/52483018-17cd9480-2bb3-11e9-9eeb-58387530be70.png)

Notre cas d'usage: de la date de dépot découle une date de validation tacite. Concrètement on a pas les moyens de gérer cette date de tacite automatiquement (les règles métiers concernant cette durée sont complexes, pas claires, elles dépendent d'informations que nous ne pouvons pas avoir facilement (ex: le projet est-il en zone ABF?). Par ailleurs, des changements de statut du dossier peuvent rajouter du temps au compteur.
On se dit qu'un moindre mal serait d'indiquer à l'utilisateur (usager ET instructeur) quand son dossier a été déposé.

**Comment by fredZen** [comment]
Merci pour ton retour, ça va nous aider à améliorer le produit.

Pour information (ça peut peut-être vous dépanner en attendant mieux), l’information est disponible sur la vue synthétique des dossier, ce qui permet par exemple de trier par date de dépôt.

![image](https://user-images.githubusercontent.com/356570/52495215-50c83200-2bd0-11e9-828c-0d832a271d7a.png)

Mais oui, je vois bien l’utilité d’avoir l’information dans la vue détaillée d’un dossier

**Comment by emsnytech** [comment]
Tout à fait OK, on a vu cela ensemble en effet !

**Comment by kemenaran** [comment]
@keirua Ça m'a l'air raisonnable d'afficher la date de dépôt dans la vue détaillée d'un dossier. Comme mockup ça m'a l'air chouette :)

**Comment by fredZen** [comment]
Cette issue est encore ouverte alors qu’une PR a été acceptée et prodée sur le sujet. J’intuite que c’est pour se souvenir de traiter aussi le cas Instructeur (la PR ne semble traiter que le cas Usager)

**Comment by Keirua** [comment]
De mon coté l'issue est toujours ouverte car je n'ai pas moyen de la fermer (compréhensible).
Pour l'instructeur, je pensais faire une autre issue, mais vu que celle-ci est bien tagguée je peux continuer avec celle-ci.

Du coup, côté instructeur on pourrait ajouter l'info là:
![image](https://user-images.githubusercontent.com/1223316/52844891-f108e400-3105-11e9-9309-80187cec4cb5.png)
Pour la couleur et la taille, je pense reprendre celle de "Dossier n 3".

**Comment by Keirua** [comment]
Après avoir bricolé un peu, je vois 3 manières de mettre l'info sans trop mettre le bazar. Aucune n'est parfaite ;)
## option A: on ajoute l'info dans le breadcrumb
![optiona](https://user-images.githubusercontent.com/1223316/52845850-6970a480-3108-11e9-8464-097a378d1bbb.png)
## option B: Pareil que A, mais on ajoute une entrée de breadcrumb
![optionb](https://user-images.githubusercontent.com/1223316/52845853-6b3a6800-3108-11e9-8093-e96ada24cc40.png)
## option C: on affiche l'info dans la page de synthèse
![optionc](https://user-images.githubusercontent.com/1223316/52845854-6bd2fe80-3108-11e9-914c-0bad2adcd76b.png)

Plutôt que toucher aux infos utilisateur (la date de dépot n'en est pas vraiment une), ou dans les champs du dossier (pareil), on pourrait imaginer ajouter une carte "Dossier" avec dedans cette date de dépot (et éventuellement le statut), mais ça me parait overkill. Vous en pensez quoi?

**Comment by kemenaran** [comment]
J'aime bien l'option C (mettre ce genre d'infos dans un onglet, plutôt que dans le header). J'ai l'impression que ça nous crée un espace où afficher d'autres métadonnées du dossier au besoin.

Je me questionne juste sur l'opportunité de mettre ça dans l'encadré "Identité". Est-ce qu'on ne sortirait pas l'info "Date de dépôt du cadre", pour la mettre entre l'onglet et "Identité du demandeur" ? Ou alors on crée un nouveau cadre "Horodatage" ?

**Comment by Keirua** [comment]
Ca me va, je trouve aussi que dans la navigation c'est pas terrible
J'ai traduit tes deux propositions en options D et E. Je trouve l'option E plus sympa, mais elle prend de l'espace vertical.

# Option D

![image](https://user-images.githubusercontent.com/1223316/52966081-ae196b80-33a6-11e9-91eb-2436a4b8a0df.png)

# Option E - Carte horodatage

![image](https://user-images.githubusercontent.com/1223316/52966379-6a733180-33a7-11e9-9e70-c786136259d6.png)

**Comment by kemenaran** [comment]
À moi la E ça me semble bien 👍

Même avec plus d'espace vertical, au moins on est clair.

Mmm, sauf à la réflexion je me dis que "Horodatage" c'est peut être un gros terme technique de l'administration jargonnante : on peut p-ê faire mieux pour ne pas intimider les usagers devant le Poids De La Machine Administrative. Hmm… :réfléchit à un terme…:

**Comment by emsnytech** [comment]
La cartouche est top!
Peut être mettre le texte simplement 
Dépose le ...
On pourra mettre plus tard
Mis en instruction le ...
On aura un sujet dans le cadre des démarches déclaratives, qui n’ont pas besoin de la deuxième info ....

**Comment by Keirua** [comment]
Je m'arrête sur ça du coup:
![image](https://user-images.githubusercontent.com/1223316/52967663-0ce0e400-33ab-11e9-8d77-d475e7e25e38.png)
