### ISSUE TITLE
ETQ Admin, je souhaite que les boutons 'Enregistrer les champs' 

### ISSUE THREAD

**Issue by chaibax** [betagouv/tps#3405]
Quand on créer un gros formulaire, il faut tout le temps revenir en haut ou en bas. C'est pénible.

**Comment by fredZen** [comment]
Doublon de #2371

**Comment by emsnytech** [comment]
Binne idée.. Pb sur certains écrans à mon avis. 
Les deux boutons peuvent aussi de déplacer et se mettre systématiquement en dessous du bloc que l'on crée ou l'on modifie.
La création des blocs en bas pose un pb, car dans les longs formulaires, il faut scroller jusqu'en bas.
Il faudrait trouver un moyen de créer une barre flottante qui contienne (ajouter un bloc, enregistrer, supprimer) On règle au passage l'autre pb du déplacement des champs avec la nouvelle interface qui est galère quand on a beaucoup de champs
