### ISSUE TITLE
ETQ usager je souhaite pouvoir supprimer une zone cartographique créée

### ISSUE THREAD

**Issue by philemon95** [betagouv/tps#3410]
ETQ usager, possibilité d'ajouter une nouvelle zone, mais impossible de supprimer une zone sélectionnée, ce qui peut mener à devoir recommencer la démarche si zone sélectionnée mauvaise.
Ajouter un bouton supprimer à côté de la liste des zones sélectionnées?

**Comment by kemenaran** [comment]
En fait c'est possible – mais c'est compliqué à voir.

Il faut :

1. Cliquer sur une zone cartographique une première fois. La zone s'entoure de points
2. Cliquer au centre de la zone une deuxième fois (en notant que le curseur change, pour devenir un symbole "Supprimer"). Ça supprimera la zone.

On devrait vraiment améliorer ça (par exemple avec un bouton "Supprimer").

En attendant, c'est quelque chose qu'on peut mettre dans la FAQ.

**Comment by philemon95** [comment]
yep tu as raison, j'essaie de voir si j'y arrive et je crée une page sur le gitbook 👍
