### ISSUE TITLE
ETQ Usager je veux obtenir de l'aide

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#3432]
Aujourd'hui en tant qu'Usager, ma seule manière d'obtenir de l'aide est de contacter quelqu'un via le footer (soit les services instructeur, soit le support DS).

Il serait bien que les Usagers puissent trouver eux-même les réponses à leur questions (avant d'avoir à écrire à quelqu'un).

Pour cela, on pourrait **ajouter un bouton "Aide" dans l'interface**, qui redirige vers la FAQ (https://faq.demarches-simplifiees.fr/).

La FAQ est chercheable, et généralement un bon point d'entrée pour trouver soi-même la solution à ses problèmes.

En bas des articles de la FAQ, un footer indiquerait comment contacter un être humain (instructeur ou support DS).

**Comment by chaibax** [comment]
Je boss avec @philemon95  sur la page de contact usager V2 https://github.com/betagouv/tps/issues/3365 . On pourrais rajouter dans les réponses contextuel un lien (ou des liens) vers la FAQ .

**Comment by tchak** [comment]
- [ ] Ajouter un gros bouton "Aide" sur toutes les pages Usager (-> FAQ)
- [x] Ajouter des réponses fréquentes dans le formulaire de contact
- [ ] Ajouter un lien vers la documentation dans le footer des pages
