### ISSUE TITLE
ETQ Administrateur, Prévisualisation les parcelles cadastrales

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/tps#3439]
Je ne dois pas voir en prévisualisation les parcelles cadastrales si la case à cocher Cadastre n’a pas été cochée pour le champ « Carte » associé

**Comment by tchak** [comment]
Il faut envoyer le `type_de_champ_id` dans `app/views/shared/dossiers/editable_champs/_carte.html.haml`
```haml
- params = if champ.persisted?
  { champ_id: champ.id }
- else
  { type_de_champ_id: champ.type_de_champ_id }
```
