### ISSUE TITLE
Exception lors de l'affichage d'un dossier sans date 'en_construction'

### ISSUE THREAD

**Issue by kemenaran** [betagouv/tps#3453]
Remonté par Sentry :

```
GET https://www.demarches-simplifiees.fr/dossiers/132112/modifier

I18n::ArgumentError: Object must be a Date, DateTime or Time object. nil given.
  app/views/new_user/dossiers/show/_header.html.haml:8:in `_app_views_new_user_dossiers_show__header_html_haml__3116684722630297484_47403074366640'
    %h2 Dossier nº #{dossier.id} - Déposé le #{l(dossier.en_construction_at, format: '%d %B %Y')}
  app/views/new_user/dossiers/modifier.html.haml:7:in `_app_views_new_user_dossiers_modifier_html_haml__2359103744011839365_69896775918960'
    = render partial: 'new_user/dossiers/show/header', locals: { dossier: @dossier }
...
(161 additional frame(s) were not displayed)

ActionView::Template::Error: Object must be a Date, DateTime or Time object. nil given.
```

/cc @Keirua

**Comment by Keirua** [comment]
je prends pour le quickfix (pas d'affichage si date nulle), mais une question pertinente serait de savoir pourquoi un dossier peut ne pas avoir de en_construction_at, il me semblait forcément le cas au moment du dépot

**Comment by Keirua** [comment]
ha mais on doit pouvoir consulter des dossiers en brouillon! qui du coup n'ont pas cette date

**Comment by kemenaran** [comment]
Binoui, mais c'est effectivement curieux : normalement on ne peut pas consulter de dossiers en brouillon depuis cette page…

**Comment by Keirua** [comment]
effectivement (ce n'est pas ce template qui est appelé pour le rendu du brouillon)… mais dans tous les cas, ça ne mange pas de pain de vérifier les données à afficher
