### ISSUE TITLE
ETQ admin, je dispose d'une balise --nom du service--

### ISSUE THREAD

**Issue by Keirua** [betagouv/tps#3463]
Lors de l'onboarding de nos utilisateurs, on leur partage des templates de mail. Souvent en signature ils les modifient pour afficher le nom de leur service. Histoire de simplifier le processus, c'est à dire pour qu'ils n'aient pas à modifier chaque template (au risque de se tromper), on aimerait pouvoir leur fournir des templates avec une signature du genre "Dossier traité par --nom du service--". Il faudrait donc ajouter cette balise.

Comme le service doit forcément être rempli pour déposer un dossier, on peut imaginer que cette balise soit disponible pour tous les états. Qu'en pensez-vous ?

**Comment by kemenaran** [comment]
Ça m'a l'air d'une très bonne idée 👍
