### ISSUE TITLE
ETQ usager, je veux pouvoir cloner un dossier déjà déposé

### ISSUE THREAD

**Issue by philemon95** [betagouv/tps#3494]
utile notamment pour les démarches où seul un champ varie d'une fois à l'autre (comme la date, ou le lieu).
Eventuellement faire cocher cette feature à l'admin, car cela peut être très adapté pour des démarches (exemple: vol de drone) et beaucoup moins pour d'autres.

à communiquer: HS #12822

**Comment by mmagn** [comment]
Même issue que https://github.com/betagouv/tps/issues/1906 ?

**Comment by fredZen** [comment]
Pour moi c'est bien la même issue, du coup j'ai reporté le texte de Philémon (référence HS y comprise) et je ferme celle-ci (@philemon95, je peux te laisse rouvrir si on a mal compris ?)
