### ISSUE TITLE
ETQ usager, je souhaite pouvoir modifier la civilité renseignée dans un dossier

### ISSUE THREAD

**Issue by philemon95** [betagouv/tps#3495]
pour l'instant, je peux seulement modifier le contenu de la demande mais ni la civilité ni la date de naissance, ce qui est préjudiciable en cas de typos par exemple.

**Comment by clairevigier** [comment]
Demande assez proches pour l'urbanisme : on veut pouvoir modifier le nom prénom en cas d'erreur. On a eu des cas où lors de l'enregistrement de son dossier le pétitionnaire a inversé le Nom avec le prénom et n'est pas parvenu à le modifier en tant qu'usager

**Comment by mmagn** [comment]
@clairevigier c'est en prod :)
