### ISSUE TITLE
[RFC] ETQ administrateur je veux pouvoir anonymiser le nom de l'instructeur dans la messagerie quand besoin est

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/tps#3507]
Il semblerait d'apres : https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000031367321&cidTexte=LEGITEXT000031366350&dateTexte=20181026 que l'instructeur puisse sous certaines conditions préserver l'anonymat. Serait- ce possible de faire une case à cocher permettant à l’administrateur de choisir cette option?

**Comment by fredZen** [comment]
Doublon de #2739
