### ISSUE TITLE
ETQ instructeur je veux pouvoir voir le nom prénom du demandeur dans le dashboard, le mail n'étant pas toujours clair pour se référer à des dossiers. 

### ISSUE THREAD

**Issue by clairevigier** [betagouv/tps#3508]
Feedback métier des instructeurs qui ne retrouvent pas leurs petits. Compliqué si le mail est jeanlucdu28@gmail.com par ex... souvent ils discutent de dossier en parlant des individus concernés. 
![capture d ecran 2019-02-26 a 09 49 39](https://user-images.githubusercontent.com/36004360/53400331-e7a53480-39ad-11e9-8750-43f31864d51e.png)

**Comment by mmagn** [comment]
Hello Claire, tu peux ajouter les colonnes que tu souhaites (5 max il me semble) en cliquant sur "Personnaliser" en haut à droite du tableau, et en saisissant _nom_ et _prénom_.

**Comment by mmagn** [comment]
Tiens nous au courant si cela ne fonctionne pas comme prévu.
