### ISSUE TITLE
Rajouter une var d'env pour changer la valeur de timeout d'Unicorn

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#351]
Actuellement c'est 30 sec, du coup quand on dev et qu'on met un `byebug` dans le code, on a 30 secondes pour investiguer, pas plus.

**Comment by tchak** [comment]
unicorn is dead

**Comment by fredZen** [comment]
J'ai l'impression qu'on n'a pas le même souci avec Puma

https://github.com/puma/puma/issues/160
