### ISSUE TITLE
ETQ Adminstrateur, Paramétrage couches cartographiques

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/tps#3515]
Paramétrage de l’affichage dans admin des couches cartographiques à mettre à disposition dans le champ « Carte ».
Activer ou désactiver par exemple des « Parcelles agricoles » via le fichier `.env`

**Comment by mmagn** [comment]
Comme vu ensemble, pas de besoin pour l'instant de notre côté. 
Réouvrir si nécéssaire.
