### ISSUE TITLE
Composant générique « Champ API » 

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/tps#3516]
Evolution fonctionnelle permettant à l’Administrateur d’ajouter sur un formulaire un champ générique faisant appel à une API pour retourner des valeurs remplissant automatiquement des champs liés. Configuration par fichier de paramétrage des API disponibles.

**Comment by emsnytech** [comment]
Bonne idée !

**Comment by LeSim** [comment]
Comme vu au téléphone, on ne va pas prendre cette feature car elle demande une configuration par fichier par administration.

On pourra en rediscuter si d'autres acteurs en ont besoin.
