### ISSUE TITLE
ETQ usager, Image tronquée dans le mail de réponse

### ISSUE THREAD

**Issue by pengfeidong** [betagouv/tps#3521]
Problème d'affichage des messages automatiques.
Mauvais dimensionnement du corps de texte.
La proposition: Dans le fichier:  `app/views/layouts/mailers/layout.html.erb`, supprimer le  `line-height:22px;`

**Comment by mmagn** [comment]
HS 13350

**Comment by fredZen** [comment]
Peut-être un doublon de #3448 ?
