### ISSUE TITLE
Le champs liste des régions force un choix

### ISSUE THREAD

**Issue by guillaumelevieux** [betagouv/tps#3523]
![capture-champs-region](https://user-images.githubusercontent.com/25955430/53553968-10106880-3b3f-11e9-8449-d2729309a542.png)

L'ajout d'un champ région (dans les annotations privées) ne permet pas de laisser ce champ vierge.
La région AURA est sélectionnée de base.

Cette situation ne se présente pas pour les départements.

**Comment by fredZen** [comment]
Cousin de #3417 ?

**Comment by mmagn** [comment]
@guillaumelevieux c'est en prod !

**Comment by guillaumelevieux** [comment]
@mmagn Extra, merci !
