### ISSUE TITLE
ETQ USAGER je souhaiterais pouvoir sélectionner les colonnes que j'exporte en format tableur

### ISSUE THREAD

**Issue by philemon95** [betagouv/tps#3566]
le niveau en excel des administrations étant ce qu'il est, il y a panique quand il y a 100 colonnes dans un fichier, la possibilité de choisir les données à exporter (soit au moment de la conception ("champ exportable") soit au moment de l'export (liste des champs, cocher ceux à exporter) permettrait de résoudre le problème.

a comuniquer HS: 12830

**Comment by emsnytech** [comment]
Hum, il y a déjà me semble t’il une issues mais elle doit remonter à deux ou trois ans....
Idem choisir les dossiers à exporter

**Comment by fredZen** [comment]
Bien vu, je reporte dans #2220 et je ferme celle-ci
