### ISSUE TITLE
ETQ Usager je veux voir le moins possible la référence à DS sur les emails automatiques de changement d'état de dossier

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#3595]
Ça permettrait de réduire le nombre de gens qui nous écrivent directement (plutôt que de contacter l'administration).

**Comment by kemenaran** [comment]
Ça ressemble beaucoup à #3064 . Moi je suis chaud.

**Comment by mmagn** [comment]
@kemenaran merci ! Je ferme.
