### ISSUE TITLE
[RFC] Mails transactionnels: supprimer références à DS

### ISSUE THREAD

**Issue by philemon95** [betagouv/tps#3607]
suite à une remarque de @mmagn  hier, il est vrai que nos mails "de notification", ne fassent plus état de démarches-simplifiées. Actuellement, ils contiennent le logo beta.gouv et le logo DS, et sont signés par l'Equipe démarches-simplfiées, ce qui est une énorme source de confusion pour les usagers (qui ont souvent tendance à y répondre directement).

Propositions: 

- **supprimer nos logos**, et mettre ceux du service en charge de la démarche

- idem pour la **signature** (mettre le nom du service)

- au passage peut-être ajouter leur **numéro de téléphone** (on a une réunion avec @Benjamin-Doberset  & @emsnytech pour clarifier ça sur les mentions légales d'un AR)

- mettre une adresse **no-reply** (qui transfère sur contact, mais qui permettrait peut-être d'éviter que les gens y répondent) et mettre un lien vers le formulaire de contact

**Comment by mmagn** [comment]
Doublon de https://github.com/betagouv/tps/issues/3064 ? 
@philemon95 tu reportes ton commentaires sur l'autre issue et on ferme celle ci ?
