### ISSUE TITLE
Revoir le comportement du clique sur l'élement qui fait retourner sur root

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#384]
Particulièrement `return redirect_to backoffice_invitations_path if current_gestionnaire.avis.any?
`

(quid du cas gestionnaire qui en plus donne des avis ?)

Mais après le redesign.

Voir aussi le side effect du à #382

**Comment by kemenaran** [comment]
Ça a l'air vieux, vague, et ça référence du code mort. Je ferme.

**Comment by gregoirenovel** [comment]
En gros c'est la gestion du clic le logo du header dans le cas où t'es un instructeur. Comment ça marche aujourd'hui :
- si t'es instructeur classique, ca redirige vers les demarches, OK
- si t'es instructeur classique qui a aussi donné des avis, ca redirige vers les demarches, OK
- si t'es expert, ça redirige vers les démarches, et grace à un hook (`redirect_to_avis_if_needed`), ça redirige ensuite sur les avis

Je suis pas très fan du dernier cas, ça un peu "hack", mais je ne sais pas si ça justifie une nouvelle issue.
