### ISSUE TITLE
Erreur de comptage dossiers terminés

### ISSUE THREAD

**Issue by icollombet** [betagouv/tps#392]
![capture11](https://cloud.githubusercontent.com/assets/18182552/26721077/cc41e416-478a-11e7-8639-f246d3995e1c.PNG)

**Comment by gregoirenovel** [comment]
Ce graphique et ces stats ont été supprimés, cette issue n'est plus pertinente. (et j'ai du mal à identifier le problème sur la capture de toute manièere :) )
