### ISSUE TITLE
ETQ Tech, pouvoir supprimer une procédure

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#411]
pour l'instant procedure.destroy ne fonctionne pas

pb avec procedure.assign_to, les mails et les dossiers.

workaround partiel:
pid = 734; p = Procedure.find(pid); AssignTo.where(procedure_id: pid).delete_all; p.dossiers.destroy_all; p.destroy

**Comment by kemenaran** [comment]
Ça a l'air de fonctionner aujourd'hui, mais est-ce qu'on veut vraiment pouvoir faire ça ?

**Comment by gregoirenovel** [comment]
On nous le demande régulièrement au support

**Comment by fredZen** [comment]
Je ferme car, comme le fait remarquer @kemenaran, le problème décrit par @LeSim est résolu
