### ISSUE TITLE
Intégration de la page liste des procédures dans l'interface Administrateurs

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#416]
Avec ses trois sous-pages : Procédures publiées, Brouillons, Archivées

https://projects.invisionapp.com/d/main#/projects/prototypes/10550968

**Comment by kemenaran** [comment]
@mmagn est-ce que ça vaut le coup de garder cette issue, vu qu'on ne bosse pas activement sur le redesign de interface Admin en ce moment ?

**Comment by mmagn** [comment]
Pas forcément, au pire on la réouvrira au moment de la prioriser dans le sprint.

**Comment by gregoirenovel** [comment]
Je comprends pas le rationale de la fermeture de cette issue, à moins de fermer 75 % des issues (car visiblement on ne bosse pas activement sur plus de 25 % des issues)
