### ISSUE TITLE
Pouvoir mettre des nombres décimaux dans la catégorie "Nombre"

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/tps#420]
Au moins 2 remontés à ce sujet

**Comment by benjaminhenkel** [comment]
Tél. : 01 53 69 53 70

Anne CHEVROULET
Concepteur analyste fonctionnel
Direction des systèmes d’information

OFFICE FRANCAIS
DE L’IMMIGRATION
ET DE L’INTÉGRATION

**Comment by benjaminhenkel** [comment]
Myriam ADELAÏDE
Chef de projet MOE
Unité SI pour l'Appui aux Filières et l'Information Economique (U_SIFE) - SG/Service Informatique
Tél : 01 73 30 28 85
FranceAgriMer
12 rue Henri Rol-Tanguy
T.S.A. 20002
93555 MONTREUIL CEDEX
www.franceagrimer.fr

**Comment by emsnytech** [comment]
sujet remonté plusieurs fois l'an dernier aussi, pour ceux qui mettent en oeuvre des subventions. A rapprocher d'une autre attente qui est de choisir son unité.

**Comment by benjaminhenkel** [comment]
Mayenne

**Comment by gregoirenovel** [comment]
À communiquer : 197

**Comment by gregoirenovel** [comment]
À communiquer : 735

**Comment by gregoirenovel** [comment]
À communiquer : 825

**Comment by fredZen** [comment]
Voir aussi #930

**Comment by fredZen** [comment]
À noter qu’il est aujourd’hui possible de saisir des nombres à virgule : 

- soit en utilisant un navigateur ancien (et on en trouve dans la nature, cf. HS `#5297`)
- soit en passant par la fonction enregistrer un brouillon (saisir un nombre à virgule, enregistrer un brouillon, puis soumettre => le nombre à virgule est soumis même sur les navigateurs récents)

#764 s’est fermé sur une espèce de non-décision : on ne fait rien pour autoriser officiellement les nombres à virgule, mais on ne fait rien non plus pour les empêcher totalement.

Il me parait urgent de trancher dans un sens ou dans l’autre.

**Comment by gregoirenovel** [comment]
> Il me parait urgent de trancher dans un sens ou dans l’autre.

👍 

> soit en passant par la fonction enregistrer un brouillon (saisir un nombre à virgule, enregistrer un brouillon, puis soumettre => le nombre à virgule est soumis même sur les navigateurs récents)

À la lecture je me suis dit "sorcellerie", j'ai hate de comprendre pourquoi :)

**Comment by gregoirenovel** [comment]
Et pour contribuer un peu plus : je suis partisan de 2 types de champ : nombres entiers et nombres décimaux.

**Comment by fredZen** [comment]
>> soit en passant par la fonction enregistrer un brouillon (saisir un nombre à virgule, enregistrer un brouillon, puis soumettre => le nombre à virgule est soumis même sur les navigateurs récents)
>
> À la lecture je me suis dit "sorcellerie", j'ai hate de comprendre pourquoi :)

Voici :

1. quand tu sauves un brouillon, les contraintes semblent être neutralisées, sans doute pour éviter de retoquer les usagers sur des champs pas remplis
2. ce qui est défini par la validation html5 sur un champ numérique, c’est un incrément. Par exemple, si la valeur initiale du champ est 0 ou vide, et que l’incrément est de 1, alors les valeurs valides sont 0, 1, 2, 3, ... et aussi -1, -2, -3... Mais si la valeur initiale du champ est 1,3, par exemple parce-que tu as sauvegardé un brouillon auparavant, alors les valeurs admises deviennent 0,3, 1,3, 2,3, 3,3,... et -0,7, -1,7, -2,7... alors que les valeurs entières seront rejetées par la validation

**Comment by gregoirenovel** [comment]
OK donc en fait le problème c'est qu'on ne valide pas côté back au `2.`

**Comment by emsnytech** [comment]
Je regrette, mais là on contourne un pb. Il FAUT pouvoir rentrer des nombres avec des décimales, on a cette fonction sur tous les autres sites !

**Comment by mmagn** [comment]
Penser à exporter les données proprement, dans l'API et les CSV

**Comment by gregoirenovel** [comment]
Done with #2937 (ajout d'un champ "Nombre décimal")
