### ISSUE TITLE
Améliorer le design de l'email de confirmation d'inscription à la newsletter

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#425]

**Comment by kemenaran** [comment]
Trop vague ; je ferme. Si quelqu'un veut prendre, faites vous plaisir :)

**Comment by gregoirenovel** [comment]
Sérieux c'est infame...

<img width="1229" alt="screen shot 2018-12-18 at 12 51 42" src="https://user-images.githubusercontent.com/1333173/50152362-b6c8c500-02c3-11e9-8383-81fc1199df83.png">

Y'a du TPS qui traine en plus.

**Comment by gregoirenovel** [comment]
Mais si tu tiens à plus de détails :

- problèmes de hierarchies dans les différents texts
- supprimer la casse tout en capitales du bouton
- absence de branding

**Comment by fredZen** [comment]
@chaibax j’ai l’impression que cette fiche n’est plus d’actualité depuis qu’on a changé de système de newsletter. On ferme ?

**Comment by chaibax** [comment]
Yes !
