### ISSUE TITLE
Ajouter des logos sur la landing

### ISSUE THREAD

**Issue by icollombet** [betagouv/tps#428]
Changer le logo ministère de l'environnement, de l'énergie et de la mer en ministère de la transition écologique et solidaire (http://www.ecologique-solidaire.gouv.fr/)

Ajouter les logos suivants :
* Ministère des solidarité et de la santé (http://solidarites-sante.gouv.fr/)
* Préfecture de la Martinique (http://www.martinique.pref.gouv.fr/)
* Préfecture du Pas-de-Calais (http://www.pas-de-calais.gouv.fr/)
* Santé Publique France (http://www.santepubliquefrance.fr/)
* Agence France Entrepreneur (https://www.afecreation.fr/)

**Comment by icollombet** [comment]
@MarineCrespel Pour toi :)

**Comment by gregoirenovel** [comment]
Partiellement fait
