### ISSUE TITLE
Pour les stats d'avis, utiliser un bar_chart au lieu d'un line_chart

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#436]

**Comment by kemenaran** [comment]
Pourquoi ?

**Comment by gregoirenovel** [comment]
Comme on affiche peu de data (3 points), ça ne semble pas pertinent d'avoir une courbe

**Comment by fredZen** [comment]
J’ai l’impression que cette fiche est devenue sans objet je ne trouve pas de stat correspondant à la description. Sinon, merci de rouvrir en rajoutant une description plus précise ou une capture d’écran.

**Comment by gregoirenovel** [comment]
Simple contexte : il me semble que je parlais des stats affichées quand on est connecté ETQ super-admin, et qui montrent l'utilisation de la feature des "avis" par les instructeurs.

**Comment by fredZen** [comment]
Merci du contexte. Du coup je rouvre, la fiche a bel et bien un objet.

Note au passage : la légende de l’axe des abscisses n’est pas bonne

![capture d ecran de 2019-03-07 11-55-54](https://user-images.githubusercontent.com/356570/53952022-11f2a280-40d0-11e9-85fe-7e9d2ad0c2f2.png)

**Comment by mmagn** [comment]
Ces stats vont disparaître.
