### ISSUE TITLE
Mettre à jour la doc de l'API

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#448]
Pour `dossier#show`, on a 
```
nom_projet
description
```
dans apipie_examples.json, qui ne semblent correspondre à rien.

En profiter pour refaire une passe sur l'intégralité de la doc pour s'assurer qu'elle soit bien à jour

**Comment by kemenaran** [comment]
On a refait une passe sur la doc (https://doc.demarches-simplifiees.fr/pour-aller-plus-loin/api)
