### ISSUE TITLE
Fonction Recherche  : impossible de faire une recherche avec un entier supérieur à la valeur max int (ex: SIRET)

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/tps#478]
Il faut obligatoirement mettre quelque chose devant le numéro SIRET qui ne soit pas un chiffre (comme une lettre, une astérisque) 
Je pense que c'est parce que dès que l'on met un nombre, la fonction recherche considère que c'est un numéro de dossier. Un numéro est SIRET est bien trop long pour un numéro de dossier du coup ça le fait buggé!

**Comment by benjaminhenkel** [comment]
A ANSM

**Comment by mmagn** [comment]
Erreur : `ActiveModel::RangeError: XXXXXXXXXXXXX is out of range for ActiveModel::Type::Integer with limit 4`

Sentry issue : `2255`

**Comment by mmagn** [comment]
@kemar c'est en prod :)

**Comment by kemar** [comment]
@mmagn thanx :)

**Comment by gregoirenovel** [comment]
@mmagn contacter aussi les usagers impactés remontés par Sentry si besoin ?
