### ISSUE TITLE
Quand je consulte mon dossier en construction en tant qu'usager, j'ai un titre de section "Avis Externe " sans que l'on sache pq

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/tps#516]
![capture d ecran 2017-06-29 a 16 43 24](https://user-images.githubusercontent.com/28590367/27693619-3e56b792-5cea-11e7-9973-58e5d780aebe.png)

**Comment by kemenaran** [comment]
Corrigé avec la nouvelle UI.
