### ISSUE TITLE
Quand ETQU je repars du lien d'une procédure, pour laquelle j'ai déjà créé un dossier, on doit me demander si j'en suis certain.

### ISSUE THREAD

**Issue by emsnytech** [betagouv/tps#530]

**Comment by emsnytech** [comment]
La DRIEA se plein de création de doublons inutiles... certainement à creuser de ce coté là...

**Comment by kemenaran** [comment]
Il y a effectivement plein de doublons de brouillons. On règle ça dans le cadre de #2225 (page de garde).
