### ISSUE TITLE
ETQ Instructeur, les procédures auxquelles un administrateur m'a désigné, mais qu'il n'a pas publié, ne devrait pas apparaître dans mon tableau de bord

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/tps#536]

**Comment by kemenaran** [comment]
On filtre ça maintenant : on n'affiche que les procédures publiées ou en test.

**Comment by gregoirenovel** [comment]
Ben le problème n'est donc pas reglé : 

- d'une part si un admin pré-ajoute, avant publication et sur un brouillon publié, des instructeurs histoire de n'avoir qu'à cliquer sur "publier" le jour de la publication, il a quand même ce problème : les instructeurs vont voir apparaitre cette démarche dans leur tableau de bord avant publication

- d'autre part, j'imagine qu'on va tendre vers la suppression de la distinction entre brouillon et brouillon publié : pour moi on doit générer à la création de la démarche un slug (basé par exemple sur le titre de la démarche) histoire que l'admin puisse la tester *immédiatement*, quitte à lui faire valider / confirmer le slug juste avant la publication de sa démarche, ce qui va accentuer ce problème

Je me permets donc de réouvrir.

Annexe : j'aime pas le terme "en test", ça n'existe pas dans notre UI donc je trouve que ça ne devrait pas exister dans notre vocabulaire. Parlons de "brouillons publiés" pour le moment ?

**Comment by fredZen** [comment]
- Le terme « en test » est maintenant officialisé dans l’UI.
- La possibilité d’avoir un brouillon qui ne soit pas en test est en effet en train de disparaitre.
- Les instructeurs peuvent participer au test des procédures #3088 . Le fait qu’ils voient les procédures en test est une feature, pas un bug. Donc je referme.

**Comment by fredZen** [comment]
Voir cependant  #3333, pour un possible reliquat de problème
