### ISSUE TITLE
Réaliser un test ihm qui teste l'ensemble du parcours

### ISSUE THREAD

**Issue by LeSim** [betagouv/tps#545]
- ETQ administrateur : création d'une procédure avec qq champs
- ETQ usager : réponse à la procédure
- ETQ accompagnateur : validation du dossier
- ETQ usager : connexion a l'espace privé et visualisation du dossier

**Comment by kemenaran** [comment]
Aujourd'hui j'ai l'impression que nos tests d'acceptance couvrent ça de manière assez correcte (même s'il n'y a pas une séquence complète).

@LeSim je ferme ; je te laisse ré-ouvrir si tu penses que c'est pertinent.
