### ISSUE TITLE
Lorsqu'on clique sur un lien "commencer", rediriger vers le sign up, pas le sign in

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#549]
La plupart des personnes qui vont remplir une procédure n'ont pas encore de compte, donc rediriger vers sign up au lien de sign in.

**Comment by Flightan** [comment]
On peut garder sign in par défaut mais accorder plus de visibilité à l'autre option (sign up).

**Comment by gregoirenovel** [comment]
En effet, il faut qu'on retravaille cette page. À priori on va faire une page "arrivée sur une procédure", qui hiearchise mieux les informations et présente les différentes plus options plus clairement.

**Comment by kemenaran** [comment]
On redirige maintenant vers la page de garde de la démarche.
