### ISSUE TITLE
Pas de possibililité d'éditer un dossier pour un usager invité par un usager qui est aussi accompagnateur.

### ISSUE THREAD

**Issue by icollombet** [betagouv/tps#568]
Problème : lorsqu'un usager A est invité à co-construire le dossier d'un usager B qui a un compte multi-profil (usager + accompagnateur), l'usager A ne peut pas modifier le dossier en ligne.

Ce qui devrait se passer : lorsqu'un usager est invité par un autre usager à co-construire un dossier, il doit pouvoir modifier le dossier tant que celui-ci est en construction et n'a pas été figé pour être instruit. C'est ce qui se passe dans le cas normal, i.e. lorsque l'usager B n'est pas aussi accompagnateur.

Test : j'ai fait le test avec 2 invitations envoyées à ivan.collombet@gmail.com sur des dossiers en construction, l'un invité par tps.role3@gmail.com (seulement usager - dossier 3312), l'autre invité par ivan.collombet@beta.gouv.fr (multi-profil - dossier 3925). ivan.collombet@gmail.com peut modifier le dossier 3312 mais pas  le dossier 3925.

Problème remonté par les agences de santé - à prévenir quand c'est corrigé (voir avec Benjamin).

**Comment by benjaminhenkel** [comment]
A IRESP

**Comment by fredZen** [comment]
Corrigé par #1695 . Il reste des gens à qui on veut le communiquer ?

**Comment by fredZen** [comment]
Communiqué à Perrine de l’IRESP. Je ne sais pas à qui communiquer dans les ARS ; si personne ne fait avancer le schmilblick là dessus je ferme (j’enlève le label `à communiquer`) @icollombet @gregoirenovel
