### ISSUE TITLE
ETQ administrateur, si je supprime une procédure active,  je ne peux plus utiliser le même lien lors de la création d'une autre procédure

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/tps#584]
On a beau appuyer sur le bouton "publier", celle-ci refuse de se publier , sans aucun message d'erreur

**Comment by gregoirenovel** [comment]
Probablement la faute au ProcedurePath qui existe toujours et n'est pas hidden_at

(Je veux faire sauter ProcedurePath à terme)

**Comment by kemenaran** [comment]
ProcedurePath a sauté, et maintenant l'archivage supprime le lien.
