### ISSUE TITLE
Mettre des champs timestamp sur tous les objets

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#586]

**Comment by kemenaran** [comment]
Ça serait bien, mais j'imagine qu'on le fera quand le besoin se fera réellement sentir.

**Comment by gregoirenovel** [comment]
Quels objets : *tous*. C'est juste une bonne pratique.

J'ai le souvenir d'un debug en prod où ça manquait (j'ai plus l'exemple exact en tête comme c'était y'a plus d'un an) et qui m'avait entrainé à créer cette issue.

**Comment by tchak** [comment]
Deux tables n'ont pas de timestamps : `geo_areas` et `administrateurs_gestionnaires`
