### ISSUE TITLE
Pour les utilisateurs, faire pointer le lien "Contact" vers l'email de l'administrateur de la procédure, pas l'email de TPS

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#587]
@icollombet tu confirmes que c'est OK ?

**Comment by benjaminhenkel** [comment]
A terme, je rajouterai un champ " Adresse mail de contact" dans cette partie là de la création de la procédure : 
![capture d ecran 2017-07-12 a 11 12 44](https://user-images.githubusercontent.com/28590367/28110654-5cffa268-66f3-11e7-93a9-298c601bc939.png)

**Comment by emsnytech** [comment]
Excellente idée !

**Comment by benjaminhenkel** [comment]
Pour préciser, je parle  du contact qui se trouve en bas de cette photo (ETQ Usager donc)
![capture d ecran 2017-07-31 a 18 10 00](https://user-images.githubusercontent.com/28590367/28787125-9e96cbca-761b-11e7-8ed0-2c7e134bae9d.png)

**Comment by kemenaran** [comment]
On a maintenant un footer qui affiche les infos de contact du service.
