### ISSUE TITLE
ETQ utilisateur et instructeur je dois pouvoir supprimer une PJ que j'ai mise

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/tps#598]
ETQ usager / usager invité dans mon formulaire
ETQ instructeur dans les annotations privées

À la fois les anciennes et nouvelles PJ

Pb pour la CNIL

**Comment by benjaminhenkel** [comment]
A OFII

**Comment by gregoirenovel** [comment]
à O. Garry (CGDD) (nouvelle PJ)

**Comment by CamilleGarrigue** [comment]
@A.Ortega (DAE)

**Comment by mmagn** [comment]
@pengfeidong regarde

**Comment by gregoirenovel** [comment]
HS 7269

**Comment by gregoirenovel** [comment]
@LeSim on ferme, donc ? suite à  #2994

**Comment by gregoirenovel** [comment]
Je ferme.
