### ISSUE TITLE
Améliorer le wording des emails 

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/tps#638]
Nouvelle version du wording : https://docs.google.com/document/d/1d2pKYW3EryuUGf3c9YFIq_TAOWoCb6X18uSsUYg_b1w/edit?usp=sharing

**Comment by gregoirenovel** [comment]
D'après le wiki :

> Bonjour,
> 
> Comme convenu, je vous transmets vos identifiants à utiliser sur https://tps.apientreprise.fr/ :
> 
> Identifiant : votre adresse email
> 
> Mot de passe :
> 
> Vous avez la possibilité de définir un nouveau mot de passe en utilisant la fonction « Mot de passe oublié » lors d’une nouvelle connexion.
> 
> Si vous avez la moindre question, n’hésitez pas à me contacter.
> 
> Bien à vous,

**Comment by kemenaran** [comment]
J'ai l'impression que c'est obsolète (ça référence même TPS au lieu de DS).

Est-ce qu'on laisse ouvert ?

**Comment by gregoirenovel** [comment]
Non, on ferme.
