### ISSUE TITLE
ETQ Utilisateur, je veux pouvoir personnaliser mes CGU

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/tps#648]
A débattre mercredi 9 août

**Comment by AnthonyBrunelli** [comment]
Indispensable nous concernant, critère d'homologation Cerfa dont nous faisons la promotion:

18	Le pied de page doit faire figurer des liens vers les pages suivantes :
- Contact ;
- Plan du site ;
- Mentions légales ;
- Accessibilité ;
- Horaires et plans d'accès (si la page existe) ; 
- Démarches en ligne (si la page existe).

**Comment by mmagn** [comment]
Closed with #2725
