### ISSUE TITLE
L'heure d'envoi des pièces-jointes sous TPS est en UTC et non en UTC + 2

### ISSUE THREAD

**Issue by benjaminhenkel** [betagouv/tps#650]
![capture d ecran 2017-08-09 a 11 30 50](https://user-images.githubusercontent.com/28590367/29115091-99723922-7cf6-11e7-9c08-356779d41657.png)

Peut-être corrigé avec la nouvelle ergo ?

**Comment by kemenaran** [comment]
Plus d'actualité dans la nouvelle ergo, je crois bien.
