### ISSUE TITLE
La recherche est lente

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#818]
Ce qui fait qu'en prod on prend des 502, en particulier sur les procédures avec une forte volumétrie

Exemple : sur le compte de prod d'Ivan, partie accompagnateur, rechercher "a" -> 502. Là c'est un cas particulier mais ça doit se produire également sur des requetes classiques en cas de forte affluence sur le site

**Comment by fredZen** [comment]
Corrigé (dup de #2179)
