### ISSUE TITLE
Logguer le contenu de production.log

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#824]

**Comment by mmagn** [comment]
plus de détails @gregoirenovel ?

**Comment by gregoirenovel** [comment]
Il me semble que le contenu de production.log n'est pas accessible hors ssh sur le serveur, je me demande si ça ne serait pas bien d'avoir un meilleur moyen d'y accéder

**Comment by kemenaran** [comment]
J'ai l'impression qu'on a les outils qu'il faut pour déboguer. Je ferme.
