### ISSUE TITLE
Améliorer l'erreur SIRET

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#891]
Demander à l'utilisateur de s'assurer que son SIRET est bien correct

Cf. https://secure.helpscout.net/docs/59eda64b0428630253621180/article/59eda6f40428630253621183/

**Comment by gregoirenovel** [comment]
- Vérifier qu'il a bien 14 chiffres et pas 9 (SIREN)
- Vérifier qu'il est bien valide
  * est-ce que sur ce dernier point, en cas de changement, on peut pas aller taper directement sur API Entrepirse et aller chercher le bon nouveau SIRET ?

**Comment by kemenaran** [comment]
Depuis le refacto de la page SIRET on est assez bon là dessus

**Comment by gregoirenovel** [comment]
Quid du "est-ce que sur ce dernier point, en cas de changement, on peut pas aller taper directement sur API Entrepirse et aller chercher le bon nouveau SIRET ?" ?
