### ISSUE TITLE
ETQ Admin je veux pouvoir uploader un fichier type lorsque je créé un champ PJ

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#932]
Aujourd'hui on ne peut mettre qu'un lien. 
C'est compliqué à utiliser, cela nécessite de passer par un service tiers pour le stockage.

**Comment by CamilleGarrigue** [comment]
@B.R (médailles)

**Comment by mmagn** [comment]
Est ce qu'on permettrait pas d'uploader un fichier sur les champs explication ? Ce serait plus générique... trop ?

**Comment by gregoirenovel** [comment]
Ça semble casse gueule, non ?

**Comment by mmagn** [comment]
C'est à dire ? Niveau UX ? C'est vrai que lier ça au champ PJ ça permet de contrôler les mises en formes. Et vu la simplicité d'ajouter un fichier avec active storage, on peut se le permettre.

**Comment by gregoirenovel** [comment]
Conceptuellement déjà ça me semble mieux de mettre le modèle au niveau de la PJ qui contiendra ce modèle modifié.

Ensuite si on met ça au niveau de la description ça veut dire qu'une explication => 1 modèle PJ max, certains vont nous demander comment faire pour mettre 2 modèles, on va dire qu'il faut mettre 2 explications, bref, ça me semble pas intuitif.

**Comment by mmagn** [comment]
De toute façon on va limiter : 1 PJ modèle / 1 champ PJ non ?

**Comment by gregoirenovel** [comment]
Engagement pour le 15/04

à communiquer : `B. Reveillault, Rhone`
